import { life } from "./build";

export const MIDWEST = [
  life({
    id: "in-insulin",
    protagonist: "Rachel Holland",
    dossierTag: "PRICING STRATEGIST",
    householdName: "The Hollands",
    location: "Carmel, IN",
    tagline: "Drug pricing strategist, 42. Purdue MBA. Her brother is a Type 1 diabetic.",
    description:
      "Rachel Holland grew up in Kokomo, where her dad worked at the transmission plant. She's spent fifteen years at a drug company in Indianapolis, the kind that sponsors the Little League and the symphony. Her brother Nate has had Type 1 diabetes since he was nine. She pays for his insulin herself.",
    perspective:
      "The list price isn't the real price. The middlemen take rebates, the insurers take their cut, and the company gets blamed. Everybody in the chain is getting paid off the sticker price, so nobody wants to lower it — including us.",
    closingAddendum:
      "You were dealt a good job at a company that makes something people die without. You paid for your brother's insulin. Who paid for everyone else's?",
    seat: {
      title: "The Pricing Strategist",
      role: "Director of Pricing Strategy",
      color: "#BF3F3F",
      scoreLabel: "NET REVENUE",
      dial: ["price for patients", "price for the rebate game"],
      dialNote: "a higher list price means a bigger rebate to the middlemen",
      board: "EXECUTIVE TEAM",
      firedBody:
        "The executive team brought in a pricing lead from a rival who'd raised insulin prices eleven times in eight years. He did it twice more. The company's stock hit a record high.",
      pressure: [
        "The CFO said your pricing recommendation 'leaves money on the table.'",
        "The executive team is meeting with a pricing consultant. You weren't invited.",
      ],
      ranks: [
        ["Director", "a team of analysts"],
        ["Senior Director", "the diabetes portfolio"],
        ["VP of Pricing", "the whole company's list prices"],
        ["Chief Commercial Officer", "the earnings call"],
        ["CEO", "a jet and a museum wing"],
        ["Board Member", "three pharma boards"],
      ],
      intro: [
        "You're Rachel Holland. You set the list price of your company's insulin. A vial costs about $6 to make.",
        "The lights on the wall are people with diabetes and the families paying for it: the uninsured, the underinsured, and people like your brother.",
        "The executive team watches net revenue. There's a dial between pricing for patients and pricing for the rebate game.",
        "The middlemen want a high list price so they can collect a bigger rebate. The patient without insurance pays the list price.",
      ],
      introCta: "Open the pricing model ›",
      capture: "List price up 10%. Revenue beat estimates. A man in Minneapolis died rationing his insulin.",
      protect: "You held the price. The middlemen dropped your insulin from their formularies.",
      outLabel: "FALLOUT THIS QUARTER",
      fired: "Someone else raised the price anyway. What would have had to change for a $6 drug not to cost $300?",
      ended: "The stock is at a record high. How many people rationed a vial to get you here?",
      turns: [
        [2010, "THE COMPETITOR RAISES INSULIN 12%", "Hold your price", "Match it, within the week", "$"],
        [2012, "THE MIDDLEMEN WANT BIGGER REBATES", "Lower the list price instead", "Raise the list price to fund the rebate", "$"],
        [2014, "A NEW PEN COSTS MORE · THE OLD VIAL STILL WORKS", "Keep the vial cheap", "Discontinue the vial", "✂"],
        [2016, "A PATENT EXTENSION ON A SMALL TWEAK", "Let the generic come", "File forty new patents", "§"],
        [2018, "DEATHS FROM RATIONING MAKE THE NEWS", "Cut the list price in half", "Announce a 'patient assistance' program", "⚡"],
        [2020, "CONGRESS PROPOSES A $35 CAP", "Support it publicly", "Lobby against it quietly", "⚡"],
        [2023, "THE CAP PASSES FOR MEDICARE ONLY", "Extend it to everyone", "Keep the uninsured at list price"],
      ],
    },
  }),

  life({
    id: "ia-meatpacking",
    protagonist: "Ana Morales",
    dossierTag: "PLANT HR MANAGER",
    householdName: "The Moraleses",
    location: "Storm Lake, IA",
    tagline: "HR manager at the pork plant, 33. Born in Michoacán, raised in Storm Lake. Her dad still works the kill floor.",
    description:
      "Ana Morales came to Storm Lake at six. Her dad has worked the kill floor at the pork plant for twenty-four years; her mom cleans the plant at night. Ana went to Buena Vista University, the first in her family to graduate, and the plant hired her to recruit and manage the people who look like her parents.",
    perspective:
      "The plant built this town. Laotians, Mexicans, Sudanese, Burmese — everybody came for the plant, and the plant needs every one of us. But the line speed is the line speed, and my job is to keep it filled.",
    closingAddendum:
      "You were dealt the office above the kill floor your father works. Your job was to keep the line full, and your family was on it.",
    seat: {
      title: "The HR Manager",
      role: "HR Manager, Pork Plant",
      color: "#BF7F5F",
      scoreLabel: "LINE SPEED",
      dial: ["protect the workers", "fill the line"],
      dialNote: "turnover is 100% a year, and the line never stops",
      board: "PLANT MANAGER",
      firedBody:
        "The plant hired a staffing agency to recruit and manage the line. They brought in workers from farther away, with less English and fewer questions. Turnover went up. So did the injuries.",
      pressure: [
        "The plant manager says the line was short twelve people on second shift.",
        "Corporate is piloting a staffing agency at the Nebraska plant. They're watching your numbers.",
      ],
      ranks: [
        ["HR Manager", "an office above the floor"],
        ["HR Director", "three plants"],
        ["Regional VP", "the whole Midwest"],
        ["Corporate VP", "the company's workforce strategy"],
        ["Industry Spokesperson", "Congress hears from you"],
        ["Consultant", "other plants pay for your playbook"],
      ],
      intro: [
        "You're Ana Morales. The plant processes 18,000 hogs a day. The line runs as fast as the USDA allows, and the company is always asking for faster.",
        "The lights on the wall are the plant's workers and the town they built: churches in five languages, the Mexican grocery, the Sudanese restaurant, the high school that won state in soccer.",
        "The plant manager watches line speed. There's a dial between protecting the workers and filling the line.",
        "Your dad's hands don't close all the way anymore. He says it's fine.",
      ],
      introCta: "Walk the floor ›",
      capture: "The line ran at full speed. Three carpal tunnel cases went unreported this month.",
      protect: "You slowed the hiring push and fixed the ergonomics. The plant manager said the line was short.",
      outLabel: "FALLOUT THIS SHIFT",
      fired: "An agency filled the line anyway. What would have had to change for 18,000 hogs a day not to cost somebody's hands?",
      ended: "The plant never stopped. How are your father's hands?",
      turns: [
        [2014, "A NEW RULE LETS THE LINE RUN FASTER", "Keep the old speed", "Speed it up, the rule says you can", "⚙"],
        [2016, "INJURIES ON THE LINE ARE UNDER-REPORTED", "Log every one", "Send them to the plant nurse, keep it off the log", "✂"],
        [2018, "RECRUITERS BRING WORKERS FROM PUERTO RICO", "Pay for their housing", "Let them find their own — it's a free country"],
        [2019, "ICE RAIDS A PLANT TWO STATES OVER", "Help your workers get legal help", "Tell corporate you'll cooperate"],
        [2020, "THE PANDEMIC · WORKERS ARE SICK", "Close the plant for two weeks", "Keep it open; the President says it's essential", "✂"],
        [2022, "UNION CARDS APPEAR IN THE LOCKER ROOM", "Stay neutral", "Hold mandatory meetings on 'the union's cost'", "⚡"],
        [2024, "A PROPOSAL TO LET TEENS WORK THE CLEANUP SHIFT", "Refuse", "Hire them; it's legal now"],
      ],
    },
  }),

  life({
    id: "ks-tax-experiment",
    protagonist: "Greg Brandt",
    dossierTag: "STATE SENATOR",
    householdName: "The Brandts",
    location: "Hutchinson, KS",
    tagline: "State senator, 55. Owns an insurance agency. Chairs the tax committee.",
    description:
      "Greg Brandt grew up on a wheat farm near Hutchinson. He sold crop insurance for twenty years, then ran for the state senate because he was tired of complaining about taxes at the Rotary Club. He's a deacon at his church and his wife Janet teaches second grade.",
    perspective:
      "Every dollar the government takes is a dollar a family doesn't get to spend. Cut taxes, and business will come. That's what everybody said. We just didn't expect the business to be quite so slow.",
    closingAddendum:
      "You were dealt a seat and an idea everybody believed. The schools found out what the idea cost before anyone else did — your wife's among them.",
    seat: {
      title: "The Tax Chair",
      role: "Chair, Senate Tax Committee",
      color: "#BFA33F",
      scoreLabel: "TAX CUTS",
      dial: ["fund the schools", "keep the cuts"],
      dialNote: "the cut pays for itself, the governor says",
      board: "CAUCUS",
      firedTitle: "PRIMARIED",
      firedBody:
        "A group funded by out-of-state donors ran a challenger against you in the primary. He won by nine hundred votes, then voted for every cut on the table.",
      pressure: [
        "The caucus leader says your vote on the budget bill is 'being watched.'",
        "A political action committee just bought TV ads in your district calling you a tax-raiser.",
      ],
      ranks: [
        ["State Senator", "a seat and a desk"],
        ["Committee Chair", "the tax bills go through you"],
        ["Majority Leader", "the whole agenda"],
        ["Governor's Pick", "the budget office"],
        ["Congressman", "a seat in Washington"],
        ["Think Tank Fellow", "the model is exported to other states"],
      ],
      intro: [
        "You're Greg Brandt. The governor has promised a 'real live experiment': cut income taxes deep and watch Kansas boom.",
        "The lights on the wall are Kansans: teachers, highway workers, small business owners, and the kids in schools the budget pays for.",
        "Your caucus watches whether you keep the cuts. There's a dial between funding the schools and keeping the cuts.",
        "You believe in it. Most of the people who elected you do too.",
      ],
      introCta: "Gavel in the committee ›",
      actLabel: "VOTE",
      capture: "The cut passed. The budget hole grew by $200 million. The school district in Hutchinson went to a four-day week.",
      protect: "You voted to restore funding. The caucus stripped you of your committee seat, then restored it.",
      outLabel: "FALLOUT THIS SESSION",
      fired: "Someone else voted for it anyway. What would have had to change for a budget to add up?",
      ended: "The cuts held. Did the boom come?",
      turns: [
        [2012, "THE GOVERNOR'S TAX PLAN · ZERO INCOME TAX FOR BUSINESS OWNERS", "Vote for a smaller cut", "Vote for the full cut", "$"],
        [2013, "THE BUDGET IS $300 MILLION SHORT", "Delay the next round of cuts", "Cut spending instead", "✂"],
        [2014, "THE STATE'S CREDIT RATING IS DOWNGRADED", "Say the experiment isn't working", "Say it needs more time", "⚡"],
        [2015, "THE HIGHWAY FUND IS RAIDED TO COVER THE HOLE", "Oppose the raid", "Vote for the transfer", "✂"],
        [2016, "SCHOOLS CLOSE EARLY FOR LACK OF MONEY", "Vote to restore school funding", "Blame the court for overreaching", "⚡"],
        [2017, "A BIPARTISAN BILL TO REPEAL THE CUTS", "Vote for repeal", "Vote to sustain the veto", "✎"],
        [2024, "A NEW FLAT-TAX PROPOSAL", "Remember what happened", "Sign on as a co-sponsor", "✎"],
      ],
    },
  }),

  life({
    id: "mi-flint",
    protagonist: "Sharon Jackson",
    dossierTag: "CITY FINANCE DIRECTOR",
    householdName: "The Jacksons",
    location: "Flint, MI",
    tagline: "City finance director, 51. Born in Flint. Her father built Buicks for thirty-two years.",
    description:
      "Sharon Jackson went to Northwestern High and Michigan State, and came home to work for the city she grew up in. She's watched Flint lose half its people. Her son Darius is a junior at Southwestern Academy. Her mother lives four blocks away, in the house Sharon grew up in.",
    perspective:
      "The state says Flint can't manage its own money, so it sends someone to do it for us. I work for him now. You can quit and let somebody who doesn't know this town run the numbers, or you can stay and try to keep them from breaking something.",
    closingAddendum:
      "You were dealt the city you grew up in, run by someone the state sent. The water came out of the tap in your mother's house too.",
    seat: {
      title: "The Finance Director",
      role: "Finance Director, City of Flint",
      color: "#3F7FBF",
      scoreLabel: "SAVINGS",
      dial: ["the residents", "the budget"],
      dialNote: "the emergency manager answers to Lansing, not to Flint",
      board: "EMERGENCY MANAGER",
      firedBody:
        "The emergency manager replaced you with a consultant from Lansing who'd never lived in Flint. He signed off on everything you wouldn't.",
      pressure: [
        "The emergency manager says your department is 'resisting efficiencies.'",
        "The state treasurer's office asked for your department's full correspondence. They're building a file.",
      ],
      ranks: [
        ["Finance Director", "the city's checkbook"],
        ["Deputy City Administrator", "every department's budget"],
        ["City Administrator", "the whole city, when the state lets you"],
        ["State Appointee", "a seat on the review board"],
        ["State Treasurer's Office", "other cities' emergency managers"],
        ["Consultant", "you advise other bankrupt cities"],
      ],
      intro: [
        "You're Sharon Jackson. Flint is broke. The state has appointed an emergency manager who can overrule the mayor and the council. You work for him now.",
        "The lights on the wall are Flint: your neighbors, your old teachers, the family who's lived next to your mother for forty years.",
        "The emergency manager watches savings. There's a dial between protecting the residents and balancing the budget.",
        "The city is about to switch water sources to save $5 million. Nobody has asked what's in the river.",
      ],
      introCta: "Sign in at City Hall ›",
      capture: "The budget balanced. The water in your mother's tap turned the color of weak tea.",
      protect: "You flagged it in writing. The emergency manager sent it to Lansing, and nobody wrote back.",
      outLabel: "FALLOUT THIS MONTH",
      fired: "Someone from Lansing signed it anyway. What would have had to change for a city like Flint to control its own water?",
      ended: "The city's books are balanced. How many kids in Flint have lead in their blood?",
      turns: [
        [2011, "THE STATE APPOINTS AN EMERGENCY MANAGER", "Speak out against it", "Stay on and work with him"],
        [2013, "A NEW PIPELINE WILL SAVE $5 MILLION", "Stay on Detroit's water until it's ready", "Switch to the Flint River now", "$"],
        [2014, "THE RIVER WATER ISN'T TREATED FOR CORROSION", "Pay for the treatment", "It's $100 a day; skip it", "✂"],
        [2014, "RESIDENTS COMPLAIN THE WATER SMELLS", "Demand an independent test", "Say it meets standards", "⚗"],
        [2015, "A DOCTOR FINDS LEAD IN CHILDREN'S BLOOD", "Back her findings publicly", "Question her data", "⚡"],
        [2016, "BOTTLED WATER ARRIVES · THE PIPES STAY", "Push to replace every pipe", "Distribute water, wait for federal money"],
        [2018, "THE STATE ENDS FREE BOTTLED WATER", "Fight to keep it", "Say the water is safe now"],
      ],
    },
  }),

  life({
    id: "mo-municipal-fines",
    protagonist: "Linda Schmidt",
    dossierTag: "CITY ADMINISTRATOR",
    householdName: "The Schmidts",
    location: "North St. Louis County, MO",
    tagline: "City administrator, 48. Runs a town of 9,000. A third of its budget comes from fines.",
    description:
      "Linda Schmidt grew up in St. Charles and got a public administration degree from Mizzou. She's run a small municipality in north county for eight years. The town was mostly white when she was born; it's mostly Black now. She lives thirty minutes away.",
    perspective:
      "The tax base left when the plants did. The state won't let us raise taxes without a vote nobody will pass. So the town is funded by the court. I didn't design it. I'm just trying to keep the lights on in City Hall.",
    closingAddendum:
      "You were dealt a town that had to fund itself somehow. It ended up funded by its own residents, one ticket at a time.",
    seat: {
      title: "The City Administrator",
      role: "City Administrator",
      color: "#7F5FBF",
      scoreLabel: "COURT REVENUE",
      dial: ["the residents", "the budget"],
      dialNote: "the court pays for the police",
      board: "COUNCIL",
      firedBody:
        "The council hired an administrator from a neighboring town where fines paid for 40% of the budget. He brought his police chief with him. The municipal court docket doubled.",
      pressure: [
        "The finance committee says court revenue is short of the budget projection.",
        "The mayor says the police chief 'has ideas' about traffic enforcement, and wants you to listen.",
      ],
      ranks: [
        ["Administrator", "a town of 9,000"],
        ["County Rising Star", "the county municipal league"],
        ["Larger City", "a suburb with a real tax base"],
        ["State Association", "you speak for Missouri's cities"],
        ["Consultant", "other towns hire your model"],
        ["Court Vendor", "a stake in the ticket software"],
      ],
      intro: [
        "You're Linda Schmidt. Your town of 9,000 has its own mayor, council, police department, and municipal court. It has almost no tax base.",
        "The lights on the wall are residents: nurses and bus drivers and retirees, most of them Black, most of them one ticket away from a warrant.",
        "The council watches court revenue. There's a dial between protecting the residents and balancing the budget.",
        "A $100 ticket becomes $400 with fees. A missed court date becomes a warrant. A warrant becomes a job lost.",
      ],
      introCta: "Open the budget ›",
      capture: "Court revenue up 18%. A mother of three spent a weekend in jail over an unpaid parking ticket.",
      protect: "You capped the fees. The council asked how you plan to pay the police.",
      outLabel: "FALLOUT THIS BUDGET",
      fired: "Someone else ran the court anyway. What would have had to change for a town to fund itself without ticketing its residents?",
      ended: "The budget balanced. How many people in town have a warrant?",
      turns: [
        [2008, "THE RECESSION · SALES TAX REVENUE DROPS", "Cut the administration's budget", "Tell the police to write more tickets", "⚡"],
        [2010, "A 'FAILURE TO APPEAR' FEE", "Waive it for first offenses", "Add it to every missed date", "$"],
        [2012, "THE COURT MEETS ONCE A MONTH, AT NIGHT", "Add more court dates", "Keep it; the backlog brings fees"],
        [2014, "FERGUSON · THE WHOLE COUNTRY IS WATCHING", "Audit your own court", "Say your town is different", "⚡"],
        [2015, "THE STATE CAPS FINE REVENUE AT 20%", "Comply fully", "Reclassify fines as 'fees'", "§"],
        [2018, "A PRIVATE PROBATION COMPANY OFFERS A CONTRACT", "Keep probation public", "Let them charge the defendants", "$"],
        [2022, "A PROPOSAL TO MERGE WITH THE NEIGHBORING TOWNS", "Support the merger", "Protect your town's court"],
      ],
    },
  }),

  life({
    id: "ne-railroad",
    protagonist: "Mike Kucera",
    dossierTag: "TRAINMASTER",
    householdName: "The Kuceras",
    location: "North Platte, NE",
    tagline: "Railroad trainmaster, 47. Czech-Catholic. Three generations at Bailey Yard.",
    description:
      "Mike Kucera's grandfather worked the yard in North Platte during the war, when the whole town met every troop train with sandwiches. His dad was a conductor. Mike started as a switchman at nineteen and now manages the crews that build the trains. His wife Kristy runs a daycare out of their house.",
    perspective:
      "The railroad made this town, and it's still the best job in western Nebraska. But it's run from Omaha by people who watch the stock. They call it precision. What they mean is fewer people running longer trains.",
    closingAddendum:
      "You were dealt the job your grandfather was proud of. It got longer, faster, and emptier — by your hand.",
    seat: {
      title: "The Trainmaster",
      role: "Trainmaster, Bailey Yard",
      color: "#BF9F3F",
      scoreLabel: "OPERATING RATIO",
      dial: ["run it safe", "run it lean"],
      dialNote: "Wall Street grades railroads on operating ratio",
      board: "SUPERINTENDENT",
      firedBody:
        "The superintendent brought in a trainmaster from a railroad that runs three-mile trains with two-person crews. He cut the car inspectors by half. The derailments are someone else's town.",
      pressure: [
        "The superintendent said your yard's dwell time is 'unacceptable.'",
        "Omaha sent a consultant to shadow you for a week. He takes a lot of notes.",
      ],
      ranks: [
        ["Trainmaster", "the yard's crews"],
        ["Terminal Superintendent", "the whole yard"],
        ["Division Superintendent", "trains from Denver to Omaha"],
        ["VP of Operations", "the whole network"],
        ["COO", "the operating ratio is yours"],
        ["Industry Board", "the rail lobby"],
      ],
      intro: [
        "You're Mike Kucera. Bailey Yard is the biggest rail yard in the world. You run the crews that build and inspect the trains.",
        "The lights on the wall are railroaders and railroad towns: engineers, conductors, car inspectors, and every town along the tracks where the trains roll through.",
        "The superintendent watches the operating ratio. There's a dial between running it safe and running it lean.",
        "Every railroad in America is making the same cuts. The towns along the tracks don't get a vote.",
      ],
      introCta: "Walk the yard ›",
      capture: "Operating ratio down two points. The trains are two miles long now. A crossing in Kearney was blocked for forty minutes while an ambulance waited.",
      protect: "You kept the inspectors on. Omaha asked why your ratio is the worst in the division.",
      outLabel: "FALLOUT THIS MONTH",
      fired: "Someone else ran it lean anyway. What would have had to change for a railroad to be graded on safety?",
      ended: "The railroad is more profitable than ever. What happened in the towns along the tracks?",
      turns: [
        [2017, "OMAHA ANNOUNCES 'PRECISION SCHEDULED RAILROADING'", "Keep the crews and the schedules", "Implement it fast"],
        [2018, "LONGER TRAINS · TWO MILES AND GROWING", "Keep trains under a mile", "Build them as long as possible", "⚙"],
        [2019, "CAR INSPECTORS GET 30 SECONDS PER CAR", "Keep it at two minutes", "Enforce the 30 seconds", "✂"],
        [2020, "THE PANDEMIC · FREIGHT DROPS 20%", "Keep the crews on", "Furlough a third of the yard", "✂"],
        [2022, "A RAIL STRIKE OVER SICK DAYS", "Back the crews publicly", "Tell the crews to cross the line"],
        [2023, "A DERAILMENT IN OHIO · A TOWN EVACUATED", "Push for a safety review", "Say it couldn't happen here"],
        [2024, "OMAHA WANTS ONE-PERSON CREWS", "Oppose it", "Pilot it in your yard", "✂"],
      ],
    },
  }),

  life({
    id: "nd-oil-boom",
    protagonist: "Kyle Halvorson",
    dossierTag: "RIG MANAGER",
    householdName: "The Halvorsons",
    location: "Williston, ND",
    tagline: "Roughneck turned rig manager, 24. Makes $140,000. Lives in a camper.",
    description:
      "Kyle Halvorson grew up on a farm outside Minot and came to Williston at nineteen when the boom hit. He started on a drilling crew, got promoted fast, and now manages a rig. He sends money home to his mom. His girlfriend Kayla is a nurse at the hospital in Williston, where they see a lot of the same injuries.",
    perspective:
      "Nobody here asked for a boom. But when it came, a kid with no degree could make six figures. That's the American dream, and it's real. You work hard, you take the risk, you get paid.",
    closingAddendum:
      "You were dealt a boom where a kid could make six figures. The risk was real, and you got paid for it. Not everybody on your crew did.",
    seat: {
      title: "The Rig Manager",
      role: "Rig Manager",
      color: "#3F3F3F",
      scoreLabel: "BARRELS PER DAY",
      dial: ["keep the crew safe", "keep the rig turning"],
      dialNote: "a rig costs $30,000 a day to run, stopped or not",
      board: "OPERATOR",
      firedBody:
        "The operator replaced you with a manager from Texas who'd run rigs through two booms. He cut the safety meetings to Mondays only. The rig never stopped.",
      pressure: [
        "The operator's company man says your rig is behind schedule.",
        "The operator is sending a manager from Midland to 'help.' Everyone knows what that means.",
      ],
      ranks: [
        ["Rig Manager", "a rig and a crew of twenty"],
        ["Superintendent", "six rigs in the Bakken"],
        ["Operations Manager", "the whole field"],
        ["VP", "an office in Houston"],
        ["Owner", "your own service company"],
        ["Oil Money", "a lake house and a boat"],
      ],
      intro: [
        "You're Kyle Halvorson. You run a drilling rig in the Bakken. The oil companies are paying whatever it takes to get the wells drilled before prices drop.",
        "The lights on the wall are the Bakken: roughneck crews, ranchers with wells on their land, and Williston families whose rent went up 400%.",
        "The operator watches barrels per day. There's a dial between keeping the crew safe and keeping the rig turning.",
        "Oilfield work is some of the most dangerous in America. Everybody knows somebody.",
      ],
      introCta: "Climb the rig ›",
      capture: "The well came in on schedule. A derrickhand fell from forty feet; the report said 'human error.'",
      protect: "You shut the rig down for a safety stand-down. The operator's company man was on the phone before lunch.",
      outLabel: "FALLOUT THIS WELL",
      fired: "Someone else kept it turning anyway. What would have had to change for a boom not to burn through its workers?",
      ended: "The boom made you rich. What's left in Williston?",
      turns: [
        [2011, "THE BOOM · RIGS RUNNING 24/7", "Hire and train slowly", "Hire anyone who can pass a drug test"],
        [2012, "SIXTEEN-HOUR SHIFTS · THE CREW IS EXHAUSTED", "Cap shifts at twelve hours", "Keep them at sixteen; they want the overtime", "⚙"],
        [2013, "NATURAL GAS IS BEING FLARED · THERE'S NO PIPELINE", "Push the operator to capture it", "Flare it; it's cheaper", "▲"],
        [2014, "A SALTWATER SPILL ON A RANCHER'S PASTURE", "Report it immediately", "Clean it up quietly", "✂"],
        [2015, "PRICES CRASH · RIGS SHUT DOWN", "Keep your crew as long as you can", "Lay off half, keep the best", "✂"],
        [2018, "THE BOOM RETURNS · FEWER WORKERS, MORE AUTOMATION", "Keep a full crew", "Run it with half the crew", "⚙"],
        [2022, "THE COMPANY IS BOUGHT BY A LARGER FIRM", "Stay and protect your crew", "Take the buyout and go"],
      ],
    },
  }),

  life({
    id: "sd-trusts",
    protagonist: "Scott Lindgren",
    dossierTag: "TRUST OFFICER",
    householdName: "The Lindgrens",
    location: "Sioux Falls, SD",
    tagline: "Trust company president, 52. Lutheran. Coaches his daughter's volleyball team.",
    description:
      "Scott Lindgren grew up in Mitchell, where his dad ran the hardware store. He went to Augustana and then law school, and came home to work at a small Sioux Falls trust company. South Dakota changed its laws, and that company now holds hundreds of billions of dollars for families from all over the world.",
    perspective:
      "South Dakota didn't break any laws. We wrote better ones. If a family wants to keep its money private and pass it down forever, why shouldn't they? Every state competes for business. We just won.",
    closingAddendum:
      "You were dealt a hardware store kid's life in a state that learned to sell secrecy. The money stayed hidden, and the tax bills landed on everyone who couldn't hide theirs.",
    seat: {
      title: "The Trust Officer",
      role: "President, Trust Company",
      color: "#3F5FBF",
      scoreLabel: "ASSETS HELD",
      dial: ["know your client", "don't ask"],
      dialNote: "a dynasty trust never pays estate tax, ever",
      board: "SHAREHOLDERS",
      firedBody:
        "The shareholders sold the company to a larger trust firm that asks no questions at all. Its client list includes two sanctioned oligarchs and a family that owns half of a Latin American country.",
      pressure: [
        "A shareholder asked why your firm's assets grew slower than the competitor's.",
        "The shareholders are taking a call from a larger firm that wants to buy you.",
      ],
      ranks: [
        ["Trust Officer", "a desk in Sioux Falls"],
        ["President", "the whole company"],
        ["Industry Leader", "the legislature writes your bills"],
        ["Billionaire Whisperer", "families fly in on private jets"],
        ["Firm Owner", "a stake in the assets"],
        ["Legacy", "a wing at the Sioux Falls hospital"],
      ],
      intro: [
        "You're Scott Lindgren. South Dakota has no income tax, no estate tax, and trust laws that let the wealthy keep their money secret and pass it down forever.",
        "The lights on the wall are everyone else: the people whose taxes go up when the wealthiest pay none, in South Dakota and in every country where the money came from.",
        "Your shareholders watch assets held. There's a dial between knowing your client and not asking.",
        "Nobody in Sioux Falls knows whose money is in the building. That's the product.",
      ],
      introCta: "Open the vault ›",
      capture: "A family from overseas moved $400 million into a dynasty trust. The paperwork said 'estate planning.'",
      protect: "You turned down a client whose money you couldn't trace. He went to the firm across the street.",
      outLabel: "FALLOUT THIS QUARTER",
      fired: "Another firm took the money anyway. What would have had to change for secrecy not to be a state's business model?",
      ended: "South Dakota holds more than half a trillion dollars in trust. Whose taxes paid for that?",
      turns: [
        [1997, "THE LEGISLATURE ABOLISHES THE RULE AGAINST PERPETUITIES", "Stay a small local trust company", "Market dynasty trusts nationwide", "∞"],
        [2005, "A BILL TO SEAL TRUST RECORDS FROM COURTS", "Oppose the secrecy provision", "Help draft it", "§"],
        [2010, "WEALTHY FOREIGN CLIENTS START CALLING", "Require full disclosure of sources", "Accept what the lawyers send", "$"],
        [2014, "OTHER STATES COPY THE LAW", "Let the competition come", "Lobby for even more secrecy", "§"],
        [2016, "THE PANAMA PAPERS · CLIENTS WANT A NEW HAVEN", "Turn away the shell companies", "Welcome the money home", "$"],
        [2019, "A CLIENT IS ON A SANCTIONS WATCH LIST", "Close the account", "It's not a sanction yet; keep it"],
        [2021, "THE PANDORA PAPERS NAME SOUTH DAKOTA", "Call for reform publicly", "Defend the industry to the press", "⚡"],
      ],
    },
  }),
];
