import { life } from "./build";

export const NORTHEAST = [
  life({
    id: "ct-newspapers",
    protagonist: "Caroline Whitmore",
    dossierTag: "PRIVATE EQUITY PARTNER",
    householdName: "The Whitmores",
    location: "Greenwich, CT",
    tagline: "Private equity partner, 47. Two kids at Greenwich Country Day. A house on the water.",
    description:
      "Caroline Whitmore grew up in Hartford, where her father set type at the Courant for thirty years. She went to Yale on aid and to Wharton on loans. Now she runs a fund that buys local newspapers — because they're cheap, and the real estate under them isn't.",
    perspective:
      "Nobody forced anybody to stop subscribing. The papers were dying before we bought them. We just stopped pretending they weren't. Somebody was going to own the decline. Better it be someone who reads the balance sheet.",
    closingAddendum:
      "You were dealt the life that bought the paper your father set type for. The limited partners got their return. The towns got silence.",
    seat: {
      title: "The Fund Partner",
      role: "Partner, Media Fund",
      mode: "attn",
      color: "#8C7AB8",
      scoreLabel: "EBITDA",
      dial: ["keep the newsroom", "harvest the masthead"],
      dialNote: "a newspaper's building is worth more than its reporters",
      board: "LPs",
      firedBody:
        "The limited partners moved their money to a fund in Manhattan that owns two hundred papers and runs them from a single copy desk. Your papers were folded in by Christmas.",
      pressure: [
        "An LP asked on the quarterly call why your fund's margins trail the sector.",
        "Two of your biggest LPs declined to commit to Fund IV. The founding partner wants a word.",
      ],
      ranks: [
        ["Partner", "a carried interest and a corner office"],
        ["Senior Partner", "your name on the fund"],
        ["Managing Partner", "a seat on eleven boards"],
        ["Media Mogul", "two hundred mastheads"],
        ["Billionaire", "a Palm Beach address"],
        ["Philanthropist", "a journalism school named for you"],
      ],
      intro: [
        "You're Caroline Whitmore. Your fund just bought forty local newspapers across New England for less than the price of one Manhattan apartment.",
        "The lights on the wall are the readers — the people who find out about the zoning vote, the school budget, and the plant closing from the paper you now own.",
        "Your limited partners want one number: EBITDA. There's a dial between keeping the newsroom and harvesting the masthead.",
        "Nobody will notice the day a paper stops covering the city council. They'll notice years later, when nobody knows what the council did.",
      ],
      introCta: "Open the data room ›",
      capture: "Margins up nine points. The paper still prints. It just doesn't cover anything that happens in town.",
      protect: "You kept the reporters. The LPs asked why you're running a charity.",
      outLabel: "FALLOUT THIS QUARTER",
      fired: "Another fund bought the papers and gutted them anyway. What would have had to change for local news not to be an asset class?",
      ended: "The fund returned 3×. Who is covering the city council now?",
      turns: [
        [2012, "FORTY PAPERS FOR THE PRICE OF ONE APARTMENT", "Keep every newsroom intact for a year", "Cut the newsrooms by a third on day one", "✂"],
        [2014, "THE PRINTING PLANTS ARE REDUNDANT", "Keep printing locally", "Consolidate printing to one plant, three hours away"],
        [2016, "THE BUILDINGS ARE WORTH MORE THAN THE PAPERS", "Keep the newsroom downtown", "Sell the building; reporters work from home", "$"],
        [2018, "A HEDGE FUND OFFERS TO MERGE YOUR PAPERS INTO ITS CHAIN", "Stay independent", "Merge and cut the overlapping staff", "✂"],
        [2020, "THE PANDEMIC · AD REVENUE COLLAPSES", "Take the loss; keep the reporters", "Furlough the newsroom; keep the paywall up", "✂"],
        [2022, "AI CAN WRITE THE HIGH SCHOOL SPORTS", "Keep the stringers", "Automate the local copy", "⚙"],
        [2024, "THE LAST PAPER IN THREE COUNTIES LOSES MONEY", "Give it to a local nonprofit", "Shut it down and sell the name", "✂"],
      ],
    },
  }),

  life({
    id: "me-home-care",
    protagonist: "Hodan Abdi",
    dossierTag: "HOME CARE AGENCY OWNER",
    householdName: "The Abdis",
    location: "Lewiston, ME",
    tagline: "Home care agency owner, 34. Came to Maine at nine. Forty aides, all paid by Medicaid.",
    description:
      "Hodan Abdi arrived in Lewiston in 2001 with her mother and two brothers. She was a home health aide at nineteen and started her own agency at twenty-eight. Her aides are Somali, Congolese, and French-Canadian. Her clients are old, mostly white, and mostly alone.",
    perspective:
      "The state sets the rate. The rate doesn't cover a living wage. Everybody knows that — the legislature, the hospital, the families. So the work gets done by women who can't afford to say no, and the system calls it a labor shortage.",
    closingAddendum:
      "You were dealt the job of caring for people the state pays too little to care for. The margin had to come from somewhere, and it was always someone's hours.",
    seat: {
      title: "The Agency Owner",
      role: "Owner, Home Care Agency",
      color: "#4DA38A",
      scoreLabel: "BILLABLE HOURS",
      dial: ["pay the aides", "cover the rate"],
      dialNote: "Medicaid pays what it pays",
      board: "PAYROLL",
      firedTitle: "SOLD",
      firedBody:
        "You couldn't make payroll. A national home care chain bought your client list for a fraction of what you built. Your aides were re-hired at a dollar less an hour, if they were re-hired.",
      pressure: [
        "Payroll cleared by two hundred dollars this week. Your accountant called it 'a warning.'",
        "The bank froze your line of credit. A national chain's recruiter has been calling your aides.",
      ],
      ranks: [
        ["Owner", "forty aides and a van"],
        ["Growing Agency", "an office on Lisbon Street"],
        ["Regional Agency", "clients in three counties"],
        ["State Leader", "a seat on the governor's task force"],
        ["Acquirer", "you buy the small agencies now"],
        ["Exited", "a check from the national chain"],
      ],
      intro: [
        "You're Hodan Abdi. Forty aides, a hundred and ten clients, one fax machine that still works. You started this agency because you knew you could run it better than the one that paid you $9 an hour.",
        "The lights on the wall are the aides and their families, and the clients who depend on them to get out of bed.",
        "The state pays a fixed rate per hour of care. There's a dial between paying the aides a living wage and covering the rate.",
        "Every dollar you don't pay an aide is a dollar you can use to stay open. Every aide you lose is a client who goes without.",
      ],
      introCta: "Open the schedule ›",
      capture: "You covered payroll. Two aides picked up second jobs. One stopped answering the schedule texts.",
      protect: "The aides got a raise. The bank got nervous.",
      outLabel: "FALLOUT THIS MONTH",
      fired: "A chain took your clients and paid the aides less anyway. What would have had to change for care work to pay?",
      ended: "The agency survived. Who carried it?",
      turns: [
        [2018, "THE STATE RATE IS FLAT FOR THE FIFTH YEAR", "Raise wages anyway, eat the margin", "Hold wages; the rate is the rate"],
        [2019, "AN AIDE ASKS FOR MILEAGE BETWEEN CLIENTS", "Pay for the drive time", "Mileage isn't billable; neither is the drive", "✂"],
        [2020, "THE PANDEMIC · AIDES ARE AFRAID TO GO IN", "Hazard pay and PPE, whatever it costs", "Visits continue; bring your own mask", "✂"],
        [2021, "THE HOSPITAL WANTS YOU TO TAKE DISCHARGES SAME-DAY", "Only what your staff can safely cover", "Say yes to everything; overtime covers it"],
        [2022, "A SOFTWARE VENDOR OFFERS GPS TRACKING FOR AIDES", "Trust your staff", "Clock them by the minute", "⚙"],
        [2023, "A STAFFING APP OFFERS ON-DEMAND AIDES AS CONTRACTORS", "Keep your aides as employees", "Switch to the app, no benefits", "✂"],
        [2024, "A NATIONAL CHAIN OFFERS TO BUY YOUR CLIENT LIST", "Turn it into a worker cooperative", "Sell to the chain"],
      ],
    },
  }),

  life({
    id: "ma-enrollment",
    protagonist: "Kevin Sullivan",
    dossierTag: "VP OF ENROLLMENT",
    householdName: "The Sullivans",
    location: "Boston, MA",
    tagline: "University vice president, 55. First in his family to go to college. Now he decides who gets in.",
    description:
      "Kevin Sullivan grew up in Dorchester, the fourth of six kids. A Jesuit high school and a full scholarship got him to college. He's spent thirty years in admissions and remembers what it felt like to open the envelope.",
    perspective:
      "The college has to balance a budget, and tuition is the budget. Rankings bring applications, applications bring tuition, tuition pays for the dorms. You can think it's all wrong and still be the one who has to hit the class target.",
    closingAddendum:
      "You were dealt the life that got through the door on a scholarship. Then you were handed the key, and a number to hit.",
    seat: {
      title: "The Dean",
      role: "VP of Enrollment",
      color: "#A33B3B",
      scoreLabel: "NET TUITION",
      dial: ["need-blind", "full-pay first"],
      dialNote: "the rankings reward selectivity, not access",
      board: "TRUSTEES",
      firedBody:
        "The trustees hired an enrollment consulting firm that uses an algorithm to price financial aid down to the dollar. The class came in on budget, and whiter and richer than the year before.",
      pressure: [
        "The CFO said the class came in $4 million short. The trustees want 'a plan.'",
        "The president is interviewing enrollment consultants. He says it's 'just to benchmark.'",
      ],
      ranks: [
        ["Dean", "an office in the old library"],
        ["Vice President", "a seat in the cabinet"],
        ["Senior VP", "the trustees know your name"],
        ["Provost", "the academic budget"],
        ["President", "a house on campus"],
        ["Consultant", "forty colleges pay for your model"],
      ],
      intro: [
        "You're Kevin Sullivan. You run admissions and financial aid at a private university in Boston. Tuition is $68,000 a year.",
        "The lights on the wall are families: the applicants, the parents co-signing loans, the kids who'll carry the debt into their thirties.",
        "The trustees watch net tuition revenue and the rankings. There's a dial between admitting need-blind and full-pay first.",
        "You were once the kid with the thin envelope and the big dream. That kid is in the pile this year too.",
      ],
      introCta: "Open the reading room ›",
      capture: "The class came in on budget. The ranking went up two spots. Fewer kids like you got in.",
      protect: "You admitted the class you believed in. The CFO called before the deposits were counted.",
      outLabel: "FALLOUT THIS CLASS",
      fired: "An algorithm filled the class anyway. What would have had to change for college not to be priced like an airline seat?",
      ended: "The rankings rose every year. Where did the kids like you go?",
      turns: [
        [2003, "THE RANKINGS REWARD A LOW ADMIT RATE", "Keep recruiting where the need is", "Market everywhere, reject more, climb the list", "⚡"],
        [2006, "MERIT AID ATTRACTS WEALTHY STUDENTS", "Keep the money in need-based aid", "Shift aid to 'merit' for full-pay families"],
        [2009, "THE ENDOWMENT LOST 25% · FILL THE CLASS", "Hold need-blind admissions", "Go need-aware — quietly"],
        [2012, "A NEW DORM WITH A LAZY RIVER", "Put the money into aid", "Build the amenities; the tours need them"],
        [2016, "LEGACY APPLICANTS FILL 14% OF THE CLASS", "End legacy preference", "Keep it — the donors are watching", "$"],
        [2019, "A CONSULTANT OFFERS 'AID OPTIMIZATION' SOFTWARE", "Keep aid decisions human", "Price each student to their max willingness to pay", "⚙"],
        [2023, "THE SUPREME COURT ENDS AFFIRMATIVE ACTION", "Recruit hard in poor neighborhoods", "Let the numbers fall where they fall"],
      ],
    },
  }),

  life({
    id: "nh-recovery",
    protagonist: "Tim Boucher",
    dossierTag: "RECOVERY CENTER DIRECTOR",
    householdName: "The Bouchers",
    location: "Manchester, NH",
    tagline: "Recovery center director, 38. Eight years sober. He and his husband Marco just bought a condo.",
    description:
      "Tim Boucher overdosed twice in 2014. A church-run recovery house in Manchester took him in when nobody else would. Now he runs a treatment center of his own. Marco teaches third grade. They have a dog named Deputy.",
    perspective:
      "Recovery works when somebody decides you're worth the trouble. Insurance decides that by the day, and the days run out. Everybody in this business knows somebody who died on day thirty-one.",
    closingAddendum:
      "You were dealt the life somebody saved. Then you were handed a business where saving people depended on how they were billed.",
    seat: {
      title: "The Director",
      role: "Director, Recovery Center",
      color: "#5B8FD9",
      scoreLabel: "CENSUS",
      dial: ["treat the patient", "bill the insurer"],
      dialNote: "a full bed pays; a discharged patient doesn't",
      board: "INVESTORS",
      firedBody:
        "The investors replaced you with a director from a Florida treatment chain. Within a year the center was paying 'recruiters' for referrals and testing patients' urine three times a week — because the tests bill well.",
      pressure: [
        "The investors want to know why census is down four beds.",
        "The operating partner flew in from Nashville. He wants to 'talk about the model.'",
      ],
      ranks: [
        ["Director", "a staff of twelve"],
        ["Executive Director", "a second location"],
        ["Regional VP", "five centers in New England"],
        ["Chief Clinical Officer", "your story on the website"],
        ["Industry Voice", "a keynote at the addiction summit"],
        ["Equity Holder", "a stake in the chain"],
      ],
      intro: [
        "You're Tim Boucher. A private equity group just bought the recovery center you run in Manchester. They kept you on because you're the story that sells it.",
        "The lights on the wall are the people who come through the door: the construction worker, the nurse, the kid from Nashua. Their families are waiting outside.",
        "The investors watch census — how many beds are full, how many days are billed. There's a dial between treating the patient and billing the insurer.",
        "You know exactly which patients insurance will stop paying for on day twenty-eight. So do they.",
      ],
      introCta: "Unlock the front door ›",
      capture: "Census up. Billing up. A patient discharged on day twenty-nine was back in the ER by the weekend.",
      protect: "The patient stayed until he was ready. The claim was denied. The investors noticed.",
      outLabel: "FALLOUT THIS MONTH",
      fired: "A chain ran it the way the billing wanted. What would have had to change for recovery not to be a revenue cycle?",
      ended: "The beds stayed full. How many people did the center actually keep alive?",
      turns: [
        [2017, "THE INVESTORS CLOSE ON THE CENTER", "Keep the old staff and the old rules", "Adopt the chain's billing playbook"],
        [2018, "URINE TESTS BILL AT $1,200 EACH", "Test when it's clinically needed", "Test everyone three times a week", "⚗"],
        [2019, "A 'RECRUITER' OFFERS PATIENTS FOR A FEE", "Refuse the referral money", "Pay the finder's fee; the beds need filling"],
        [2020, "THE PANDEMIC · OVERDOSES SPIKE", "Open beds for the uninsured", "Only admit patients with commercial insurance", "✂"],
        [2021, "INSURANCE CUTS OFF AT DAY 28", "Keep them on your own dime", "Discharge on day 28, as billed", "✂"],
        [2022, "MEDICATION TREATMENT WORKS · IT DOESN'T BILL AS WELL", "Offer medication for everyone who needs it", "Stick with the residential model"],
        [2024, "THE CHAIN WANTS A SECOND CENTER IN A STRIP MALL", "Only if it's staffed right", "Open it with half the clinicians"],
      ],
    },
  }),

  life({
    id: "nj-motels",
    protagonist: "Rakesh Patel",
    dossierTag: "MOTEL OWNER",
    householdName: "The Patels",
    location: "Edison, NJ",
    tagline: "Motel owner, 56. Three motels on Route 1. His daughter is in her second year of medical school.",
    description:
      "Rakesh Patel came from Gujarat in 1992 and worked the front desk at his uncle's motel in Delaware. He bought his first motel in 1999 with money from four relatives. The family lives above the office. His wife Meena does the books at the kitchen table.",
    perspective:
      "Everybody thinks motel owners are rich. We are rich in rooms, and every room is a debt. The county pays on time, the tourists don't come anymore, and you do not choose who needs a room.",
    closingAddendum:
      "You were dealt a family business built one room at a time. The county paid for the rooms. Nobody paid for what happened in them.",
    seat: {
      title: "The Motel Owner",
      role: "Owner, Route 1 Motels",
      color: "#D9A74D",
      scoreLabel: "OCCUPANCY",
      dial: ["a home for the night", "a bed for the county rate"],
      dialNote: "the county pays per room, not per repair",
      board: "THE BANK",
      firedTitle: "FORECLOSED",
      firedBody:
        "The bank foreclosed on the second motel. A real estate trust bought it, kept the county contract, and cut the cleaning staff to one. The rooms stayed full.",
      pressure: [
        "The bank's commercial officer asked about 'occupancy trends' on the phone.",
        "The note on the second motel is under review. The bank sent an appraiser without asking.",
      ],
      ranks: [
        ["Owner", "one motel and a family"],
        ["Hotelier", "three properties on Route 1"],
        ["Franchisee", "a national flag out front"],
        ["Developer", "a new build near the turnpike"],
        ["Association Chair", "the county returns your calls"],
        ["Portfolio", "a dozen hotels and a management company"],
      ],
      intro: [
        "You're Rakesh Patel. Your three motels on Route 1 used to host truckers and families driving to the shore. Now the county pays you to house people who have nowhere else to go.",
        "The lights on the wall are the people in your rooms and the neighborhoods around them — families between apartments, men out of rehab, kids who catch the school bus in your parking lot.",
        "The bank watches occupancy. There's a dial between making it a home for the night and a bed at the county rate.",
        "Nobody planned for motels to become the housing system. They just did, because nothing else was built.",
      ],
      introCta: "Turn on the vacancy sign ›",
      capture: "Every room full at the county rate. The heat went out in Room 14 and stayed out until Thursday.",
      protect: "You fixed the rooms and kept the rate fair. The bank asked why margins fell.",
      outLabel: "FALLOUT THIS MONTH",
      fired: "A trust took the motel and ran it anyway. What would have had to change for motels not to be the housing plan?",
      ended: "The motels made it. How many families left your rooms for somewhere better?",
      turns: [
        [2009, "THE RECESSION · TOURISTS STOP COMING", "Cut your own salary, keep the staff", "Cut housekeeping to every third day", "✂"],
        [2012, "THE COUNTY OFFERS A CONTRACT FOR EMERGENCY HOUSING", "Take a few rooms, keep the rest for travelers", "Give the county every room at the county rate"],
        [2015, "A FAMILY OF FIVE IN ONE ROOM FOR A YEAR", "Help them find an apartment", "Keep them — steady money"],
        [2018, "THE INSPECTOR FINDS MOLD", "Close the rooms and fix them", "Paint over it, reopen tomorrow", "✂"],
        [2020, "THE PANDEMIC · THE STATE NEEDS ISOLATION ROOMS", "Take them at cost", "Charge the emergency rate", "$"],
        [2022, "A RESIDENT FALLS BEHIND ON THE PORTION HE PAYS", "Work out a payment plan", "Change the lock on Friday", "✂"],
        [2024, "A DEVELOPER OFFERS TO BUY FOR APARTMENTS", "Sell for affordable housing, at less", "Hold for the county rate"],
      ],
    },
  }),

  life({
    id: "pa-fracking",
    protagonist: "Joe Novak",
    dossierTag: "TOWNSHIP SUPERVISOR",
    householdName: "The Novaks",
    location: "Washington County, PA",
    tagline: "Retired steelworker, 61. Township supervisor. Forty acres of his grandfather's land sits on the Marcellus Shale.",
    description:
      "Joe Novak worked thirty years at the mill in Monessen until it closed. His wife Donna works at the hospital. They go to St. Stanislaus every Sunday, and their son drives a water truck for the gas company.",
    perspective:
      "After the mills, nothing came back. Then the gas came, and for the first time in thirty years people had money. Don't tell a man who watched his town die that the thing paying his mortgage is the problem.",
    closingAddendum:
      "You were dealt a town that had already lost its first fortune. The second one came out of the ground, and so did the water.",
    seat: {
      title: "The Township Supervisor",
      role: "Township Supervisor",
      color: "#6F7D8C",
      scoreLabel: "GAS REVENUE",
      dial: ["the neighbors", "the drilling"],
      dialNote: "the impact fee pays for the new fire truck",
      board: "SUPERVISORS",
      firedTitle: "VOTED OUT",
      firedBody:
        "The gas company's lawyers and a slate of candidates they funded unseated you by 140 votes. The new board approved every permit on the table in one night.",
      pressure: [
        "The other two supervisors took the gas company's lobbyist to dinner without you.",
        "Signs are going up in yards: 'Novak Is Anti-Jobs.' Nobody will say who printed them.",
      ],
      ranks: [
        ["Supervisor", "a seat and a gavel"],
        ["Chairman", "the ribbon cuttings"],
        ["County Commissioner", "the whole county's leases"],
        ["State Rep", "a vote on the impact fee"],
        ["Industry Liaison", "a consulting fee from the driller"],
        ["Landowner Coalition", "you speak for the royalty owners"],
      ],
      intro: [
        "You're Joe Novak. You're one of three supervisors in a township of 4,000 people sitting on top of the Marcellus Shale.",
        "The lights on the wall are the township: farmers who leased their land, neighbors who didn't, kids at the elementary school a thousand feet from the new well pad.",
        "Every permit comes before your board. There's a dial between protecting the neighbors and welcoming the drilling.",
        "The royalty checks are real. So is the well water that started coming out of the tap the color of tea.",
      ],
      introCta: "Gavel in ›",
      capture: "The permit passed 3–0. The township got a new fire truck. A family on Brush Run Road started buying bottled water.",
      protect: "You voted no. The permit passed 2–1, and the other two supervisors stopped saying hello.",
      outLabel: "FALLOUT THIS MEETING",
      fired: "A new board approved it all anyway. What would have had to change for the township not to need the gas?",
      ended: "The township got its revenue. What did it cost the people who didn't sign a lease?",
      turns: [
        [2008, "THE LANDMEN ARRIVE · $2,500 AN ACRE", "Warn people to read the lease", "Sign your own land first; lead by example"],
        [2010, "A WELL PAD NEXT TO THE ELEMENTARY SCHOOL", "Require a mile setback", "Approve it; the setback law is the state's problem"],
        [2012, "THE STATE PASSES AN IMPACT FEE · NO LOCAL ZONING", "Join the lawsuit to keep local control", "Take the fee money and stay quiet"],
        [2014, "A FAMILY'S WATER TURNS BROWN", "Demand the driller test it", "Accept the company's report", "⚗"],
        [2016, "A COMPRESSOR STATION · IT RUNS DAY AND NIGHT", "Require noise and air monitoring", "Approve it as written"],
        [2019, "A CRACKER PLANT WANTS TO BUILD UPRIVER", "Ask what it puts in the air", "Welcome the jobs", "⚗"],
        [2022, "CHILDHOOD CANCERS CLUSTER IN THE COUNTY", "Call for a state study, loudly", "Say the data isn't conclusive"],
      ],
    },
  }),

  life({
    id: "ri-creator",
    protagonist: "Carmen Rosario",
    dossierTag: "CONTENT CREATOR",
    householdName: "The Rosarios",
    location: "Providence, RI",
    tagline: "Content creator, 26. 400,000 followers. Lives with her mother and grandmother on Broad Street.",
    description:
      "Carmen Rosario started posting makeup tutorials in a CVS parking lot in 2017. Now brands pay her more in a month than her mother made in a year cleaning offices downtown. Her grandmother still doesn't understand what she does, and neither, some days, does Carmen.",
    perspective:
      "Nobody gave us anything. The algorithm doesn't care where you're from, it cares if people watch. That's the first fair game anybody in my family ever got to play.",
    closingAddendum:
      "You were dealt a game that was finally fair to you. It paid for attention, and you got very good at getting it.",
    seat: {
      title: "The Creator",
      role: "Content Creator",
      mode: "attn",
      color: "#E05C9B",
      scoreLabel: "VIEWS",
      dial: ["say what's true", "say what spreads"],
      dialNote: "the algorithm pays for outrage and envy",
      board: "SPONSORS",
      firedTitle: "FORGOTTEN",
      firedBody:
        "The algorithm moved on. A creator from Miami with your exact look and none of your hesitation took your sponsors in a month. Her followers bought everything she sold them.",
      pressure: [
        "Your reach is down 30%. Your manager says 'the algorithm wants more of you.'",
        "Two sponsors didn't renew. Your manager sent a list of trends you're 'missing.'",
      ],
      ranks: [
        ["Creator", "a ring light and a dream"],
        ["Influencer", "free product every week"],
        ["Brand Partner", "your own discount code"],
        ["Verified", "a blue check and a manager"],
        ["Founder", "your own product line"],
        ["Celebrity", "a Super Bowl ad"],
      ],
      intro: [
        "You're Carmen Rosario. You post three times a day. Your mother pays her rent with what you make now.",
        "The lights on the wall are your followers: girls in Providence and Paterson and Lawrence who want your life, and their moms who worry about them.",
        "Your sponsors watch one number: views. There's a dial between saying what's true and saying what spreads.",
        "The fastest-growing accounts sell something — a supplement, a feeling, an enemy. Everybody knows it. Everybody does it anyway.",
      ],
      introCta: "Hit record ›",
      actLabel: "POST",
      capture: "It went viral. Two million views by morning. The comments are a war.",
      protect: "Honest and kind. Eleven thousand views. Your manager sent a thumbs-down emoji.",
      outLabel: "FALLOUT THIS POST",
      fired: "Someone else sold it to them anyway. What would have had to change for attention not to be the only currency?",
      ended: "You made it out. What did the girls who watched you learn to want?",
      turns: [
        [2018, "A TEETH-WHITENING BRAND WANTS A SPONSORED POST", "Only products you'd use", "Take every deal that pays", "$"],
        [2019, "BEFORE-AND-AFTER VIDEOS GET 5× THE VIEWS", "Post real skin, no filter", "Filter everything, sell the fantasy", "✦"],
        [2020, "A 'DETOX TEA' OFFERS $20,000", "Pass — it's a laxative", "Post it with #ad in small print", "$"],
        [2021, "A DRAMA VIDEO ABOUT ANOTHER CREATOR BLOWS UP", "Delete it and apologize", "Make a part two", "⚡"],
        [2022, "A CRYPTO APP WANTS YOU TO PROMOTE A COIN", "Decline", "Tell your followers to buy in", "$"],
        [2023, "POLITICAL RAGE CONTENT IS OUTPERFORMING MAKEUP", "Stay in your lane", "Pick a side and go loud", "⚡"],
        [2024, "A SPORTS BETTING APP OFFERS A SEVEN-FIGURE DEAL", "Walk away", "Sign it; your followers are old enough", "$"],
      ],
    },
  }),

  life({
    id: "vt-hospital",
    protagonist: "Hannah Adler",
    dossierTag: "HOSPITAL CEO",
    householdName: "The Adlers",
    location: "St. Johnsbury, VT",
    tagline: "Rural hospital CEO, 49. Family doctor for fifteen years before that. Forty miles from the next ER.",
    description:
      "Hannah Adler came to the Northeast Kingdom for a two-year rural medicine program and never left. Her husband builds furniture; their daughter plays hockey at the high school. She delivered half the kids on her daughter's team.",
    perspective:
      "A rural hospital is the biggest employer, the only ER, and the place people are born and die. It also loses money on almost everything it does. Somebody has to decide what to cut, and whoever decides is the bad guy.",
    closingAddendum:
      "You were dealt the hospital everyone needed and nobody paid for. Every service you kept was a decision about who would drive forty miles.",
    seat: {
      title: "The Hospital CEO",
      role: "CEO, Community Hospital",
      color: "#4D9FD9",
      scoreLabel: "OPERATING MARGIN",
      dial: ["keep every service", "keep the doors open"],
      dialNote: "labor and delivery loses money on every birth",
      board: "SYSTEM",
      firedBody:
        "The regional health system that absorbed the hospital sent its own CEO from Burlington. She closed the birthing center and the psych unit in her first ninety days, and the margin came back.",
      pressure: [
        "The health system's CFO wants your margin to break even by spring.",
        "The system's board is 'reviewing the service lines' at your hospital. They didn't invite you.",
      ],
      ranks: [
        ["CEO", "a hospital with forty beds"],
        ["System VP", "three rural hospitals"],
        ["Regional President", "a seat at the system board"],
        ["Health Policy Voice", "the governor's commission"],
        ["System CEO", "a medical center in Burlington"],
        ["Board Member", "a seat on the insurer's board"],
      ],
      intro: [
        "You're Hannah Adler. You run the only hospital in a county of 30,000 people. Last year it lost $4 million.",
        "The lights on the wall are the county: loggers, dairy farmers, retirees, the kid who wrecked his snowmobile and needs the ER in the next twenty minutes.",
        "A regional health system took you over to save you. They watch the operating margin. There's a dial between keeping every service and keeping the doors open.",
        "Every service you cut is a longer drive for somebody. Sometimes the drive is the difference.",
      ],
      introCta: "Walk the halls ›",
      capture: "The margin improved. A woman in labor drove an hour and ten minutes to Burlington through a snowstorm.",
      protect: "You kept the unit open. The system sent a 'sustainability consultant.'",
      outLabel: "FALLOUT THIS QUARTER",
      fired: "The system cut it anyway. What would have had to change for a rural hospital to break even?",
      ended: "The hospital's still open. What does it still do?",
      turns: [
        [2014, "THE HOSPITAL CAN'T MAKE PAYROLL ALONE", "Stay independent another year", "Join the regional health system"],
        [2016, "THE BIRTHING CENTER DELIVERS 180 BABIES A YEAR · IT LOSES MONEY", "Keep it open", "Close it; send them to Burlington", "✂"],
        [2018, "PATIENTS OWE THE HOSPITAL $3 MILLION", "Write off the poor patients' debt", "Send it all to collections"],
        [2020, "THE PANDEMIC · ELECTIVE SURGERIES STOP", "Keep every nurse on payroll", "Lay off the non-essential staff", "✂"],
        [2021, "TRAVEL NURSES COST THREE TIMES STAFF NURSES", "Raise staff pay instead", "Staff the floor with travelers", "$"],
        [2023, "THE PSYCH UNIT IS THE LAST ONE IN THE REGION", "Keep the beds", "Convert them to profitable orthopedics", "✂"],
        [2025, "THE SYSTEM WANTS TO CLOSE INPATIENT BEDS ENTIRELY", "Fight for the beds", "Become an ER and a clinic", "✂"],
      ],
    },
  }),
];
