import { life } from "./build";

export const SOUTH = [
  life({
    id: "ar-supplier",
    protagonist: "Jenna Pruitt",
    dossierTag: "VENDOR ACCOUNT MANAGER",
    householdName: "The Pruitts",
    location: "Bentonville, AR",
    tagline: "Vendor account manager, 31. Moved from Fort Smith for the job. First in her family with a salary.",
    description:
      "Jenna Pruitt works for a household-goods company whose single biggest customer is the big-box retailer headquartered down the road. Her husband Cody is a youth pastor. They just closed on a house with a two-car garage and a nursery that's still empty.",
    perspective:
      "Everybody in Bentonville works for the store or sells to it. It's a good life. The store says lower prices help families like mine, and they do. They also come from somewhere.",
    closingAddendum:
      "You were dealt a good job in the town the low price built. The price came out of a factory you never saw.",
    seat: {
      title: "The Vendor Rep",
      role: "Vendor Account Manager",
      color: "#3F7FBF",
      scoreLabel: "SHELF SPACE",
      dial: ["protect the factory", "hit the retailer's price"],
      dialNote: "the retailer wants a lower price every single year",
      board: "HEAD OFFICE",
      firedBody:
        "Head office replaced you with a rep who agreed to every price cut the retailer asked for. The Ohio plant closed within the year; the products are made in Vietnam now, and they're cheaper.",
      pressure: [
        "Head office wants to know why you haven't closed the new price agreement.",
        "Your VP flew in from Ohio. She said 'the account is at risk,' and she meant you.",
      ],
      ranks: [
        ["Account Manager", "a badge to the retailer's campus"],
        ["Senior Manager", "a team of four"],
        ["Director", "the whole category"],
        ["VP of Sales", "a lake house on Beaver Lake"],
        ["Supplier of the Year", "an award in the retailer's lobby"],
        ["Retailer Hire", "they hired you across the table"],
      ],
      intro: [
        "You're Jenna Pruitt. Your company makes plastic storage bins in a plant in Ohio. The retailer down the road sells a third of everything you make.",
        "The lights on the wall are the people on both ends: the families who buy the bins for $7.97, and the workers in Ohio who make them for less every year.",
        "The retailer asks for a lower price every year. There's a dial between protecting the factory and hitting the retailer's number.",
        "If you say no, the buyer has four other vendors waiting in the lobby. You'll never meet the people who pay for your yes.",
      ],
      introCta: "Badge into the campus ›",
      capture: "The retailer took the price. The Ohio plant went to four ten-hour shifts, no overtime.",
      protect: "You held the price. The buyer moved half your shelf space to a competitor.",
      outLabel: "FALLOUT THIS QUARTER",
      fired: "Someone else agreed to the price. What would have had to change for the lowest price not to be the only one that mattered?",
      ended: "The bins are $6.97 now. Where are they made?",
      turns: [
        [2016, "THE RETAILER WANTS 5% OFF · EVERY YEAR, FOREVER", "Tell them it can't be done", "Promise it, figure it out later"],
        [2017, "THE PLANT PAYS FOR HEALTH INSURANCE", "Protect it in the budget", "Suggest the plant 'rethink benefits'", "✂"],
        [2018, "TARIFFS RAISE THE COST OF RESIN", "Ask the retailer to share the hit", "Absorb it at the plant; keep the price", "✂"],
        [2019, "A FACTORY IN VIETNAM QUOTES 30% LESS", "Keep production in Ohio", "Move half the line overseas", "✈"],
        [2020, "THE PANDEMIC · STORAGE BINS SELL OUT", "Hire at the plant, raise wages", "Run mandatory overtime, no raise", "$"],
        [2022, "THE RETAILER WANTS YOU TO PAY FOR ITS SHIPPING", "Push back hard", "Eat it; charge the plant"],
        [2024, "THE RETAILER LAUNCHES ITS OWN STORE BRAND", "Refuse to make it for them", "Make the knockoff of your own product", "$"],
      ],
    },
  }),

  life({
    id: "de-collections",
    protagonist: "Tara Mullin",
    dossierTag: "COLLECTIONS TEAM LEAD",
    householdName: "The Mullins",
    location: "Newark, DE",
    tagline: "Collections team lead, 36. Single mom. Owes $11,000 on her own card.",
    description:
      "Tara Mullin works for one of the credit card banks that moved to Delaware because the state lets them charge any interest rate they want. She has a son, Aiden, who's eleven. She got promoted because she's good on the phone — good at making people feel heard, and then making them pay.",
    perspective:
      "I know what it's like to be on the other end of the call. That's why I'm good at this. Everybody's one bad month away. The trick is to be the one making the calls, not getting them.",
    closingAddendum:
      "You were dealt a job calling people exactly like you. It paid your card down — one of theirs at a time.",
    seat: {
      title: "The Collector",
      role: "Collections Team Lead",
      color: "#BF5F3F",
      scoreLabel: "RECOVERY RATE",
      dial: ["work it out", "collect in full"],
      dialNote: "the bank pays bonuses on dollars recovered",
      board: "FLOOR MANAGER",
      firedBody:
        "Your team missed quota two months running. They sold your whole book of accounts to a debt buyer in Georgia that sues everybody. Your people got reassigned to fraud prevention.",
      pressure: [
        "The floor manager posted your team's recovery rate on the board. It's in red.",
        "HR scheduled a 'performance conversation.' Your team's bonuses are frozen.",
      ],
      ranks: [
        ["Team Lead", "a headset and a quota"],
        ["Supervisor", "three teams"],
        ["Floor Manager", "an office with a window"],
        ["Director of Recovery", "a bonus tied to charge-offs"],
        ["VP of Collections", "the debt sales go through you"],
        ["Debt Buyer", "your own portfolio of paper"],
      ],
      intro: [
        "You're Tara Mullin. Your team calls people who are ninety days behind on their credit cards. You're graded on how much you get back.",
        "The lights on the wall are the cardholders: nurses, truckers, laid-off retail managers, and people whose medical bills went on a card.",
        "The floor manager watches one number: recovery rate. There's a dial between working out a plan and collecting in full.",
        "Every dollar you don't collect, the bank sells to a debt buyer for four cents. They'll get it one way or another.",
      ],
      introCta: "Put on the headset ›",
      capture: "He paid the whole balance on a second card. He'll be back on your list in four months.",
      protect: "You set up a hardship plan. The bank's system flagged it as 'below target.'",
      outLabel: "FALLOUT THIS SHIFT",
      fired: "A debt buyer collected anyway. What would have had to change for being broke not to be a business opportunity?",
      ended: "Recovery rate up every year. How many of those people were you?",
      turns: [
        [2008, "THE RECESSION · DELINQUENCIES DOUBLE", "Offer hardship plans", "Push for full payment, call every day"],
        [2010, "A NEW LAW LIMITS SOME FEES", "Follow the spirit of it", "Find the fees it didn't cover", "$"],
        [2013, "A SCRIPT THAT MENTIONS 'LEGAL ACTION'", "Stay honest on the phone", "Use the script; it works"],
        [2016, "A CUSTOMER'S DEBT IS FROM A HOSPITAL STAY", "Flag it for forgiveness", "Treat it like any other balance", "✂"],
        [2019, "AUTO-DIALERS CAN CALL 300 TIMES A DAY", "Call during business hours only", "Call at dinner; they pick up", "☎"],
        [2021, "PANDEMIC FORBEARANCE ENDS", "Extend it quietly", "Collect the back balance at once"],
        [2023, "THE BANK WANTS TO SELL OLD ACCOUNTS TO A DEBT BUYER", "Push to settle them first", "Sell them — they'll sue"],
      ],
    },
  }),

  life({
    id: "fl-insurance",
    protagonist: "Marisol Castillo",
    dossierTag: "CLAIMS MANAGER",
    householdName: "The Castillos",
    location: "Hialeah, FL",
    tagline: "Claims manager, 45. Cuban-American. Her parents' house lost its roof in Hurricane Andrew.",
    description:
      "Marisol Castillo was thirteen in 1992 when Andrew tore the roof off her parents' house. It took the insurer eighteen months to pay. She went into insurance to be the one who picks up the phone. Her husband Rafael drives for a produce distributor. Her mother lives with them now.",
    perspective:
      "Florida's in denial about what it costs to live here. The storms get worse, the insurers leave, and whoever's left has to decide who gets paid. Nobody else wants that job, and somebody has to do it.",
    closingAddendum:
      "You were dealt a house that waited eighteen months for a check. You became the one who decided how long everyone else waited.",
    seat: {
      title: "The Claims Manager",
      role: "Claims Manager, Home Insurer",
      color: "#3FBFBF",
      scoreLabel: "LOSS RATIO",
      dial: ["pay the claim", "protect the reserves"],
      dialNote: "every claim paid is a hole in the reserves",
      board: "HOME OFFICE",
      firedBody:
        "The insurer went insolvent anyway, and the state's insurer of last resort took over. It denied more claims than you ever did, and paid slower.",
      pressure: [
        "Home office flagged your region's payout ratio as 'out of tolerance.'",
        "The reinsurers raised rates 40%. Your VP says it's your region's fault.",
      ],
      ranks: [
        ["Claims Manager", "a team of adjusters"],
        ["Regional Director", "all of South Florida"],
        ["VP of Claims", "the state's biggest book"],
        ["Chief Claims Officer", "the rating agencies know your name"],
        ["Industry Lobbyist", "the legislature asks your advice"],
        ["Reinsurer", "you bet on the storms now"],
      ],
      intro: [
        "You're Marisol Castillo. You run claims for a Florida home insurer that writes policies nobody else will.",
        "The lights on the wall are homeowners in Hialeah and Homestead and Fort Myers — people who paid their premiums for twenty years and now need a roof.",
        "Home office watches the loss ratio. There's a dial between paying the claim and protecting the reserves.",
        "You remember the blue tarp on your parents' house. So does everybody on the wall.",
      ],
      introCta: "Open the claims queue ›",
      capture: "Reserves protected. The claim was 'under review' for ten months. The family moved in with their daughter.",
      protect: "You paid it fast and fair. Home office asked why your region's numbers look like that.",
      outLabel: "FALLOUT THIS STORM",
      fired: "Someone else denied it anyway. What would have had to change for a hurricane not to be a coin flip on your policy?",
      ended: "The company survived the storms. Did the people who paid their premiums?",
      turns: [
        [2005, "HURRICANE WILMA · 100,000 CLAIMS", "Send adjusters to every house", "Deny the claims that 'look like flood'", "✂"],
        [2011, "A 'ROOF AGE' RULE CUTS COVERAGE ON OLD ROOFS", "Grandfather in long-time customers", "Apply it to everyone at renewal"],
        [2014, "A SOFTWARE TOOL LOWBALLS ESTIMATES", "Use your adjusters' judgment", "Use the software's numbers", "⚙"],
        [2017, "HURRICANE IRMA · THE COMPANY'S RESERVES ARE THIN", "Pay the claims, ask for a rate hike", "Slow-walk every claim over $50,000"],
        [2019, "LAWSUITS AGAINST INSURERS SKYROCKET", "Settle the fair ones", "Fight every one in court", "§"],
        [2022, "HURRICANE IAN · THE WORST YEAR IN HISTORY", "Pay first, audit later", "Rewrite adjusters' reports downward", "✂"],
        [2024, "THE STATE LETS INSURERS DROP HIGH-RISK HOMES", "Keep your longtime customers", "Drop them all at renewal", "✂"],
      ],
    },
  }),

  life({
    id: "ky-pharmacy",
    protagonist: "Gary Caudill",
    dossierTag: "PHARMACIST",
    householdName: "The Caudills",
    location: "Hazard, KY",
    tagline: "Independent pharmacist, 58. Third-generation Perry County. Owns the drugstore on Main Street.",
    description:
      "Gary Caudill's father ran the pharmacy before him, and his grandfather sold patent medicine from the same counter. Gary coaches Little League and sings in the choir at First Baptist. He knows most of his customers' grandparents by name.",
    perspective:
      "People here work hard jobs that break their bodies. When the doctor writes a prescription, it's not the pharmacist's place to second-guess the doctor. That's what we were told, and that's what the drug companies paid good money to make sure we believed.",
    closingAddendum:
      "You were dealt the counter every family in town trusted. The pills came through it by the truckload, and so did the money.",
    seat: {
      title: "The Pharmacist",
      role: "Owner, Main Street Pharmacy",
      color: "#9FBF3F",
      scoreLabel: "SCRIPTS FILLED",
      dial: ["question the script", "fill what's written"],
      dialNote: "the distributor's rep says the pills are safe",
      board: "DISTRIBUTOR",
      firedTitle: "CLOSED",
      firedBody:
        "You couldn't compete. A chain pharmacy opened by the highway, filled everything you wouldn't, and took your customers. Your father's store is a vape shop now.",
      pressure: [
        "The distributor's rep says your volume is too low for your current pricing.",
        "The chain opened a store by the highway. Half your regulars haven't been back.",
      ],
      ranks: [
        ["Pharmacist", "your father's counter"],
        ["Owner", "a second store in Whitesburg"],
        ["Regional Chain", "five stores in the hills"],
        ["Top Dispenser", "the distributor sends a steak dinner"],
        ["Pharmacy Board", "a seat in Frankfort"],
        ["Distributor Partner", "equity in the supply chain"],
      ],
      intro: [
        "You're Gary Caudill. A new painkiller came out a couple years back that the company says is less addictive than the old ones. Every doctor in the county is prescribing it.",
        "The lights on the wall are Hazard: miners with bad backs, their wives, their teenagers, the preacher and the county judge.",
        "The distributor ships as much as you order. There's a dial between questioning the script and filling what's written.",
        "Nobody told you what was happening. Everybody could see it anyway.",
      ],
      introCta: "Unlock the pharmacy ›",
      actLabel: "FILL",
      capture: "You filled it. Your order went up again. A boy from your son's graduating class was found in his truck.",
      protect: "You called the doctor and refused the fill. The customer drove to the pill mill in Corbin.",
      outLabel: "FALLOUT THIS MONTH",
      fired: "Someone else filled them anyway. What would have had to change for the pills not to reach the county?",
      ended: "Your store survived. How many of your customers did?",
      turns: [
        [1998, "A NEW PAINKILLER · 'LESS THAN 1% RISK OF ADDICTION'", "Wait and see", "Stock up — the doctors are prescribing it", "℞"],
        [2002, "THE SAME DOCTOR WRITES 60 SCRIPTS A DAY", "Call the board of pharmacy", "Fill them; he's a licensed doctor", "℞"],
        [2006, "CUSTOMERS FROM THREE STATES AWAY", "Refuse out-of-state scripts", "Fill them; it's legal", "℞"],
        [2009, "THE DISTRIBUTOR OFFERS A VOLUME DISCOUNT", "Keep your order steady", "Order more; the discount is steep", "$"],
        [2012, "A LOCAL KID OVERDOSES · HIS SCRIPT WAS FROM YOUR COUNTER", "Speak at the funeral about what happened", "Say nothing; you followed the law"],
        [2016, "THE PILLS ARE HARDER TO GET · HEROIN MOVES IN", "Stock naloxone, give it free", "Charge full price for naloxone", "$"],
        [2021, "THE SETTLEMENT MONEY ARRIVES", "Push for treatment centers", "Let the county spend it on roads"],
      ],
    },
  }),

  life({
    id: "md-contractor",
    protagonist: "Marcus Green",
    dossierTag: "PROGRAM MANAGER",
    householdName: "The Greens",
    location: "Bowie, MD",
    tagline: "Defense program manager, 46. Army veteran. Two daughters, one at Howard, one headed there.",
    description:
      "Marcus Green did twenty years in the Army, two tours in Iraq, and retired as a lieutenant colonel. Now he runs a $400 million program for a defense contractor in Maryland. His wife Denise is a deputy principal. They're the first generation of their families to own a house outright.",
    perspective:
      "The military gave me everything — discipline, a career, a way up. The contractors are how the work gets done now. If the Pentagon wants to pay for it, somebody's going to deliver it. It might as well be somebody who served.",
    closingAddendum:
      "You were dealt the ladder the military offered. It led to a contract with no ceiling — paid for by everybody who never got a ladder.",
    seat: {
      title: "The Program Manager",
      role: "Program Manager, Defense Contractor",
      color: "#5F7F3F",
      scoreLabel: "CONTRACT VALUE",
      dial: ["deliver what works", "grow the program"],
      dialNote: "cost overruns are billed to the government",
      board: "EXECUTIVE VP",
      firedBody:
        "The company moved you to a smaller program and put a former Pentagon official in charge of yours. He grew it to $900 million by the next budget cycle.",
      pressure: [
        "The executive VP asked why your program didn't ask for a budget increase this year.",
        "A former deputy assistant secretary just joined the company. He's been asking about your program.",
      ],
      ranks: [
        ["Program Manager", "a $400 million program"],
        ["Senior PM", "a billion-dollar portfolio"],
        ["VP", "the Pentagon's cell number"],
        ["Senior VP", "a jet to the Paris Air Show"],
        ["Board Seat", "a seat on the contractor's board"],
        ["Revolving Door", "the Pentagon job, then back"],
      ],
      intro: [
        "You're Marcus Green. You manage a program building communications systems for the Army. It's two years behind and 40% over budget, like almost every program.",
        "The lights on the wall are taxpayers: the families whose schools, clinics, and roads compete for the same dollars.",
        "Your executive VP watches contract value. There's a dial between delivering what works and growing the program.",
        "The Pentagon doesn't audit well. Nobody's ever been fired for a cost overrun. People have been fired for shrinking a program.",
      ],
      introCta: "Badge into the SCIF ›",
      capture: "The program grew by $120 million. The system still doesn't work in the field.",
      protect: "You told the Pentagon the truth about the schedule. The program was cut, and so was your bonus.",
      outLabel: "FALLOUT THIS BUDGET CYCLE",
      fired: "Someone else grew the program anyway. What would have had to change for defense spending to have a ceiling?",
      ended: "The program is worth $2 billion now. Does it do what it was supposed to do?",
      turns: [
        [2010, "THE PROGRAM IS SIX MONTHS BEHIND", "Tell the Army now", "Rebaseline the schedule; call it progress"],
        [2012, "SEQUESTRATION · THE BUDGET IS FROZEN", "Cut the program's scope honestly", "Spread subcontracts across 40 districts"],
        [2014, "A SPARE PART COSTS $14,000 · IT'S A $40 BOLT", "Flag the pricing", "Keep the markup; it's allowable", "$"],
        [2016, "THE SYSTEM FAILS FIELD TESTING", "Report the failures in full", "Report 'progress toward requirements'"],
        [2018, "A CONGRESSMAN WANTS A PLANT IN HIS DISTRICT", "Put it where it makes sense", "Put it in his district", "⚡"],
        [2020, "A RETIRED GENERAL WANTS A CONSULTING JOB", "Keep the door closed", "Hire him — he knows the right people", "$"],
        [2023, "THE ARMY WANTS TO CANCEL THE PROGRAM", "Let it end", "Lobby Congress to save it", "⚡"],
      ],
    },
  }),

  life({
    id: "ms-dollar-store",
    protagonist: "Lamont Harris",
    dossierTag: "STORE MANAGER",
    householdName: "The Harrises",
    location: "Greenwood, MS",
    tagline: "Dollar store manager, 27. Makes $38,000. The only store in the neighborhood.",
    description:
      "Lamont Harris grew up in Greenwood with his grandmother, who still lives three blocks from the store. He did a year at Mississippi Valley State before money ran out. He's got a daughter, Nia, who's four, and her mother works nights at the catfish plant.",
    perspective:
      "The grocery store left years ago. Now it's us, the gas station, and the church. People here need what we sell, and we're the only ones selling it. That's not a business plan, it's a monopoly — but somebody's got to run the register.",
    closingAddendum:
      "You were dealt the only store in a neighborhood nobody else would build in. The price of that was yours to set, and you didn't set it.",
    seat: {
      title: "The Store Manager",
      role: "Store Manager, Dollar Store",
      color: "#E5D23F",
      scoreLabel: "SALES PER LABOR HOUR",
      dial: ["staff the store", "hit the labor budget"],
      dialNote: "corporate budgets two people per shift",
      board: "DISTRICT",
      firedBody:
        "District sent a manager from Jackson who ran the store with one person per shift and a 'self-checkout pilot.' The store got robbed twice. Corporate called it shrink.",
      pressure: [
        "District says your labor hours are over budget again.",
        "Your district manager is coming Thursday with someone from 'loss prevention.' That's never good.",
      ],
      ranks: [
        ["Store Manager", "a set of keys"],
        ["Key Holder of the Year", "a plaque in the back room"],
        ["District Manager", "twelve stores in the Delta"],
        ["Regional Director", "the whole state"],
        ["Corporate", "an office in Tennessee"],
        ["VP of Operations", "stock options"],
      ],
      intro: [
        "You're Lamont Harris. You manage the only store in walking distance for three thousand people. There's no grocery, no pharmacy, no bank.",
        "The lights on the wall are the neighborhood: your grandmother's friends, the kids from your old school, the men who come in every day for a single beer.",
        "Corporate gives you a labor budget. There's a dial between staffing the store and hitting it.",
        "There's always somebody in the aisles who can't make the math work. Corporate says prices are set in Tennessee.",
      ],
      introCta: "Unlock the store ›",
      capture: "Labor under budget. One cashier, a line out the door, the milk case empty since Tuesday.",
      protect: "You kept two on the register. District sent an email with 'labor' in the subject line.",
      outLabel: "FALLOUT THIS WEEK",
      fired: "Someone else ran it lean anyway. What would have had to change for the neighborhood to have more than one store?",
      ended: "The store made its numbers. What does a neighborhood look like when this is its store?",
      turns: [
        [2018, "CORPORATE CUTS THE FRESH PRODUCE PILOT", "Keep fresh food on a shelf", "Fill the space with chips and soda", "✂"],
        [2019, "A SMALLER PACKAGE, THE SAME PRICE", "Tell customers about the change", "Re-shelve it quietly"],
        [2020, "THE PANDEMIC · THE STORE IS 'ESSENTIAL'", "Close early to protect your staff", "Stay open; hazard pay isn't approved", "✂"],
        [2021, "THE TOWN'S LAST GROCERY STORE CLOSES", "Push corporate to stock fresh food", "Raise prices on what people need", "$"],
        [2022, "A CUSTOMER CAN'T AFFORD INFANT FORMULA", "Put some back for families", "Lock the formula behind the counter"],
        [2023, "CORPORATE WANTS TO CUT TO ONE CLERK AT NIGHT", "Refuse; it isn't safe", "Schedule one clerk", "✂"],
        [2024, "THE CITY OFFERS A BREAK FOR A REAL GROCERY STORE", "Help them recruit it", "Tell corporate — they'll block it"],
      ],
    },
  }),

  life({
    id: "nc-mortgages",
    protagonist: "Lauren Pryor",
    dossierTag: "MORTGAGE BANKER",
    householdName: "The Pryors",
    location: "Charlotte, NC",
    tagline: "Mortgage banker, 35 in 2004. Top producer in the region. Two kids, a BMW, and a house in Ballantyne.",
    description:
      "Lauren Pryor grew up in Gastonia, where her dad was a mill supervisor until the mills closed. She took a job at the bank after UNC and was writing loans at twenty-four. By thirty-five she was the best producer in the Southeast. Her husband Chad is in commercial real estate.",
    perspective:
      "Homeownership is how regular families build wealth. Everybody said so — the President, Congress, the bank. If a family wants a house and the bank says yes, who am I to say no? Everybody was making money, and everybody's house was going up.",
    closingAddendum:
      "You were dealt the life that climbed out of a mill town on commission. Every loan was legal. Most of them were someone's house.",
    seat: {
      title: "The Mortgage Banker",
      role: "Senior Loan Officer",
      color: "#3FBF7F",
      scoreLabel: "LOAN VOLUME",
      dial: ["loans they can repay", "loans that close"],
      dialNote: "you get paid when it closes, not when it's repaid",
      board: "BRANCH MANAGER",
      firedBody:
        "The bank replaced you with a loan officer from California who wrote twice your volume in adjustable-rate loans. The bank sold every one of them to Wall Street before the first payment was due.",
      pressure: [
        "Your branch manager posted the volume numbers. You're third, behind two guys who started last year.",
        "The regional director asked if you 'still have the hunger.' Your book is being reassigned.",
      ],
      ranks: [
        ["Loan Officer", "a desk and a phone"],
        ["Top Producer", "a trip to Cabo"],
        ["Branch Manager", "a team of twelve"],
        ["Regional Director", "the whole Southeast"],
        ["Executive VP", "a seat on the secondary-market desk"],
        ["Rescued", "a bailout and a bonus"],
      ],
      intro: [
        "You're Lauren Pryor. It's 2004. Home prices are rising everywhere, and the bank will sell every mortgage you write to Wall Street within a month.",
        "The lights on the wall are borrowers: first-time buyers in Charlotte and Durham, retirees refinancing, families who've never owned anything.",
        "Your branch manager watches loan volume. There's a dial between loans they can repay and loans that close.",
        "You'll never hold the loan. By the time anyone knows if they can pay, it's someone else's problem.",
      ],
      introCta: "Open the pipeline ›",
      capture: "Closed. A $340,000 loan with a teaser rate that resets in two years. Your commission was $6,800.",
      protect: "You told them they couldn't afford it. They went to the broker across the street, who said yes.",
      outLabel: "FALLOUT THIS MONTH",
      fired: "Someone else wrote the loan anyway. What would have had to change for the bank to care whether you could pay?",
      ended: "You made it through the crash. What happened to the families you wrote loans for?",
      turns: [
        [2004, "A LOAN THAT NEEDS NO INCOME DOCUMENTATION", "Verify every income", "Stated income — take their word", "$"],
        [2005, "A TEASER RATE MAKES A HOUSE 'AFFORDABLE'", "Sell the fixed rate", "Sell the adjustable; it closes faster"],
        [2006, "A CUSTOMER QUALIFIES FOR PRIME · THE SUBPRIME PAYS MORE", "Give her the prime loan", "Steer her to subprime; you earn double", "$"],
        [2007, "APPRAISERS ARE UNDER PRESSURE TO HIT THE NUMBER", "Use independent appraisers", "Call the appraiser who always comes in high"],
        [2008, "THE CRASH · YOUR BORROWERS ARE UNDERWATER", "Push the bank to modify their loans", "Foreclose on schedule", "✂"],
        [2010, "ROBO-SIGNING · 10,000 FORECLOSURES A MONTH", "Refuse to sign what you haven't read", "Sign them; everybody does", "✎"],
        [2012, "A FUND BUYS THE FORECLOSED HOUSES AS RENTALS", "Sell to families first", "Sell in bulk to the fund", "$"],
      ],
    },
  }),

  life({
    id: "sc-heirs-property",
    protagonist: "Ernestine Gadsden",
    dossierTag: "FAMILY LANDHOLDER",
    householdName: "The Gadsdens",
    location: "Johns Island, SC",
    tagline: "Retired schoolteacher, 66. Gullah Geechee. Her family has held twelve acres since 1868.",
    description:
      "Ernestine Gadsden's great-great-grandfather bought the land after emancipation. It passed down without a will, so now it belongs to forty-one heirs in six states. She's the one who stayed. She pays the taxes, cuts the grass, and keeps the family cemetery clean.",
    perspective:
      "Our people held this land through things you would not believe. Now the resorts want it, and the law makes it easy — any one heir can sell a share, and a developer can force the whole thing to auction. We didn't lose it. It's being taken, one heir at a time.",
    closingAddendum:
      "You were dealt twelve acres your family held through everything. Keeping them turned out to depend on the one thing you couldn't control: forty-one cousins and a developer's checkbook.",
    seat: {
      title: "The Family Steward",
      role: "Heirs' Property Steward",
      color: "#3F9FBF",
      scoreLabel: "LAND VALUE",
      dial: ["keep the land", "take the offer"],
      dialNote: "one heir selling can force the whole property to auction",
      board: "THE COUSINS",
      firedTitle: "PARTITIONED",
      firedBody:
        "A cousin in New Jersey sold his share to a developer's LLC. The LLC petitioned the court, and the whole twelve acres went to auction. The developer bid alone. The cemetery is behind a gate now.",
      pressure: [
        "Three cousins called about the developer's letter. They want to know why you're 'sitting on money.'",
        "A lawyer for the developer's LLC sent a letter about 'partition.' The cousins in Atlanta are listening.",
      ],
      ranks: [
        ["Steward", "the keys to the family house"],
        ["Family Voice", "the cousins call you first"],
        ["Community Leader", "the land trust asks your advice"],
        ["Seller", "a check for your share"],
        ["Developer Partner", "a stake in the new resort"],
        ["Consultant", "the developer pays you to talk to other families"],
      ],
      intro: [
        "You're Ernestine Gadsden. Twelve acres on Johns Island, owned by forty-one heirs, with a developer sending letters every month.",
        "The lights on the wall are the island: families like yours, the church, the people who fish the creeks and work the resorts across the bridge.",
        "The cousins want money; the developer wants the land. There's a dial between keeping the land and taking the offer.",
        "Every family on the island is getting the same letters. What one family does, the developer uses against the next.",
      ],
      introCta: "Walk the property line ›",
      capture: "The family got a check. The developer got a road through the next property over. Three more families got letters that week.",
      protect: "You held on. The taxes went up again, and two cousins stopped paying their share.",
      outLabel: "FALLOUT THIS YEAR",
      fired: "The court sold it anyway. What would have had to change for the law to protect land held the way your family held it?",
      ended: "The land is still yours, or it isn't. What's left of the island that raised you?",
      turns: [
        [2006, "A DEVELOPER OFFERS TO BUY ONE COUSIN'S SHARE", "Talk the cousin out of it", "Let him sell; it's his share"],
        [2009, "THE COUNTY REASSESSES · TAXES TRIPLE", "Pay the taxes yourself", "Let the county put it up for tax sale"],
        [2012, "A RESORT WANTS AN EASEMENT FOR A ROAD", "Refuse the easement", "Sell the easement for cash", "$"],
        [2015, "THE CEMETERY IS IN THE DEVELOPER'S SITE PLAN", "Fight to protect the graves", "Let the family vote to sell"],
        [2018, "A LAND TRUST OFFERS HELP CLEARING THE TITLE", "Spend two years clearing it", "Sell to the developer — faster"],
        [2021, "THE PRICE HITS $400,000 AN ACRE", "Keep it for the grandchildren", "Take the money for the family"],
        [2024, "THE COUSINS VOTE · 22 TO 19 TO SELL", "Buy out the ones who want to sell", "Sign with the majority", "✎"],
      ],
    },
  }),

  life({
    id: "tn-hospital-billing",
    protagonist: "Brittany Patterson",
    dossierTag: "REVENUE CYCLE MANAGER",
    householdName: "The Pattersons",
    location: "Nashville, TN",
    tagline: "Revenue cycle manager, 34. Works for a hospital company. Still paying off her own ER bill from 2017.",
    description:
      "Brittany Patterson grew up in Murfreesboro and went to MTSU for accounting. She manages billing and collections for a chain of hospitals headquartered in Nashville, which is the capital of the for-profit hospital industry. Her fiancé Tyler is a sound engineer on Music Row.",
    perspective:
      "Hospitals aren't charities, even the nonprofits. Somebody has to pay for the building and the nurses. The bill is complicated because the whole system is complicated. I just make sure the hospital gets paid for what it does.",
    closingAddendum:
      "You were dealt the desk where a hospital stay becomes a debt. You'd been on the other side of that bill yourself.",
    seat: {
      title: "The Revenue Manager",
      role: "Revenue Cycle Manager",
      color: "#BF3F7F",
      scoreLabel: "COLLECTIONS",
      dial: ["bill what's fair", "bill what's allowed"],
      dialNote: "the chargemaster price is whatever the hospital says it is",
      board: "CFO",
      firedBody:
        "The company outsourced revenue cycle to a firm that sues patients by the thousand. The collections number went up. So did the wage garnishments in Rutherford County.",
      pressure: [
        "The CFO says your hospitals' collections are below the company average.",
        "The company is 'evaluating outsourcing partners' for revenue cycle. You're in the meeting, for now.",
      ],
      ranks: [
        ["Manager", "four hospitals' billing"],
        ["Director", "the Tennessee division"],
        ["VP of Revenue Cycle", "the whole company's collections"],
        ["CFO", "the earnings call"],
        ["Consultant", "other hospitals license your model"],
        ["Industry Board", "a seat at the hospital association"],
      ],
      intro: [
        "You're Brittany Patterson. You manage billing for four hospitals. One in five patients can't pay what they owe.",
        "The lights on the wall are patients: the uninsured, the underinsured, the people who got a surprise bill from a doctor they never met.",
        "The CFO watches collections. There's a dial between billing what's fair and billing what's allowed.",
        "You still have a $2,300 balance from a kidney stone. You know what the letter looks like.",
      ],
      introCta: "Open the billing queue ›",
      capture: "Collections up 4%. A family in Smyrna had their wages garnished for an appendectomy.",
      protect: "You applied the charity care policy. The CFO asked why your numbers dipped.",
      outLabel: "FALLOUT THIS QUARTER",
      fired: "A collections firm sued them anyway. What would have had to change for getting sick not to be a debt?",
      ended: "Collections up every year. How many of those patients had insurance?",
      turns: [
        [2014, "THE CHARGEMASTER PRICE FOR AN MRI IS $3,800", "Give uninsured patients a real price", "Bill the chargemaster price"],
        [2016, "CHARITY CARE IS OPTIONAL UNDER STATE LAW", "Screen every patient for it", "Don't mention it unless they ask", "✂"],
        [2017, "OUT-OF-NETWORK DOCTORS IN IN-NETWORK HOSPITALS", "Warn patients before treatment", "Bill the surprise charges", "$"],
        [2018, "A NEW COLLECTIONS VENDOR SUES FOR ANY DEBT OVER $500", "Keep lawsuits as a last resort", "Sign with the vendor", "§"],
        [2020, "THE PANDEMIC · RELIEF MONEY ARRIVES", "Forgive balances for struggling patients", "Keep collecting and bank the relief", "$"],
        [2022, "A FEDERAL RULE REQUIRES POSTED PRICES", "Post clear prices", "Post a file nobody can read"],
        [2024, "THE COMPANY WANTS TO SELL OLD PATIENT DEBT", "Forgive it instead", "Sell it for three cents on the dollar", "$"],
      ],
    },
  }),

  life({
    id: "va-data-centers",
    protagonist: "Esther Kim",
    dossierTag: "ECONOMIC DEVELOPMENT DIRECTOR",
    householdName: "The Kims",
    location: "Loudoun County, VA",
    tagline: "County economic development director, 39. Korean-American. Her parents run a dry cleaner in Annandale.",
    description:
      "Esther Kim grew up behind the counter of her parents' dry cleaner, doing homework between customers. She went to UVA, got a master's in public policy, and came home to work for the county. She and her husband Jae have two kids and a townhouse in Ashburn.",
    perspective:
      "The county needs revenue. Data centers pay enormous taxes and send almost no kids to school. It looks like free money. It's my job to bring the money in, and it's somebody else's job to worry about what comes with it.",
    closingAddendum:
      "You were dealt the job of bringing money into a county that needed it. The money came with transmission lines, a hum at night, and a power bill for everyone.",
    seat: {
      title: "The Development Director",
      role: "Economic Development Director",
      color: "#7F7FBF",
      scoreLabel: "TAX REVENUE",
      dial: ["the neighbors", "the data centers"],
      dialNote: "one data center pays more tax than ten thousand homes",
      board: "SUPERVISORS",
      firedBody:
        "The board replaced you with a director who used to work for a data center developer. She approved three new campuses in her first year, and the transmission lines went up through the historic district.",
      pressure: [
        "The board chair asked why the new data center proposal is 'stuck' in your office.",
        "A developer's lobbyist met with three supervisors. None of them mentioned it to you.",
      ],
      ranks: [
        ["Director", "a county office and a staff of eight"],
        ["Deputy Administrator", "the budget runs through you"],
        ["County Administrator", "the whole county"],
        ["State Secretary", "a seat in Richmond"],
        ["Industry Advisor", "a data center association title"],
        ["Tech Executive", "site selection for a cloud company"],
      ],
      intro: [
        "You're Esther Kim. Loudoun County has more data centers than anywhere on Earth. Seventy percent of the internet's traffic passes through here.",
        "The lights on the wall are the county: families in new subdivisions, old farms, historic Black communities along the rural roads, and everyone who pays a power bill.",
        "The Board of Supervisors watches tax revenue. There's a dial between protecting the neighbors and landing the data centers.",
        "The data centers want land, water, and power. The county has all three, for now.",
      ],
      introCta: "Take the developer's call ›",
      capture: "The campus was approved. The county cut property taxes 2 cents. The hum started in March and never stopped.",
      protect: "You slowed the approval. The developer went to the next county over, and the board noticed.",
      outLabel: "FALLOUT THIS BUDGET",
      fired: "Someone else approved it anyway. What would have had to change for the county not to need the data centers?",
      ended: "The county is richer than ever. Who pays for the power lines?",
      turns: [
        [2012, "THE FIRST BIG DATA CENTER CAMPUS", "Require setbacks from homes", "Approve it by right, no hearing"],
        [2015, "A TAX BREAK ON SERVER EQUIPMENT", "Let it expire", "Extend it forever", "$"],
        [2018, "A CAMPUS NEXT TO A HISTORIC BLACK COMMUNITY", "Protect the community", "Rezone the land"],
        [2020, "THE DATA CENTERS NEED A NEW TRANSMISSION LINE", "Bury it, whatever it costs", "Run it overhead through the neighborhood", "⚡"],
        [2022, "THE UTILITY SAYS IT CAN'T KEEP UP", "Pause new approvals", "Let the utility raise rates on everyone", "$"],
        [2023, "THE DATA CENTERS USE MILLIONS OF GALLONS A DAY", "Require water recycling", "Let them draw from the reservoir"],
        [2025, "AI CAMPUSES WANT FIVE TIMES THE POWER", "Say no until the grid is ready", "Approve them all; the tax money is huge"],
      ],
    },
  }),
];
