import { life } from "./build";

export const WEST = [
  life({
    id: "ak-native-corporation",
    protagonist: "Rose Charles",
    dossierTag: "CORPORATION BOARD MEMBER",
    householdName: "The Charleses",
    location: "Bethel, AK",
    tagline: "Yup'ik. Regional Native corporation board member, 49. Fishes the Kuskokwim every summer.",
    description:
      "Rose Charles grew up in a village upriver from Bethel, speaking Yup'ik at home. She's a nurse at the regional hospital and was elected to the board of the Native corporation that owns her people's land. Her father taught her to fish. Her daughter is at the university in Anchorage.",
    perspective:
      "Congress made us shareholders in corporations instead of nations. The land is ours, but the corporation has to make money off it. The dividend checks pay for heating oil in villages where a gallon costs twelve dollars. The fish are who we are.",
    closingAddendum:
      "You were dealt a people's land held as a corporation. The dividend kept the villages warm. The river kept them alive. Somebody made you choose.",
    seat: {
      title: "The Board Member",
      role: "Board Member, Native Corporation",
      color: "#3F8FBF",
      scoreLabel: "DIVIDENDS",
      dial: ["the river", "the dividend"],
      dialNote: "the corporation must turn a profit by law",
      board: "SHAREHOLDERS",
      firedTitle: "VOTED OFF",
      firedBody:
        "Shareholders voted you off the board for a candidate who promised bigger dividends. He approved the mine's expansion at his first meeting.",
      pressure: [
        "Shareholders at the annual meeting asked why the dividend is smaller than last year's.",
        "A slate of candidates backed by the mining partner is running for your seat.",
      ],
      ranks: [
        ["Board Member", "a seat at the table"],
        ["Committee Chair", "the lands committee"],
        ["Board Chair", "the corporation speaks through you"],
        ["Statewide Voice", "the Native federation"],
        ["Industry Partner", "a seat on the mining company's advisory board"],
        ["Washington", "you testify before Congress"],
      ],
      intro: [
        "You're Rose Charles. The corporation you help run owns millions of acres of Yup'ik land. A mining company wants to dig one of the largest gold mines on Earth at the headwaters of the Kuskokwim.",
        "The lights on the wall are the villages: families who fish for salmon, hunt caribou, and pay twelve dollars a gallon for heating oil.",
        "Shareholders watch the dividend. There's a dial between protecting the river and growing the dividend.",
        "The mine would bring jobs and money. It would also sit upstream of every village that eats from the river.",
      ],
      introCta: "Take your seat ›",
      actLabel: "VOTE",
      capture: "The dividend went up. A village upriver voted to oppose the mine; the corporation's lawyers answered.",
      protect: "You voted to slow the mine. The dividend was cut, and your phone rang all night.",
      outLabel: "FALLOUT THIS YEAR",
      fired: "Someone else voted yes anyway. What would have had to change for land to not have to turn a profit?",
      ended: "The dividends are larger. How are the salmon?",
      turns: [
        [2008, "A MINING COMPANY WANTS TO LEASE THE LAND", "Require tribal consent from every village", "Sign the lease; the corporation needs revenue", "✎"],
        [2012, "THE KING SALMON RUNS COLLAPSE", "Fund research on the river", "Say the mine had nothing to do with it"],
        [2015, "A PIPELINE ROUTE ACROSS SUBSISTENCE LAND", "Reroute it", "Approve the cheapest route"],
        [2018, "THE MINE NEEDS A PERMIT · THE VILLAGES OBJECT", "Support the villages' objections", "Support the permit", "✎"],
        [2020, "THE PANDEMIC · VILLAGES CUT OFF", "Pay a special hardship dividend", "Hold the reserves for the mine partnership"],
        [2022, "A CHUM SALMON DISASTER · FISHING CLOSED", "Declare an emergency and fund food", "Stay on schedule with the mine"],
        [2024, "THE MINE'S FINAL PERMIT", "Vote to withdraw the land", "Vote to proceed", "✎"],
      ],
    },
  }),

  life({
    id: "co-prison-town",
    protagonist: "Daniel Montoya",
    dossierTag: "CORRECTIONS LIEUTENANT",
    householdName: "The Montoyas",
    location: "Cañon City, CO",
    tagline: "Corrections lieutenant, 38. Hispano family, in Colorado for six generations. Coaches youth wrestling.",
    description:
      "Daniel Montoya's town has thirteen prisons. His father was a guard, his uncle was a guard, and his cousin did three years in one of them. He and his wife Alicia have three boys. They go to Mass at St. Michael's and eat green chile every Friday.",
    perspective:
      "The prisons are the economy here. Without them, this is a ghost town. We didn't make the laws that fill the beds. We just run the place where they end up.",
    closingAddendum:
      "You were dealt a town that runs on prisons. Every empty bed was a job. Every full one was somebody's cousin.",
    seat: {
      title: "The Lieutenant",
      role: "Corrections Lieutenant",
      mode: "attn",
      color: "#8F8F8F",
      scoreLabel: "BEDS FILLED",
      dial: ["get them home", "keep the beds full"],
      dialNote: "a prison's budget follows its headcount",
      board: "WARDEN",
      firedBody:
        "The warden promoted a lieutenant from the private prison down the road. He tightened discipline, ended the education program, and kept the beds full.",
      pressure: [
        "The warden says your unit's incident reports are 'too lenient.'",
        "The state is considering closing a unit. The warden says it won't be yours — if you get tougher.",
      ],
      ranks: [
        ["Lieutenant", "a unit of 200"],
        ["Captain", "the whole shift"],
        ["Major", "the facility's security"],
        ["Warden", "the prison is yours"],
        ["Regional Director", "five prisons"],
        ["Private Operator", "a contract with a prison company"],
      ],
      intro: [
        "You're Daniel Montoya. You're a lieutenant at a state prison in Cañon City. The town has thirteen of them.",
        "The lights on the wall are the incarcerated and their families: kids who visit on Saturdays, mothers who drive four hours, people who come home without the right to vote.",
        "The warden watches headcount and discipline. There's a dial between getting them home and keeping the beds full.",
        "Every write-up you file adds time to someone's sentence. Every empty bed is a job in town.",
      ],
      introCta: "Report for shift ›",
      actLabel: "ENFORCE",
      capture: "The write-up stuck. He lost his parole date. His daughter's birthday is next month.",
      protect: "You let it go with a warning. The warden asked why your unit's reports were down.",
      outLabel: "FALLOUT THIS SHIFT",
      fired: "Someone else wrote them up anyway. What would have had to change for a town not to need its prisons full?",
      ended: "The beds stayed full. How many of the people who came home stayed home?",
      turns: [
        [2008, "THE STATE BUDGET IS CUT · EDUCATION PROGRAMS FIRST", "Fight to keep the GED classes", "Let them go; security first", "✂"],
        [2011, "SOLITARY CONFINEMENT FOR MINOR INFRACTIONS", "Use it as a last resort", "Use it to keep order", "▣"],
        [2013, "A PRIVATE PRISON COMPANY OFFERS THE STATE A DEAL", "Oppose it at the county", "Support it; it's more jobs"],
        [2016, "PHONE CALLS COST FAMILIES $15 FOR 15 MINUTES", "Push to lower the rates", "The contract funds the facility", "$"],
        [2019, "A SENTENCING REFORM WOULD RELEASE 800 PEOPLE", "Support it publicly", "Warn about 'public safety'", "⚡"],
        [2020, "THE PANDEMIC · COVID IN THE PRISON", "Push for early release of the vulnerable", "Lock down, 23 hours a day", "▣"],
        [2023, "THE STATE PROPOSES CLOSING A PRISON", "Help plan the town's transition", "Lobby to keep it open", "⚡"],
      ],
    },
  }),

  life({
    id: "hi-resort",
    protagonist: "Kaipo Kealoha",
    dossierTag: "RESORT OPERATIONS MANAGER",
    householdName: "The Kealohas",
    location: "Lahaina, HI",
    tagline: "Native Hawaiian. Resort operations manager, 38. His family has farmed taro in the valley for generations.",
    description:
      "Kaipo Kealoha grew up in Lahaina, surfing before school and working at his uncle's taro patch on weekends. He started at the resort as a busboy and worked his way up. His mom lost her house in the 2023 fire. She lives with Kaipo, his wife Leilani, and their two girls now.",
    perspective:
      "Tourism is the only real job on Maui. It paid for my house and my kids' school. But the water that used to run to the taro fields runs to the resort golf courses now. We serve people on land our grandparents farmed.",
    closingAddendum:
      "You were dealt a job serving visitors on the land your family farmed. The resort got the water. Lahaina got the fire.",
    seat: {
      title: "The Resort Manager",
      role: "Director of Operations, Resort",
      color: "#3FBFA3",
      scoreLabel: "OCCUPANCY",
      dial: ["the community", "the guests"],
      dialNote: "a golf course drinks more water than a village",
      board: "OWNERS",
      firedBody:
        "The resort's owners on the mainland replaced you with a manager from Las Vegas. He fought the water restrictions in court and hired temporary workers from off-island.",
      pressure: [
        "The ownership group says occupancy is lagging the other resorts.",
        "The regional VP flew in from Honolulu. He asked about 'your commitment to the brand.'",
      ],
      ranks: [
        ["Operations Director", "the resort's staff"],
        ["General Manager", "the whole resort"],
        ["Regional VP", "four resorts on Maui"],
        ["Hotel Association Chair", "the county council listens"],
        ["Corporate", "an office in the mainland HQ"],
        ["Investor", "a stake in the next development"],
      ],
      intro: [
        "You're Kaipo Kealoha. You run operations at a big resort in Kāʻanapali, north of Lahaina. It's the biggest employer in West Maui.",
        "The lights on the wall are Maui: housekeepers commuting two hours, taro farmers with dry streams, families who can't afford to live where they grew up.",
        "The resort's owners watch occupancy. There's a dial between the community and the guests.",
        "Maui has three million visitors a year and 165,000 residents. The water, the housing, and the roads have to be shared.",
      ],
      introCta: "Walk the property ›",
      capture: "The resort sold out. The golf course stayed green. A taro patch upstream went dry for the third summer.",
      protect: "You gave water back to the streams. The owners asked why the golf course was brown.",
      outLabel: "FALLOUT THIS SEASON",
      fired: "Someone else kept the water flowing to the resort anyway. What would have had to change for Maui to come first on Maui?",
      ended: "The resort is full. Can your daughters afford to live here?",
      turns: [
        [2012, "THE RESORT WANTS MORE STREAM WATER", "Leave it for the taro farmers", "Take the full allocation"],
        [2015, "VACATION RENTALS ARE BUYING UP LAHAINA HOUSES", "Support rental limits", "Stay quiet; rentals feed your restaurant"],
        [2018, "THE RESORT WANTS A NEW TOWER", "Oppose it on water grounds", "Support it; it's jobs"],
        [2020, "THE PANDEMIC · TOURISM STOPS", "Keep the workers on half pay", "Lay off everyone", "✂"],
        [2021, "TOURISM COMES BACK · RECORD VISITORS", "Push for visitor limits", "Fill every room", "$"],
        [2023, "THE FIRE · LAHAINA BURNS", "Open the resort to displaced families", "Keep the rooms for the tourists"],
        [2024, "INVESTORS OFFER CASH FOR BURNED LAHAINA LOTS", "Back a law to stop outside buyers", "Help the investors find sellers", "$"],
      ],
    },
  }),

  life({
    id: "id-talk-radio",
    protagonist: "Brett Sorensen",
    dossierTag: "TALK RADIO HOST",
    householdName: "The Sorensens",
    location: "Coeur d'Alene, ID",
    tagline: "AM talk radio host, 45. Evangelical. Moved from California in 2009. The most-listened-to show in the Panhandle.",
    description:
      "Brett Sorensen grew up in Fresno and sold cars until the recession wiped out the dealership. He moved his family to Idaho, joined a Bible church, and got a morning slot on a local AM station. He has five kids, a truck, and 90,000 listeners who feel like family.",
    perspective:
      "People up here feel like nobody listens to them. The coastal media laughs at them. I give them a voice. If the show gets heated sometimes, that's because people are angry, and they have reason to be.",
    closingAddendum:
      "You were dealt a microphone in a town that felt ignored. You gave it a voice, and the voice learned what kept the ratings up.",
    seat: {
      title: "The Host",
      role: "Morning Talk Radio Host",
      mode: "attn",
      color: "#BF5F3F",
      scoreLabel: "RATINGS",
      dial: ["inform them", "inflame them"],
      dialNote: "anger keeps them listening through the ad break",
      board: "STATION OWNER",
      firedTitle: "OFF THE AIR",
      firedBody:
        "The station's new owner, a national radio chain, replaced your show with a syndicated host from Florida. He's angrier than you ever were, and his ratings are higher.",
      pressure: [
        "The station owner says your ratings dipped for the second quarter.",
        "The national chain that bought the station is 'reviewing local programming.'",
      ],
      ranks: [
        ["Host", "a morning slot"],
        ["Top of the Market", "billboards on I-90"],
        ["Regional Network", "six stations in three states"],
        ["National Syndication", "stations in thirty markets"],
        ["TV Contributor", "a cable news slot"],
        ["Kingmaker", "candidates come to you first"],
      ],
      intro: [
        "You're Brett Sorensen. Three hours a day, five days a week, you talk to North Idaho.",
        "The lights on the wall are your listeners: loggers, retirees, young families who moved from California and Washington, and the people who've lived here all along.",
        "The station owner watches ratings. There's a dial between informing them and inflaming them.",
        "The local paper cut its staff to four. For a lot of people, your show is the news now.",
      ],
      introCta: "Go on the air ›",
      actLabel: "ON AIR",
      capture: "The phones lit up for three hours. A school board meeting that night needed a sheriff's deputy.",
      protect: "You had a calm conversation with a guest from the county. The phones were quiet. The station owner noticed.",
      outLabel: "FALLOUT THIS BROADCAST",
      fired: "A louder host took the slot anyway. What would have had to change for local radio not to need an enemy?",
      ended: "You were the voice of North Idaho. What did North Idaho sound like when you started?",
      turns: [
        [2010, "THE HEALTH CARE LAW PASSES", "Explain what it does and doesn't do", "Call it a government takeover", "⚡"],
        [2013, "A CALLER CLAIMS THE COUNTY IS HIDING SOMETHING", "Ask for evidence on air", "Let him run with it", "⚡"],
        [2016, "A NATIONAL CHAIN WANTS YOUR SHOW", "Stay local", "Sign; follow their talking points", "$"],
        [2018, "THE LIBRARY BOARD IS DEBATING BOOKS", "Invite the librarian on", "Read the 'worst pages' on air", "⚡"],
        [2020, "THE PANDEMIC · MASK ORDERS", "Tell them to listen to the local doctors", "Call the health board tyrants", "⚡"],
        [2021, "A HEALTH BOARD MEMBER RECEIVES DEATH THREATS", "Condemn it on air", "Say 'people are frustrated'"],
        [2024, "THE COUNTY HOSPITAL LOSES ITS OBSTETRICIANS", "Cover why they left", "Blame outsiders", "⚡"],
      ],
    },
  }),

  life({
    id: "mt-coal-lease",
    protagonist: "Vernon Old Coyote",
    dossierTag: "TRIBAL LEGISLATOR",
    householdName: "The Old Coyotes",
    location: "Crow Agency, MT",
    tagline: "Crow Nation legislator, 57. Rodeo rider in his youth. Unemployment on the reservation is near 50%.",
    description:
      "Vernon Old Coyote grew up speaking Crow at home and rode saddle bronc through his twenties. He worked at the coal mine on the reservation for eighteen years before being elected to the tribal legislature. He and his wife Marlene have raised their grandchildren. He dances at Crow Fair every August.",
    perspective:
      "Coal paid for our government, our schools, our elders' checks. Now the world says coal is over, and nobody is offering to replace what it paid for. We didn't create climate change. We're just the people who get told to pay for it first.",
    closingAddendum:
      "You were dealt a nation whose budget came out of the ground. The world moved on from coal. Nobody offered your people a way to move with it.",
    seat: {
      title: "The Legislator",
      role: "Crow Tribal Legislator",
      color: "#BF7F3F",
      scoreLabel: "COAL ROYALTIES",
      dial: ["the land", "the lease"],
      dialNote: "coal pays for most of the tribal government",
      board: "DISTRICT",
      firedTitle: "VOTED OUT",
      firedBody:
        "Your district voted you out for a candidate who promised to keep the mine open at any cost. He signed a new lease extension the first week.",
      pressure: [
        "Elders in your district are asking why their per capita check was smaller.",
        "The chairman says you're 'standing in the way of jobs.' Your opponent is saying the same thing at every gym.",
      ],
      ranks: [
        ["Legislator", "a seat and a district"],
        ["Committee Chair", "the resources committee"],
        ["Speaker", "the legislature follows you"],
        ["Chairman", "the whole Crow Nation"],
        ["National Voice", "the tribal energy council"],
        ["Industry Partner", "a seat on the coal company's advisory board"],
      ],
      intro: [
        "You're Vernon Old Coyote. The Crow Nation sits on billions of tons of coal. The royalties pay for nearly everything the tribal government does.",
        "The lights on the wall are the Crow people: elders who depend on per capita checks, miners with good jobs, kids in schools that need the money.",
        "Your district watches royalties and jobs. There's a dial between protecting the land and extending the lease.",
        "The utilities that buy the coal are closing their power plants. The mine is dying either way.",
      ],
      introCta: "Take your seat ›",
      actLabel: "VOTE",
      capture: "The lease was extended. The per capita checks went out. The mine cut another twenty jobs anyway.",
      protect: "You voted to invest in something else. There wasn't money to invest.",
      outLabel: "FALLOUT THIS SESSION",
      fired: "Someone else signed the lease anyway. What would have had to change for the Crow Nation to have a choice?",
      ended: "The mine is closing. What's the Crow Nation's budget now?",
      turns: [
        [2008, "THE COAL COMPANY WANTS A LEASE EXTENSION", "Negotiate better terms", "Sign the extension quickly", "✎"],
        [2011, "A NEW MINE ON SACRED LAND", "Protect the sites", "Approve it; the nation needs revenue"],
        [2013, "AN EXPORT TERMINAL TO SHIP COAL TO ASIA", "Stay neutral", "Invest the tribe's money in it", "$"],
        [2016, "THE POWER PLANTS ARE CLOSING", "Plan for life after coal", "Fight the closures in court", "§"],
        [2019, "A SOLAR COMPANY OFFERS A SMALL LEASE", "Take it and plan", "Turn it down; coal pays better"],
        [2021, "THE MINE CUTS HALF ITS WORKERS", "Push for job retraining money", "Cut the tribe's budget to match"],
        [2024, "FEDERAL CLEAN ENERGY MONEY IS AVAILABLE", "Apply for it", "Lobby to extend coal instead", "⚡"],
      ],
    },
  }),

  life({
    id: "nv-sportsbook",
    protagonist: "Grace Santos",
    dossierTag: "CASINO HOST",
    householdName: "The Santoses",
    location: "Las Vegas, NV",
    tagline: "Filipino-American. VIP casino host, 42. Her mother cleaned rooms on the Strip for twenty-five years.",
    description:
      "Grace Santos's parents came from Pampanga in 1985. Her mother was a housekeeper at a Strip hotel, a member of the Culinary Union for twenty-five years. Grace started as a cocktail server and worked her way up to VIP host. She and her husband Mark have a daughter at UNLV and a son in high school.",
    perspective:
      "This town was built on gambling, and it gave my family a middle-class life. My mother's union job paid for our house. People come here to lose money — they know it. I just make sure they enjoy it.",
    closingAddendum:
      "You were dealt a town where losing money is the product. Your mother cleaned the rooms. You kept the players at the table.",
    seat: {
      title: "The Host",
      role: "VIP Casino Host",
      mode: "attn",
      color: "#BF3F9F",
      scoreLabel: "THEORETICAL WIN",
      dial: ["let them walk away", "keep them playing"],
      dialNote: "the house earns on every hour they stay",
      board: "CASINO MARKETING",
      firedBody:
        "Casino marketing replaced you with a data-driven 'player development' system that sends offers the moment a player tries to leave. It knows who's losing and who's chasing.",
      pressure: [
        "Casino marketing says your players' theoretical win is down 12%.",
        "The VP of player development wants to 'optimize' your player list. He means reassign it.",
      ],
      ranks: [
        ["Host", "a list of players"],
        ["Senior Host", "the high rollers"],
        ["Executive Host", "a private jet budget"],
        ["Director of Player Development", "all the hosts"],
        ["VP of Marketing", "the casino's loyalty program"],
        ["Sportsbook", "the app's VIP program"],
      ],
      intro: [
        "You're Grace Santos. You're a VIP host at a casino on the Strip. Your job is to keep big players coming back and happy.",
        "The lights on the wall are the players: businessmen who can afford it, retirees who can't, young men on their phones at 3 a.m.",
        "Casino marketing watches theoretical win. There's a dial between letting them walk away and keeping them playing.",
        "You know which players are having a good time and which ones are in trouble. The system knows too.",
      ],
      introCta: "Walk the casino floor ›",
      actLabel: "COMP",
      capture: "He stayed three more days on a free suite. He lost his retirement account.",
      protect: "You told him to go home. Casino marketing asked why his play dropped.",
      outLabel: "FALLOUT THIS WEEKEND",
      fired: "An algorithm kept them playing anyway. What would have had to change for losing not to be the business model?",
      ended: "Your players are the casino's best customers. How many of them can afford it?",
      turns: [
        [2010, "A PLAYER IS ON A LOSING STREAK", "Suggest he take a break", "Comp him a suite and a show", "$"],
        [2013, "A 'LOSS REBATE' KEEPS PLAYERS COMING BACK", "Offer it only to players who can afford it", "Offer it to your biggest losers", "$"],
        [2016, "A PLAYER ASKS TO BE BANNED", "Help him self-exclude", "Tell him you'll 'keep an eye out'"],
        [2018, "SPORTS BETTING IS LEGAL NATIONWIDE", "Stay on the casino floor", "Move to the sportsbook app", "▶"],
        [2020, "THE PANDEMIC · CASINOS CLOSE", "Check in on your players' wellbeing", "Push them to the app", "▶"],
        [2022, "THE APP CAN SEND OFFERS AT 2 A.M.", "Turn off late-night marketing", "Let the algorithm decide", "⚙"],
        [2024, "A COLLEGE KID IS YOUR BIGGEST LOSER", "Flag his account", "Upgrade him to VIP", "$"],
      ],
    },
  }),

  life({
    id: "nm-state-land",
    protagonist: "Ramona Gallegos",
    dossierTag: "DEPUTY LAND COMMISSIONER",
    householdName: "The Gallegoses",
    location: "Santa Fe, NM",
    tagline: "Nuevomexicana. Deputy state land commissioner, 43. Her family has been in northern New Mexico since before it was America.",
    description:
      "Ramona Gallegos grew up in Chimayó, where her family has lived for three hundred years. Her grandfather lost his family's grazing land to a federal forest. She went to UNM and law school and now helps run the office that leases state trust land to oil companies. That money pays for New Mexico's schools.",
    perspective:
      "Oil pays for our schools, our hospitals, everything. New Mexico is one of the poorest states in the country. Without oil money, we'd have nothing. But the wells are down in the Permian, and the kids who breathe the air there go to the schools the oil money builds.",
    closingAddendum:
      "You were dealt a poor state's only big check. It came out of the Permian, and so did the air the kids down there breathed.",
    seat: {
      title: "The Land Commissioner",
      role: "Deputy State Land Commissioner",
      color: "#BF9F5F",
      scoreLabel: "LEASE REVENUE",
      dial: ["the air", "the schools"],
      dialNote: "a third of the state budget is oil money",
      board: "COMMISSIONER",
      firedBody:
        "The commissioner replaced you with a deputy who used to be an oil company lawyer. She opened a million new acres for leasing in her first year.",
      pressure: [
        "The commissioner asked why lease revenue fell short of the projection.",
        "The oil industry association just endorsed the commissioner's opponent. The commissioner wants results.",
      ],
      ranks: [
        ["Deputy Commissioner", "the leasing office"],
        ["Chief of Staff", "the commissioner's office"],
        ["Land Commissioner", "the office is yours"],
        ["Governor's Cabinet", "the energy department"],
        ["Congress", "a seat in Washington"],
        ["Industry Board", "a seat at an oil company"],
      ],
      intro: [
        "You're Ramona Gallegos. The State Land Office leases millions of acres of trust land to oil and gas companies. The money goes to New Mexico's schools.",
        "The lights on the wall are New Mexicans: kids in schools across the state, and the families in the Permian Basin who live next to the wells.",
        "The commissioner watches lease revenue. There's a dial between protecting the air and funding the schools.",
        "The Permian is the richest oil field in America. It's also the reason the air in Hobbs is so hard to breathe.",
      ],
      introCta: "Open the lease file ›",
      capture: "A new lease sold for a record price. The school fund grew. The flaring near Carlsbad lit the sky orange every night.",
      protect: "You set stricter rules on methane. Revenue dropped. The commissioner noticed.",
      outLabel: "FALLOUT THIS SALE",
      fired: "Someone else signed the lease anyway. What would have had to change for New Mexico's schools not to depend on oil?",
      ended: "The school fund is the biggest it's ever been. What happened to the air in the Permian?",
      turns: [
        [2012, "FRACKING OPENS THE PERMIAN", "Lease slowly, with strict rules", "Lease everything, fast", "$"],
        [2014, "METHANE IS LEAKING FROM WELLS", "Require leak detection", "Leave it to the federal government"],
        [2016, "OIL PRICES CRASH · THE SCHOOL BUDGET IS SHORT", "Cut other spending", "Lower royalty rates to keep drilling", "$"],
        [2018, "A WELL NEAR AN ELEMENTARY SCHOOL", "Require a setback", "Approve it; the school needs the money"],
        [2020, "FLARING HITS RECORD LEVELS", "Ban routine flaring", "Let the market handle it"],
        [2022, "THE STATE HAS A RECORD SURPLUS FROM OIL", "Invest in life after oil", "Cut taxes and keep leasing", "$"],
        [2024, "A PROPOSAL TO LEASE LAND NEAR CHACO CANYON", "Protect it", "Lease it; the price is right", "✎"],
      ],
    },
  }),

  life({
    id: "or-labor-contractor",
    protagonist: "Maribel Cruz",
    dossierTag: "FARM LABOR CONTRACTOR",
    householdName: "The Cruzes",
    location: "Hood River, OR",
    tagline: "Farm labor contractor, 40. Came from Oaxaca at fourteen. Picked pears before she ran the crews.",
    description:
      "Maribel Cruz came to Oregon with her uncle and picked pears through high school. She learned English at night, got her papers through the 1986 amnesty her father qualified for, and now runs a labor contracting business that supplies crews to orchards up and down the valley. Her kids are in the Hood River schools.",
    perspective:
      "The growers need workers. The workers need jobs. I'm in the middle. The growers set the price, and I have to make my margin from it. Everybody complains about the contractors, but nobody else wants to do this job.",
    closingAddendum:
      "You were dealt the ladder out of the orchard. It turned out to be the one standing between the growers and the crews.",
    seat: {
      title: "The Labor Contractor",
      role: "Farm Labor Contractor",
      color: "#9FBF5F",
      scoreLabel: "CREWS PLACED",
      dial: ["pay the crews", "keep the margin"],
      dialNote: "the grower pays a flat rate per bin",
      board: "GROWERS",
      firedBody:
        "The growers switched to a contractor from California who brings H-2A workers on guest visas and houses them in shipping containers. He charges them for the housing.",
      pressure: [
        "The biggest grower says your rate is higher than the contractor from Yakima.",
        "Two growers didn't renew for next season. They're 'looking at H-2A.'",
      ],
      ranks: [
        ["Contractor", "two crews and a van"],
        ["Crew Boss", "six crews"],
        ["Big Contractor", "the whole valley"],
        ["H-2A Recruiter", "workers from Mexico by contract"],
        ["Grower", "your own orchard"],
        ["Industry Voice", "the growers' association"],
      ],
      intro: [
        "You're Maribel Cruz. You supply crews to pear and apple orchards in the Hood River Valley.",
        "The lights on the wall are the workers and their families: pickers in the orchards, packers in the sheds, kids who work the harvest in the summer.",
        "The growers watch the price. There's a dial between paying the crews well and keeping your margin.",
        "The growers set the rate. You set what the crews get. The difference is your business.",
      ],
      introCta: "Load up the van ›",
      capture: "The orchards were picked on time. The crew worked through the heat wave, no shade breaks.",
      protect: "You paid above the rate and gave shade breaks. The growers said you were expensive.",
      outLabel: "FALLOUT THIS HARVEST",
      fired: "Someone else ran the crews anyway. What would have had to change for the people who pick the fruit to afford it?",
      ended: "Your business survived. What do the crews make now?",
      turns: [
        [2012, "GROWERS WANT A LOWER PER-BIN RATE", "Hold your rate", "Cut the pickers' pay to match"],
        [2014, "A NEW PIECE-RATE SYSTEM", "Guarantee minimum wage", "Pay only by the bin", "$"],
        [2016, "HOUSING FOR WORKERS IS FULL", "Rent better housing", "Put them in the old bunkhouse"],
        [2018, "THE H-2A GUEST WORKER PROGRAM EXPANDS", "Keep hiring locally", "Switch to H-2A; they can't quit", "✈"],
        [2020, "THE PANDEMIC · WORKERS SHARE HOUSING", "Pay for separate housing", "Keep the crews together", "✂"],
        [2021, "A HEAT WAVE · 115 DEGREES", "Stop the harvest at noon", "Keep picking; the fruit won't wait", "☀"],
        [2023, "A LAWSUIT OVER WAGE THEFT", "Settle and pay the workers", "Fight it; everybody does it", "§"],
      ],
    },
  }),

  life({
    id: "ut-mlm",
    protagonist: "Megan Christensen",
    dossierTag: "MLM DIAMOND LEADER",
    householdName: "The Christensens",
    location: "Lehi, UT",
    tagline: "Multilevel marketing leader, 32. Latter-day Saint. Four kids under eight. Her husband is a software engineer.",
    description:
      "Megan Christensen married young, had kids young, and joined a multilevel marketing company selling essential oils to make some money while staying home. She was good at it. Now she's a 'diamond,' with thousands of women in her downline. Her husband Ryan's startup salary pays the mortgage; her checks pay for everything else.",
    perspective:
      "It's about empowering women who want to stay home with their kids. It's a real opportunity. Some people do make money. If you work hard enough and believe in the product, you can succeed. I did.",
    closingAddendum:
      "You were dealt a way to earn from home in a place that honored staying home. It worked, for you. It was built on the thousands of women below you who paid in.",
    seat: {
      title: "The Leader",
      role: "Diamond Leader, MLM",
      color: "#BF5FBF",
      scoreLabel: "DOWNLINE VOLUME",
      dial: ["tell them the truth", "sell them the dream"],
      dialNote: "your check depends on what your downline buys",
      board: "UPLINE",
      firedTitle: "DEMOTED",
      firedBody:
        "Your volume dropped, and so did your rank. Your downline was absorbed by a leader in Provo who tells every new recruit they can make six figures in a year. They buy more starter kits.",
      pressure: [
        "Your upline says your team's volume is down. She wants a 'recommitment plan.'",
        "The company is changing the compensation plan. At your volume, you'll lose your rank.",
      ],
      ranks: [
        ["Leader", "a small downline"],
        ["Gold", "a trip to Hawaii"],
        ["Platinum", "a car allowance"],
        ["Diamond", "your photo at the convention"],
        ["Crown Diamond", "a speaking slot"],
        ["Royal Crown", "a mansion in Alpine"],
      ],
      intro: [
        "You're Megan Christensen. You sell essential oils through a multilevel marketing company. Your real money comes from recruiting other women to sell, too.",
        "The lights on the wall are your downline: moms in Utah, Idaho, and Arizona who believe what you told them.",
        "Your upline watches downline volume. There's a dial between telling them the truth and selling them the dream.",
        "The company's income disclosure says 99% of sellers make less than $1,000 a year. You don't mention it at the meetings.",
      ],
      introCta: "Open the team chat ›",
      capture: "Twelve new recruits bought starter kits. Your check was $14,000 this month.",
      protect: "You told a recruit the truth about the numbers. She didn't join. Your upline noticed.",
      outLabel: "FALLOUT THIS MONTH",
      fired: "Someone else recruited them anyway. What would have had to change for a woman at home to have a real way to earn?",
      ended: "You reached the top. How many women in your downline made money?",
      turns: [
        [2014, "A MOM IN YOUR WARD WANTS A SIDE INCOME", "Tell her the real numbers", "Tell her she could make six figures", "$"],
        [2016, "THE COMPANY RAISES THE MONTHLY PURCHASE MINIMUM", "Tell your downline to buy only what they sell", "Push them to meet the minimum"],
        [2018, "A RECRUIT'S GARAGE IS FULL OF UNSOLD PRODUCT", "Help her return it", "Tell her to recruit her way out"],
        [2019, "THE COMPANY CLAIMS THE OILS 'SUPPORT IMMUNITY'", "Don't repeat it", "Post it on your page"],
        [2020, "THE PANDEMIC · MOMS AT HOME NEED MONEY", "Warn them about the risks", "Recruit harder than ever", "$"],
        [2022, "A FORMER DOWNLINE MEMBER POSTS ABOUT HER DEBT", "Reach out and apologize", "Block her and call it 'negativity'"],
        [2024, "THE COMPANY LAUNCHES A NEW PRODUCT LINE", "Sit this one out", "Buy the top package to keep your rank", "$"],
      ],
    },
  }),

  life({
    id: "wa-detention",
    protagonist: "Jake Olson",
    dossierTag: "DETENTION OFFICER",
    householdName: "The Olsons",
    location: "Tacoma, WA",
    tagline: "Army veteran, 26. Detention officer at a private immigration facility. The pay is better than anything else he could find.",
    description:
      "Jake Olson grew up in Puyallup and enlisted at eighteen. He did a tour in Afghanistan and came home to Joint Base Lewis-McChord with a bad knee and a TBI diagnosis. The private company that runs the immigration detention center hired him fast. His girlfriend Ashley is pregnant with their first.",
    perspective:
      "I didn't make the immigration laws. People are here because the government says they have to be. My job is to keep them safe and keep order. It's a job, with benefits, and I've got a kid on the way.",
    closingAddendum:
      "You were dealt a veteran's return to a job market that had one opening for you. The company was paid by the bed, and you guarded the beds.",
    seat: {
      title: "The Officer",
      role: "Detention Officer",
      mode: "attn",
      color: "#5F5F8F",
      scoreLabel: "BEDS FILLED",
      dial: ["treat them as people", "run it by the contract"],
      dialNote: "the company is paid per bed per night",
      board: "FACILITY ADMIN",
      firedBody:
        "The facility administrator replaced you with an officer transferred from a facility in Texas. He enforced every rule to the letter, including the ones that meant solitary.",
      pressure: [
        "The facility administrator says your unit has too many 'accommodations' in the log.",
        "Corporate is reviewing staffing at the Tacoma facility. Your shift lieutenant says to 'watch it.'",
      ],
      ranks: [
        ["Officer", "a unit and a badge"],
        ["Sergeant", "the whole shift"],
        ["Lieutenant", "the facility's security"],
        ["Assistant Administrator", "the facility's operations"],
        ["Administrator", "the facility is yours"],
        ["Corporate", "an office at company HQ in Florida"],
      ],
      intro: [
        "You're Jake Olson. You work at a privately run immigration detention center in Tacoma. It holds 1,500 people.",
        "The lights on the wall are the detained and their families: asylum-seekers, people picked up at traffic stops, parents whose kids are waiting at home.",
        "The facility administrator watches the beds. There's a dial between treating them as people and running it by the contract.",
        "The company is paid for every bed filled every night. The contract has a minimum.",
      ],
      introCta: "Report for shift ›",
      actLabel: "ENFORCE",
      capture: "The unit ran by the book. A man on a hunger strike was moved to solitary.",
      protect: "You let a detainee call his kids after hours. The lieutenant wrote you up.",
      outLabel: "FALLOUT THIS SHIFT",
      fired: "Someone else ran it by the contract anyway. What would have had to change for detention not to be paid by the bed?",
      ended: "The beds stayed full. What happened to the people in them?",
      turns: [
        [2018, "DETAINEES WORK FOR $1 A DAY", "Report it to your lieutenant", "It's voluntary; don't ask"],
        [2019, "A HUNGER STRIKE IN YOUR UNIT", "Listen to their demands", "Move the leaders to solitary", "▣"],
        [2020, "THE PANDEMIC · COVID IN THE FACILITY", "Push for releases of the vulnerable", "Lock down the units", "▣"],
        [2021, "A STATE LAW BANS PRIVATE DETENTION", "Support it; find another job", "The company sues; stay on"],
        [2022, "A DETAINEE NEEDS MEDICAL CARE · THE CONTRACTOR DELAYS", "Call an ambulance yourself", "Follow the protocol; wait", "✂"],
        [2023, "A JOURNALIST ASKS YOU ABOUT CONDITIONS", "Tell the truth", "Refer her to corporate"],
        [2025, "THE FACILITY IS EXPANDING TO 3,000 BEDS", "Transfer out", "Take the promotion", "$"],
      ],
    },
  }),

  life({
    id: "wy-coal-bankruptcy",
    protagonist: "Curt Hansen",
    dossierTag: "MINE GENERAL MANAGER",
    householdName: "The Hansens",
    location: "Gillette, WY",
    tagline: "Coal mine general manager, 53. Thirty years at the mine. His son drives a haul truck.",
    description:
      "Curt Hansen grew up in Gillette when it was a boomtown. He started driving a haul truck at nineteen and worked his way up to general manager of one of the biggest coal mines in America. His wife Deb is a nurse. His son Colton drives a truck at the mine, the job Curt started in.",
    perspective:
      "Coal built this town and powered the country. We did our job. Now everybody says coal is dirty, and the company's in bankruptcy, and the people who made it rich are nowhere to be found. Somebody has to keep the lights on until the end.",
    closingAddendum:
      "You were dealt the mine that powered a country. When it went bankrupt, you were the one left deciding who got paid.",
    seat: {
      title: "The General Manager",
      role: "General Manager, Coal Mine",
      color: "#5F5F5F",
      scoreLabel: "TONS SHIPPED",
      dial: ["the workers and the land", "the creditors"],
      dialNote: "bankruptcy court puts the creditors first",
      board: "COURT",
      firedBody:
        "The bankruptcy court approved a new owner, a private equity firm from New York. It laid off a third of the workers and walked away from the reclamation bonds.",
      pressure: [
        "The creditors' committee says your mine's costs are 'unsustainable.'",
        "The bankruptcy judge is considering a sale to a private equity firm. They're touring your mine next week.",
      ],
      ranks: [
        ["General Manager", "a mine and 500 workers"],
        ["Regional VP", "three mines in the Powder River Basin"],
        ["COO", "the whole company's operations"],
        ["CEO", "the company, through bankruptcy"],
        ["Industry Board", "the coal association"],
        ["Buyer", "a stake in the new owner"],
      ],
      intro: [
        "You're Curt Hansen. The company that owns your mine just filed for bankruptcy. You're running it while the court decides who gets what.",
        "The lights on the wall are Gillette: miners and their families, retirees counting on pensions, and the land that the company promised to restore.",
        "The bankruptcy court watches the creditors. There's a dial between protecting the workers and the land and paying the creditors.",
        "The company promised to reclaim the land when the mining was done. That money is in the bankruptcy now too.",
      ],
      introCta: "Walk the pit ›",
      capture: "The creditors got paid. The retirees' health insurance was cut in half.",
      protect: "You fought to protect the pensions. The creditors' lawyers filed a motion against you.",
      outLabel: "FALLOUT THIS HEARING",
      fired: "The creditors got paid anyway. What would have had to change for workers to come first in a bankruptcy?",
      ended: "The mine is still running. Who's going to clean it up?",
      turns: [
        [2015, "THE COMPANY FILES FOR BANKRUPTCY", "Tell the workers the truth", "Say it's 'just a restructuring'"],
        [2016, "THE COURT APPROVES EXECUTIVE BONUSES", "Speak against them", "Stay quiet; take yours", "$"],
        [2017, "RETIREE HEALTH INSURANCE IS ON THE TABLE", "Fight to protect it", "Let it be cut", "✂"],
        [2019, "A SECOND BANKRUPTCY · PAYCHECKS BOUNCE", "Push the court to pay the miners first", "Follow the court's order of creditors", "✂"],
        [2020, "THE RECLAMATION BONDS ARE UNDERFUNDED", "Report it to the state", "Keep it quiet; it's legal"],
        [2022, "A PRIVATE EQUITY FIRM OFFERS TO BUY THE MINE", "Push for a buyer who'll keep the workers", "Support the highest bid", "$"],
        [2024, "THE MINE WILL CLOSE BY 2030", "Plan for the town's future", "Mine as fast as you can while it lasts", "⚙"],
      ],
    },
  }),
];
