import type { SeatPeople } from "./types";

export const HAND_BUILT_PEOPLE: SeatPeople = {
  supervisor: [
    ["the shift", "full-time with benefits", "hours cut to thirty-two", "a temp contract, renewed weekly", "let go for rate"],
    ["the back", "no complaints", "a brace under the vest", "pain pills to finish the shift", "can't work anymore"],
    ["the union talk", "signed a card", "keeps his head down", "afraid to be seen talking", "fired after the vote"],
    ["the house", "paid off since the mine", "a second mortgage", "behind on the taxes", "lost the house"],
    ["the kids", "one at Marshall on a scholarship", "stayed close to help out", "moved back in with their parents", "moved to Columbus for good"],
    ["the county", "the diner's still open", "Main Street half empty", "the school consolidated", "the town is hollowed out"],
  ],
  fleet: [
    ["the car", "owns it outright", "making the lease", "behind on the lease", "the car was repossessed"],
    ["the rating", "4.9 and steady", "slipping under the new rules", "one complaint from deactivation", "deactivated"],
    ["the hours", "drives when she wants", "fifty hours a week", "naps between shifts in the car", "living in the car"],
    ["the rent", "paid on the first", "paid late", "two months behind", "evicted"],
    ["the kids", "in the after-school program", "home alone after school", "the oldest works nights", "the oldest dropped out to drive"],
    ["the health", "insured through a spouse", "a plan with a huge deductible", "skips the doctor", "an ER bill in collections"],
  ],
  engineer: [
    ["the phone", "checks it a few times a day", "checks it every hour", "can't put it down", "lost to the feed"],
    ["the news", "reads the local paper", "gets it from the feed", "gets it from strangers' posts", "believes whatever goes viral"],
    ["the family table", "dinner without phones", "phones at the table", "everyone eats in separate rooms", "hasn't spoken to his brother since the election"],
    ["the kids", "outside after school", "on screens most evenings", "scrolling until 2 a.m.", "the daughter stopped eating"],
    ["the town meeting", "goes every month", "watches the stream", "only sees the angry clips", "thinks the council is out to get them"],
    ["the neighbors", "knows them by name", "waves from the driveway", "argues with them online", "blocked them all"],
  ],
  owner: [
    ["the furnace", "fixed right the first time", "upsold a new unit", "financed a unit they didn't need", "paying off a $14,000 unit on a card"],
    ["the job", "a Kellerman tech for ten years", "on commission now", "trapped by a non-compete", "left the trade"],
    ["the health plan", "the family plan", "a high deductible", "skips the checkups", "medical debt in collections"],
    ["the membership", "never needed one", "signed up at the door", "can't find how to cancel", "still paying for a house they sold"],
    ["the paycheck", "above market", "flat for three years", "picks up weekend calls", "working two jobs"],
    ["the service", "the local shop answers the phone", "the shop was bought out", "a call center in Arizona", "nobody comes out after dark anymore"],
  ],
  expert: [
    ["the hospital", "two to choose from", "one system now", "prices up a fifth", "skipped the surgery"],
    ["the flight home", "flies home for Christmas", "pays the hub premium", "drives eight hours instead", "hasn't seen family in three years"],
    ["the groceries", "a store in town", "the store changed its name", "prices up, shelves thinner", "the store closed; thirty miles to the next"],
    ["the job", "could switch across the street", "signed a non-compete", "stuck at the same wage", "can't take the better offer"],
    ["the seed", "four dealers to choose from", "two dealers left", "one price, take it or leave it", "sold the farm"],
    ["the budget", "comfortable", "watching every price", "choosing which bill to skip", "can't make it to the end of the month"],
  ],
  farmer: [
    ["the farm", "fourth generation, still farming", "renting out half", "farming the fund's ground", "sold at auction"],
    ["the co-op", "a member with a vote", "the elevator merged", "forty miles to deliver grain", "the co-op is gone"],
    ["the water", "clean from the well", "nitrates in the tap", "buying bottled water", "the well is unusable"],
    ["the school", "walks to school in town", "the school consolidated", "an hour each way on the bus", "the family moved to Mankato"],
    ["the church", "every Sunday, full pews", "every other Sunday", "shares a pastor with three towns", "the church closed"],
    ["the barn", "their own hogs", "contract hogs for the integrator", "the contract wasn't renewed", "the barn is empty and the loan isn't"],
  ],
  landlord: [
    ["the rent", "fair and steady", "up 10% this year", "half their income", "priced out"],
    ["the lease", "a long lease with a neighbor", "year to year", "cash for keys on the table", "evicted"],
    ["the commute", "walks to work", "a bus across town", "an hour from Antioch", "two hours from Stockton"],
    ["the kids' school", "the neighborhood school", "switched schools twice", "switched three times this year", "left the district"],
    ["the savings", "saving for a down payment", "savings going to rent", "no savings", "a payday loan for the deposit"],
    ["the block", "knows every family", "new faces every year", "short-term renters next door", "the block doesn't know them anymore"],
  ],
  trustee: [
    ["the store job", "a steady retail job", "hours cut after the buyout", "the store is closing", "the chain went bankrupt"],
    ["the nursing home", "Mom is well cared for", "one aide for twenty residents", "a bedsore nobody noticed", "Mom died alone on a short-staffed night"],
    ["the trailer lot", "lot rent they can afford", "lot rent up 20%", "lot rent up 60%", "sold the home for a dollar"],
    ["the paycheck", "a union wage", "wages frozen since the buyout", "a second job", "laid off when the debt came due"],
    ["the pension", "promised and paid", "frozen", "cut in bankruptcy", "gone"],
    ["the debt", "no debt", "a credit card", "a high-interest installment loan", "wages garnished"],
  ],
  council: [
    ["the air", "fresh off the river", "a smell at night", "an inhaler in every room", "cancer in the family"],
    ["the house", "held since 1870", "worth less every year", "a buyout offer on the table", "sold and gone"],
    ["the plant job", "a good job at the plant", "a contractor job", "laid off after the expansion", "no work that pays"],
    ["the school", "a good school", "the music program cut", "the school sits on the fence line", "the school closed"],
    ["the church", "the Friday fish fry", "half the parish moved", "services every other week", "the graveyard is behind a fence"],
    ["the storm", "power back in a day", "power back in a week", "three weeks in the dark", "never came home after the storm"],
  ],
  pastor: [
    ["Sunday", "sits with the same families every week", "watches from the overflow room", "watches the stream at home", "only sees the clips"],
    ["the neighbors", "brings a casserole", "waves from the truck", "suspicious of the new family", "won't speak to the family across the street"],
    ["the news", "reads the Times Daily", "hears it from church friends", "gets it from the Facebook group", "believes whatever the group shares"],
    ["the pantry", "volunteers every Tuesday", "donates at Christmas", "stopped volunteering", "the pantry lost its volunteers"],
    ["the family", "Thanksgiving together", "argues at Thanksgiving", "skipped Thanksgiving", "hasn't spoken to his sister in two years"],
    ["the vote", "reads both sides", "votes the way the church votes", "votes angry", "believes the election was stolen"],
  ],
  local: [
    ["the contract", "one tier, full scale", "the lower tier", "a contractor at half pay", "no contract at all"],
    ["the air", "fine most days", "flares at night", "an inhaler for the grandson", "cancer in the family"],
    ["the pension", "a full pension", "a 401(k) instead", "the plan was frozen", "no retirement"],
    ["the house", "paid off in Pasadena", "the value stalled", "flooded in the hurricane", "moved away from the fence line"],
    ["the job", "an operator for twenty years", "a turnaround contractor", "laid off in the downturn", "hurt on the job"],
    ["the school", "a good district", "the district lost the tax money", "portable classrooms", "the school cut its nurse"],
  ],
  mill: [
    ["the line", "a steady mill job", "short weeks", "the line moved to Mexico", "laid off when the mill closed"],
    ["the water", "clean from the tap", "a notice about 'forever chemicals'", "higher bills to filter it", "buying bottled water for the baby"],
    ["the wages", "overtime at Christmas", "no raise in years", "a labor contractor's rate", "cash wages, no papers, no rights"],
    ["the town", "stadium lights on Friday", "stores closing on Hamilton Street", "half the mills empty", "the town is hollowed out"],
    ["the health", "family insurance", "a high deductible", "worked sick through the outbreak", "no coverage"],
    ["the family", "three generations in Dalton", "the kids moved to Chattanooga", "the kids moved to Atlanta", "nobody left to stay"],
  ],
};
