import type { SeatPeople } from "./types";

export const MIDWEST_PEOPLE: SeatPeople = {
  "in-insulin": [
    ["the insulin", "covered, $25 a month", "a $300 vial with a deductible", "rationing to make it last", "died rationing insulin"],
    ["the insurance", "a good employer plan", "a high deductible", "between jobs, uninsured", "aged off a parent's plan"],
    ["the budget", "insulin is just another bill", "insulin before groceries", "insulin or rent", "can't afford either"],
    ["the pen", "a pen that works", "switched brands for the formulary", "switched back to the old vial", "no vial left to buy"],
    ["the trips", "a pharmacy down the street", "drives to Canada twice a year", "buys it from strangers online", "ran out"],
    ["the health", "blood sugar stable", "high more often than not", "in the ICU once", "kidney failure"],
  ],
  "ia-meatpacking": [
    ["the hands", "healthy", "sore at night", "carpal tunnel", "can't close them anymore"],
    ["the job", "fifteen years at the plant", "a new hire at the plant", "hurt and sent to the nurse", "fired after the injury"],
    ["the family", "together in Storm Lake", "a cousin detained in the raid", "a parent deported", "the kids live with an aunt now"],
    ["the housing", "a house on the east side", "an apartment, two families", "a trailer with six men", "no place to live"],
    ["the pandemic", "never got sick", "sick for two weeks", "sick and worked anyway", "died in the outbreak"],
    ["the union", "a union card", "went to the meeting", "afraid to sign", "fired for organizing"],
  ],
  "ks-tax-experiment": [
    ["the school", "a five-day week", "bigger classes", "a four-day week", "the district closed a school"],
    ["the road", "smooth", "potholes", "a bridge with a weight limit", "a detour for two years"],
    ["the paycheck", "a state job with a raise", "a state job, no raise", "hours cut", "laid off"],
    ["the taxes", "paying a fair share", "sales tax up", "property tax up", "paying more than the business owner next door"],
    ["the kids", "a good school, a good future", "fewer teachers", "no art or music", "moved to Missouri for the schools"],
    ["the hospital", "a hospital in town", "cuts at the hospital", "the ER closed at night", "the hospital closed"],
  ],
  "mi-flint": [
    ["the water", "clean from the tap", "smells strange", "brown from the tap", "lead in the blood"],
    ["the kids", "healthy", "rashes in the bath", "lead in their blood tests", "a child with lifelong damage"],
    ["the trust", "trusts the city", "doubts the city", "trusts no one in government", "believes nothing they're told"],
    ["the house", "a family home", "bills for water they can't drink", "a lien for unpaid water bills", "walked away from the house"],
    ["the bottled water", "never needed it", "cases from the fire station", "cases every week", "can't afford water anymore"],
    ["the town", "a proud Buick town", "half the people gone", "a city run by the state", "the town that was poisoned"],
  ],
  "mo-municipal-fines": [
    ["the ticket", "never been stopped", "a ticket, paid on time", "a ticket turned into $400", "a warrant for an unpaid ticket"],
    ["the court", "never been", "missed one date", "a failure-to-appear fee", "a weekend in jail"],
    ["the job", "steady work", "missed work for court", "lost a shift for court", "fired after the arrest"],
    ["the license", "a valid license", "suspended for unpaid fines", "driving without one", "no way to get to work"],
    ["the trust", "trusts the police", "avoids the police", "afraid of the police", "moved out of town"],
    ["the debt", "no fines", "a payment plan", "private probation fees", "owes more than they make in a month"],
  ],
  "ne-railroad": [
    ["the job", "railroader for twenty years", "a longer territory", "furloughed", "laid off"],
    ["the schedule", "home for dinner", "on call for twelve days straight", "no sick days", "missed the kid's birth"],
    ["the crossing", "trains pass in two minutes", "ten-minute waits", "blocked for forty minutes", "the ambulance couldn't get through"],
    ["the town", "the yard employs the town", "four hundred fewer jobs", "empty storefronts", "the town lost its railroad"],
    ["the safety", "every car inspected", "thirty seconds a car", "a derailment near town", "evacuated after the derailment"],
    ["the pension", "a railroad pension", "a smaller crew, a smaller pension", "retired early, hurt", "no pension, bought out"],
  ],
  "nd-oil-boom": [
    ["the rent", "$600 a month", "$1,500 a month", "$2,500 a month", "living in a camper in the Walmart lot"],
    ["the crew", "a safe crew", "sixteen-hour shifts", "hurt on the rig", "killed on the job"],
    ["the ranch", "cattle on clean grass", "a well pad in the pasture", "a saltwater spill", "the land is poisoned"],
    ["the town", "a quiet town of 12,000", "doubled overnight", "crime and traffic", "boom went bust"],
    ["the paycheck", "six figures", "overtime cut", "laid off in the crash", "no work, truck repossessed"],
    ["the family", "home every weekend", "home once a month", "divorced", "lost contact with the kids"],
  ],
  "sd-trusts": [
    ["the taxes", "paying a fair share", "paying more as the rich pay less", "the state leans on sales tax", "paying more than billionaires"],
    ["the public schools", "fully funded", "flat budgets", "cutting teachers", "the district closed a school"],
    ["the country the money left", "a functioning government", "tax revenue shrinking", "hospitals underfunded", "a clinic with no medicine"],
    ["the paycheck", "all theirs", "taxes on every dollar", "sales tax on groceries", "working two jobs to pay the difference"],
    ["the fairness", "believes the rules are fair", "suspects they're not", "knows they're not", "gave up on the system"],
    ["the town services", "a library open every day", "library hours cut", "the pool closed", "the town sold the pool"],
  ],
};
