import type { SeatPeople } from "./types";

export const SOUTH_PEOPLE: SeatPeople = {
  "ar-supplier": [
    ["the plant job", "full-time in Ohio", "four ten-hour shifts, no overtime", "the line moved to Vietnam", "laid off before Christmas"],
    ["the health plan", "a real family plan", "a $6,000 deductible", "skipped the surgery", "medical debt in collections"],
    ["the raise", "a raise every year", "frozen for two years", "a pay cut to keep the line", "no job to get a raise from"],
    ["the store", "shops at the supercenter", "counts every dollar there", "buys the store brand", "can't afford the $6.97 bin"],
    ["the town", "the plant sponsors Little League", "the plant cut its sponsorships", "the plant closed a building", "the town lost its plant"],
    ["the overtime", "overtime when they want it", "mandatory overtime", "seven days a week in summer", "burned out and quit"],
  ],
  "de-collections": [
    ["the card", "paid off monthly", "carrying a balance", "ninety days late", "charged off and sold"],
    ["the calls", "no calls", "a call a week", "calls every day at dinner", "stopped answering the phone"],
    ["the 401(k)", "growing", "borrowed against", "cashed out to pay the card", "empty"],
    ["the medical bill", "covered by insurance", "on a card at 29%", "sent to collections", "sued over it"],
    ["the credit score", "excellent", "fair", "poor", "ruined"],
    ["the paycheck", "all theirs", "stretched thin", "one bad month from falling behind", "garnished"],
  ],
  "fl-insurance": [
    ["the roof", "a new roof, fully covered", "patched after the storm", "a blue tarp for a year", "caved in"],
    ["the claim", "paid in six weeks", "paid in six months", "lowballed by the software", "denied as 'flood'"],
    ["the premium", "$2,000 a year", "$5,000 a year", "$11,000 a year", "dropped at renewal"],
    ["the house", "home, repaired", "living in half of it", "living with the daughter", "sold for the lot value"],
    ["the savings", "untouched", "spent on the deductible", "spent on the roof", "gone"],
    ["the lawsuit", "never needed one", "hired a public adjuster", "three years in court", "gave up and walked away"],
  ],
  "ky-pharmacy": [
    ["the prescription", "filled for a broken wrist, then stopped", "a refill every month", "running out early", "addicted"],
    ["the family", "Sunday dinner at Mamaw's", "worried about the son", "raising the grandkids", "buried a child"],
    ["the job", "working at the mine", "on disability for the back", "fired after a failed test", "can't pass a drug test"],
    ["the town", "the Main Street drugstore", "a pill mill in Corbin", "heroin on the east side", "the county leads the state in overdoses"],
    ["the naloxone", "never needed it", "keeps a kit in the truck", "used it on a neighbor", "no one had it in time"],
    ["the treatment", "clean for five years", "on a waiting list", "no clinic within fifty miles", "died waiting for a bed"],
  ],
  "md-contractor": [
    ["the school", "a new building", "the roof needs work", "the roof leaks into classrooms", "the school closed for repairs indefinitely"],
    ["the clinic", "open five days a week", "cut to three days", "a two-month wait", "the clinic closed"],
    ["the road", "freshly paved", "potholes", "a bridge with a weight limit", "the bridge was closed"],
    ["the soldier", "gear that works", "gear that half works", "a radio that failed in the field", "hurt when the system failed"],
    ["the taxes", "paying their share", "paying more for less", "the county cut services", "services gone, taxes the same"],
    ["the veteran", "a job after the Army", "waiting on the VA", "a claim denied", "on the street"],
  ],
  "ms-dollar-store": [
    ["the groceries", "a store with fresh food", "the dollar store and a weekly bus trip", "chips and canned goods", "eleven miles to a vegetable"],
    ["the formula", "on the shelf", "behind the counter", "the store ran out", "watered down to make it last"],
    ["the cashier's job", "full-time with sick days", "part-time, no sick days", "worked alone at night", "robbed at gunpoint and quit"],
    ["the health", "diabetes managed", "blood sugar high", "an amputation", "died of a stroke at fifty-one"],
    ["the prices", "fair prices", "smaller packages, same price", "prices up on what they need", "can't afford the basics"],
    ["the neighborhood", "a grocery, a pharmacy, a bank", "the grocery left", "the pharmacy left", "the dollar store is all that's left"],
  ],
  "nc-mortgages": [
    ["the mortgage", "a fixed rate they can afford", "an adjustable, still manageable", "the rate reset", "foreclosed"],
    ["the house", "a home of their own", "underwater", "behind on payments", "lost the house"],
    ["the loan", "prime, like they qualified for", "a teaser rate", "steered into subprime", "a loan they could never repay"],
    ["the neighborhood", "every house owned", "a few foreclosures", "boarded-up houses", "a fund owns the whole street"],
    ["the savings", "a down payment saved", "savings into the house", "savings gone to the payment", "bankruptcy"],
    ["the rent", "never rented again", "renting a house they used to own", "rent up 40%", "renting a room"],
  ],
  "sc-heirs-property": [
    ["the land", "held by the family since 1868", "a cousin sold a share", "a developer owns a piece", "sold at partition auction"],
    ["the taxes", "paid every year", "tripled after reassessment", "behind on the taxes", "lost it at tax sale"],
    ["the cemetery", "tended every spring", "a road runs past it", "behind a developer's gate", "the graves were moved"],
    ["the family", "the cousins gather in July", "the cousins argue about selling", "the cousins voted to sell", "the family scattered"],
    ["the creek", "fishing and crabbing", "posted 'private'", "fenced for the resort", "no access to the water"],
    ["the island", "neighbors who've been here forever", "new houses, new faces", "gated communities", "priced off the island"],
  ],
  "tn-hospital-billing": [
    ["the bill", "covered by insurance", "a surprise bill from a doctor they never chose", "sent to collections", "sued over it"],
    ["charity care", "qualified and approved", "qualified, never told", "applied, lost in paperwork", "never knew it existed"],
    ["the paycheck", "all theirs", "a payment plan", "garnished", "lost the job over the court date"],
    ["the doctor", "goes when sick", "waits until it's bad", "avoids the hospital", "died at home rather than go back"],
    ["the credit", "good credit", "a medical collection", "ruined credit", "can't rent an apartment"],
    ["the price", "knew the price up front", "a posted price nobody could read", "billed the chargemaster rate", "billed triple for being uninsured"],
  ],
  "va-data-centers": [
    ["the power bill", "$150 a month", "$200 a month", "$280 a month", "can't keep the lights on"],
    ["the view", "fields out the window", "a data center across the road", "transmission towers over the yard", "moved away"],
    ["the sound", "quiet nights", "a hum at night", "a hum all the time", "can't sleep"],
    ["the water", "plenty in the reservoir", "asked to conserve", "watering restrictions", "the well ran dry"],
    ["the community", "a historic Black community, intact", "a data center next to the church", "the cemetery surrounded", "the community rezoned away"],
    ["the house value", "rising", "flat", "falling near the lines", "sold at a loss"],
  ],
};
