import type { SeatPeople } from "./types";

export const WEST_PEOPLE: SeatPeople = {
  "ak-native-corporation": [
    ["the salmon", "a full smokehouse", "a thin run", "fishing closed", "an empty smokehouse all winter"],
    ["the river", "clean water upstream", "a mine road upstream", "tailings upstream", "can't trust the river"],
    ["the heating oil", "a full tank", "$12 a gallon", "rationing it", "a cold house in January"],
    ["the dividend", "a check that helps", "a smaller check", "the check went to the mine", "the check is all that's left"],
    ["the village", "everyone speaks Yup'ik at home", "the young people moving to Anchorage", "the school down to eleven kids", "the village is emptying"],
    ["the caribou", "the herd comes through every fall", "the herd changed its path", "a long trip to hunt", "no caribou this year"],
  ],
  "co-prison-town": [
    ["the sentence", "home on schedule", "a write-up, time added", "parole date lost", "sixty days in solitary"],
    ["the family visit", "every Saturday", "once a month", "phone calls at $15 each", "no contact in a year"],
    ["the GED", "earned it inside", "enrolled, classes cut", "on a waiting list", "no classes at all"],
    ["the kids", "visit their dad often", "visit on holidays", "can't afford the drive", "haven't seen him in years"],
    ["coming home", "a job and a place to stay", "a halfway house", "no job, no vote", "back inside in a year"],
    ["the guard's job", "a state job with a pension", "mandatory overtime", "burned out", "moved to the private prison at less pay"],
  ],
  "hi-resort": [
    ["the taro", "the patch runs full", "the stream runs low", "the stream is dry in summer", "the patch is abandoned"],
    ["the housing", "a family home in Lahaina", "rent up by half", "two families in one house", "moved to Las Vegas"],
    ["the job", "a resort job with a union", "hours cut after the shutdown", "laid off", "no work on the island"],
    ["the commute", "walks to work", "forty minutes each way", "two hours each way", "gave up the job"],
    ["the fire", "the house survived", "the house burned; insurance paid", "living in a hotel room", "the lot sold to an investor"],
    ["the island", "home, as it always was", "more visitors than neighbors", "a stranger in their own town", "left the island for good"],
  ],
  "id-talk-radio": [
    ["the radio", "listens for the weather", "listens every morning", "angry after every show", "only trusts the show"],
    ["the library", "checks out books every week", "worried about the board fight", "stopped going", "the library lost its levy"],
    ["the doctor", "trusts the local doctor", "skeptical of the health board", "refused the vaccine", "died of COVID in the ICU"],
    ["the neighbors", "helps them with their fence", "argues about politics", "stopped speaking", "reported them to the sheriff"],
    ["the school board", "goes to the meetings", "watches the clips", "shouts at the meetings", "the board member moved away"],
    ["the baby", "delivered at the county hospital", "a longer drive to deliver", "ninety minutes to the nearest OB", "delivered on the highway"],
  ],
  "mt-coal-lease": [
    ["the job", "a mine job with good pay", "hours cut", "laid off", "no work on the reservation"],
    ["the per capita check", "a check that helps", "a smaller check", "the check was cut", "no check this year"],
    ["the land", "sacred sites protected", "a mine near the sites", "a burial ground in the pit", "the land is dug up"],
    ["the tribal services", "a full clinic and police", "cuts to the clinic", "six officers laid off", "services closed"],
    ["the language", "speaks Crow at home", "the grandkids understand it", "the grandkids don't speak it", "the last fluent speaker in the family died"],
    ["the future", "a plan after coal", "a solar lease", "waiting on the grant", "no plan, no coal"],
  ],
  "nv-sportsbook": [
    ["the bets", "plays for fun on birthdays", "a weekly habit", "chasing losses", "lost everything to the app"],
    ["the savings", "untouched", "dipped into", "the retirement account is gone", "borrowed against the house"],
    ["the sleep", "in bed by eleven", "betting at midnight", "betting at 2 a.m.", "never sleeps"],
    ["the family", "they know about the bets", "they're worried", "they found out about the debt", "the marriage ended"],
    ["the job", "at work on time", "distracted at work", "missing shifts", "fired"],
    ["the self-exclusion", "never needed it", "thought about it", "signed up, came back", "the app found a way around it"],
  ],
  "nm-state-land": [
    ["the air", "clear most days", "flares at night", "an inhaler at school", "asthma attacks all year"],
    ["the school", "fully funded by oil money", "funded, but next to a well", "the budget crashed with prices", "the school closed a wing"],
    ["the job", "an oilfield job", "a contractor at half the pay", "laid off in the bust", "no work in the Permian"],
    ["the water", "clean from the well", "tastes wrong", "contaminated", "hauling water"],
    ["the land", "family grazing land", "a pad on the lease next door", "the land is scarred", "sold to the operator"],
    ["the sacred sites", "Chaco protected", "drilling within view", "the road runs past the ruins", "the sites are surrounded"],
  ],
  "or-labor-contractor": [
    ["the pay", "an hourly wage", "piece rate", "$6 an hour on a slow day", "wages stolen"],
    ["the housing", "a clean cabin", "a crowded bunkhouse", "twelve men, one bathroom", "sleeping in the car"],
    ["the heat", "shade breaks at noon", "working through the heat", "heat exhaustion", "collapsed in the rows"],
    ["the visa", "a green card", "an H-2A visa, tied to one grower", "owes the recruiter back home", "can't quit, can't leave"],
    ["the kids", "in school in Hood River", "work the harvest in summer", "out of school to work", "left school for good"],
    ["the health", "healthy", "back pain from the ladders", "sick in the pandemic", "no care, no coverage"],
  ],
  "ut-mlm": [
    ["the business", "sells what she buys", "buying to hit the minimum", "a garage full of oils", "quit owing $8,000"],
    ["the credit card", "paid off", "a balance for the starter kit", "maxed out", "in collections"],
    ["the friendships", "friends from the ward", "friends are 'leads'", "friends stopped answering", "no friends left who don't sell"],
    ["the marriage", "a partner who supports her", "arguments about money", "hid the debt", "divorced over the debt"],
    ["the health", "trusts her doctor", "trusts the oils for colds", "skipped the doctor for the oils", "an untreated illness"],
    ["the dream", "saw through it early", "still believes", "recruited her sister", "blames herself"],
  ],
  "wa-detention": [
    ["the case", "released on bond", "waiting on a hearing", "months in detention", "deported"],
    ["the family", "visits every week", "phone calls only", "the kids haven't seen him in months", "the family was separated"],
    ["the medical care", "seen quickly", "waited days", "waited nine hours in pain", "died in custody"],
    ["the work", "no work", "works for $1 a day", "on a hunger strike", "in solitary"],
    ["the lawyer", "a lawyer from day one", "a volunteer lawyer, sometimes", "no lawyer at the hearing", "deported without seeing one"],
    ["the kids at home", "with the other parent", "with an aunt", "in foster care", "lost track of their father"],
  ],
  "wy-coal-bankruptcy": [
    ["the job", "hauling coal for twenty years", "hours cut", "the paycheck bounced", "laid off in the sale"],
    ["the pension", "a promised pension", "reduced in bankruptcy", "frozen", "gone"],
    ["the health coverage", "full coverage for the retiree", "cut in half", "lost it", "black lung and no coverage"],
    ["the house", "paid off in Gillette", "worth less every year", "for sale, no buyers", "walked away from the house"],
    ["the land", "reclaimed and grazed again", "reclamation on hold", "an open pit next door", "the pit will stay forever"],
    ["the town", "a boomtown", "empty storefronts", "the school lost students", "the town is shrinking"],
  ],
};
