import type { SeatConfig, SeatTurn } from "../types";
import { CIV_LIVES, ECON_LIVES } from "../constants";

const WARM = "#E8A24A";
const EMBER = "#F2C46D";

function turn(y: number, ch: string, protect: [string, number], capture: [string, number], glyph = "$"): SeatTurn {
  return {
    y,
    ch,
    o: [
      { id: "a", name: protect[0], glyph: "◍", type: "protect", pull: protect[1] },
      { id: "b", name: capture[0], glyph, type: "capture", pull: capture[1] },
    ],
  };
}

export const SUPERVISOR: SeatConfig = {
  id: "supervisor",
  title: "The Shift Supervisor",
  role: "Shift Supervisor",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#C9853F",
  litColor: WARM,
  scoreLabel: "UNITS PER HOUR",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["protect the crew", "hit the rate"],
  dialNote: "the rate only goes one direction",
  archetype: "the local man handed the quota",
  boardLabel: "DISTRICT",
  firedBody:
    "District brought in a supervisor from the Charleston site who hit the rate in a month. Your crew got the same quotas, from someone who didn't know their names.",
  boardPressure: [
    "District flagged your building's rate on the regional call.",
    "Your district manager is driving down Thursday. Nobody drives down on good news.",
  ],
  ranks: [
    { title: "Shift Supervisor", perk: "a radio and a clipboard" },
    { title: "Area Manager", perk: "salaried, no more overtime" },
    { title: "Operations Manager", perk: "a parking spot by the door" },
    { title: "Site Leader", perk: "stock grants" },
    { title: "Regional Director", perk: "three buildings, two states" },
    { title: "VP, Fulfillment", perk: "they fly you to headquarters" },
  ],
  intro: [
    "You're Roger Morrison. Four years after the mine closed, the distribution center on Route 52 is the best job in the county — and they've made you shift supervisor.",
    "The lights on the wall are the people on your shifts and the families behind them. Your neighbors. Your church. Men you worked underground with.",
    "District gives you one number: units per hour. There's a dial between protecting the crew and hitting the rate. District watches the rate.",
    "Nobody here will complain out loud. They need this job more than you do. That's what makes it work.",
  ],
  actLabel: "DECIDE",
  introCta: "Clock in ›",
  resultCapture: "The rate climbed. District sent a congratulations email. Two more guys didn't come back after break.",
  resultProtect: "The crew noticed. So did the dashboard. Your building was bottom of the region.",
  outLabel: "FALLOUT THIS SHIFT",
  closingQuestion: {
    fired: "They replaced you with someone who hit the rate. What would have had to change for the rate not to be the only number?",
    ended: "The rate went up every year. Is the county better off than when the mine closed?",
  },
  turns: [
    turn(2017, "THE CENTER OPENS · 400 JOBS FOR A COUNTY THAT LOST 3,000", ["Hire the older miners, train them right", 0.26], ["Hire through the temp agency — cheaper", 0.55]),
    turn(2018, "THE RATE GOES UP 8% · NOBODY ASKED THE FLOOR", ["Push back on district", 0.3], ["Post the leaderboard by the time clock", 0.68], "⚙"),
    turn(2019, "UNION CARDS IN THE BREAK ROOM", ["Stay out of it", 0.3], ["Forward the names to HR", 0.76], "✂"),
    turn(2020, "THE PANDEMIC SURGE · MANDATORY OVERTIME", ["Cap the hours, rotate the crews", 0.3], ["Sixty-hour weeks; hazard pay ends in June", 0.82]),
    turn(2021, "A BACK INJURY ON LINE 4", ["Report it as a workplace injury", 0.32], ["On-site clinic, keep it off the books", 0.86], "✂"),
    turn(2022, "THE ROBOTS ARRIVE · HALF THE PICKERS ARE 'REDEPLOYED'", ["Fight to retrain them", 0.3], ["Pick who goes, by rate", 0.9], "⚙"),
    turn(2024, "THE CENTER MIGHT CLOSE · THE COUNTY OFFERS A TAX BREAK TO STAY", ["Tell the county to let them go", 0.32], ["Testify for the tax break; the school levy gets cut", 0.92]),
  ],
};

export const FLEET: SeatConfig = {
  id: "fleet",
  title: "The Fleet Partner",
  role: "Fleet Partner",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#3FA7A0",
  litColor: WARM,
  scoreLabel: "FLEET REVENUE",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["fair terms", "squeeze the lease"],
  dialNote: "the app takes its cut first; you take yours second",
  archetype: "the driver who got out of the driver's seat",
  boardLabel: "PLATFORM",
  firedBody:
    "The platform reassigned your drivers to a fleet company out of Scottsdale with two hundred cars and no idea anyone's name. The terms got worse. The cars stayed on the road.",
  boardPressure: [
    "The platform moved you down a partner tier. Fewer rides are routed to your fleet.",
    "The app emailed: partners below target will be 'transitioned' at quarter end.",
  ],
  ranks: [
    { title: "Fleet Partner", perk: "two cars and a spreadsheet" },
    { title: "Top Partner", perk: "a badge on the app" },
    { title: "Fleet Owner", perk: "an LLC and an accountant" },
    { title: "Platinum Partner", perk: "the app returns your calls" },
    { title: "Regional Fleet", perk: "forty cars, three cities" },
    { title: "The Ad", perk: "they put you in the commercial about 'opportunity'" },
  ],
  intro: [
    "You're Maria Flores-Garcia. Four years of driving, a 4.97 rating, and the app just offered you a way out of the driver's seat: become a fleet partner.",
    "You lease cars to other drivers — people exactly like you were — and take a cut of every fare they drive.",
    "The platform ranks its partners. Fall behind and your drivers get reassigned to someone else. There's a dial between fair terms and squeezing the lease.",
    "The drivers on the wall are your cousins, friends from church, strangers from the Facebook group. They'll sign whatever you put in front of them. They need the car.",
  ],
  actLabel: "DECIDE",
  introCta: "Log in as a partner ›",
  resultCapture: "Revenue up. One of your drivers is sleeping in the car now — but he's driving.",
  resultProtect: "Your drivers were grateful. The platform dashboard was not.",
  outLabel: "FALLOUT THIS MONTH",
  closingQuestion: {
    fired: "Someone with more cars took your drivers. What would have had to change for the lease not to be the business?",
    ended: "You got out of the driver's seat. How many people did it take to hold it for you?",
  },
  turns: [
    turn(2019, "THE APP OFFERS FLEET PARTNER STATUS", ["Lease two cars at cost to your cousins", 0.26], ["Sign up ten drivers for the referral bonus", 0.55]),
    turn(2020, "THE PANDEMIC · RIDES DROP 70%", ["Pause the lease payments", 0.3], ["Payments due Friday, same as always", 0.7]),
    turn(2020, "A STATE BILL · DRIVERS ARE CONTRACTORS FOREVER", ["Tell your drivers what it takes from them", 0.3], ["Put the app's flyer in every car", 0.76], "⚡"),
    turn(2021, "GAS HITS FIVE DOLLARS", ["Eat the fuel surcharge", 0.3], ["Pass it all to the drivers", 0.8]),
    turn(2022, "A DRIVER IS DEACTIVATED · NO REASON GIVEN", ["Fight the app for her", 0.32], ["Give her car to the next name on the list", 0.84], "✂"),
    turn(2023, "THE LEASE TERMS ARE UP FOR RENEWAL", ["Write a path to ownership into the contract", 0.3], ["Add a mileage cap and a damage fee", 0.9]),
    turn(2024, "THE APP CUTS DRIVER PAY 15% · THE FLEET SHARE IS UNCHANGED", ["Stop recruiting until it's reversed", 0.32], ["Recruit harder — there's always someone newer", 0.93]),
  ],
};

export const ENGINEER: SeatConfig = {
  id: "engineer",
  title: "The Engineer",
  role: "Senior Engineer, Growth",
  mode: "attn",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#9B7FD9",
  litColor: EMBER,
  scoreLabel: "ENGAGEMENT",
  litLabel: "still reads past the headline",
  lives: CIV_LIVES,
  dial: ["ship it clean", "optimize for time spent"],
  dialNote: "the metric is minutes, not meaning",
  archetype: "the engineer who only ever shipped what the metric asked for",
  boardLabel: "REVIEW",
  firedTitle: "REORGED OUT",
  firedBody:
    "Your review said 'lacks impact.' They moved you off Growth and gave your roadmap to a new grad who shipped all of it in a quarter. The feed got stickier without you.",
  boardPressure: [
    "Your manager asked why your launch moved the metric less than forecast.",
    "Calibration is next week. Your manager says your 'impact narrative' needs work.",
  ],
  ranks: [
    { title: "Senior Engineer", perk: "RSUs, vesting quarterly" },
    { title: "Staff Engineer", perk: "your name on the launch memo" },
    { title: "Principal", perk: "a seat in the metrics review" },
    { title: "Director, Growth", perk: "your own org" },
    { title: "VP Engineering", perk: "the stock is your net worth now" },
    { title: "Keynote", perk: "you explain 'connection' on stage" },
  ],
  intro: [
    "You're David Nguyen. Senior engineer on the Growth team at a social platform with two billion users. The kids are asleep upstairs; the laptop is open.",
    "The lights on the wall are users — a small town's worth of them. The PTA chair, the retiree who reads every notice, the teenager up past midnight.",
    "Your review is graded on one number: engagement. There's a dial between shipping it clean and optimizing for time spent.",
    "Nothing you ship hurts anyone on the day it ships. The civic numbers show up next quarter — if anyone measures them.",
  ],
  actLabel: "DECIDE",
  introCta: "Open the laptop ›",
  resultCapture: "Time spent up 4%. The launch post got a thousand emoji reacts. Somewhere a town meeting had eleven people.",
  resultProtect: "Engineering-wise, beautiful. The metric was flat, and the review cycle noticed.",
  outLabel: "FALLOUT THIS CYCLE",
  closingQuestion: {
    fired: "The roadmap shipped without you. What would have had to change for time spent not to be the goal?",
    ended: "Every launch hit its number. What did the people on the wall stop doing with the hours you won?",
  },
  turns: [
    turn(2012, "MOBILE IS EVERYTHING · MAKE THE FEED STICKY", ["Chronological feed, a clear stopping point", 0.26], ["Infinite scroll", 0.55], "∞"),
    turn(2014, "NOTIFICATIONS DRIVE RETURN VISITS", ["Notify only on real messages", 0.3], ["Red badges for everything", 0.68], "●"),
    turn(2016, "OUTRAGE GETS 6× THE SHARES · THE DATA IS CLEAR", ["Downrank rage bait, eat the dip", 0.3], ["Rank by reactions — all of them", 0.8], "⚡"),
    turn(2018, "AN INTERNAL STUDY · TEENS FEEL WORSE AFTER USING IT", ["Take it to leadership, in writing", 0.32], ["Nobody asked you to read that deck", 0.84], "●"),
    turn(2020, "THE ELECTION INTEGRITY TEAM IS DISSOLVED", ["Volunteer to keep the guardrails running", 0.3], ["Join the new team — it's a promotion", 0.88], "⚡"),
    turn(2022, "SHORT VIDEO IS EATING OUR LUNCH", ["Keep friends and family at the center", 0.3], ["Autoplay strangers, forever", 0.9], "∞"),
    turn(2024, "AI CONTENT IS CHEAPER THAN PEOPLE", ["Label it, limit it", 0.32], ["Flood the feed — the metric can't tell", 0.93], "⚙"),
  ],
};

export const OWNER: SeatConfig = {
  id: "owner",
  title: "The Owner",
  role: "CEO, Kellerman Heating & Air",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#46B17F",
  litColor: WARM,
  scoreLabel: "MARGIN",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["run it for the people", "run it for the multiple"],
  dialNote: "the buyer pays for margin, not loyalty",
  archetype: "the founder who became a platform company",
  boardLabel: "LENDER",
  firedTitle: "BOUGHT OUT",
  firedBody:
    "The bank called the note. The firm bought the company out of the wreckage at half the multiple, put a new logo on your father's vans, and did everything you wouldn't — the same year.",
  boardPressure: [
    "Your banker asked to 'grab coffee.' It was not about coffee.",
    "The line of credit is under review. The firm's number is on your desk.",
  ],
  ranks: [
    { title: "Owner", perk: "four vans and a line of credit" },
    { title: "Founder-CEO", perk: "a logo someone else designed" },
    { title: "Platform CEO", perk: "three acquired shops" },
    { title: "Regional CEO", perk: "the roll-up's poster company" },
    { title: "Operating Partner", perk: "equity in the fund" },
    { title: "Exited", perk: "a lake house and a nondisclosure" },
  ],
  intro: [
    "You're Sandra Kellerman. Twenty years, seven employees, four vans with your father's name on the side. It's a real company now, and you're its CEO.",
    "The lights on the wall are your crew, your customers, and the families who've called you at 2am when the furnace quit.",
    "The bank that holds your line of credit watches one number: margin. There's a dial between running it for the people and running it for the multiple.",
    "A private equity firm has been buying up HVAC shops across Oklahoma. They've already called twice.",
  ],
  actLabel: "DECIDE",
  introCta: "Unlock the shop ›",
  resultCapture: "Margin up. The firm sent a bottle of scotch. Mrs. Alvarez paid $14,000 for a unit that needed a $300 part.",
  resultProtect: "The crew stayed loyal. The bank read the margin and frowned.",
  outLabel: "FALLOUT THIS QUARTER",
  closingQuestion: {
    fired: "Someone else bought the vans and did it anyway. What would have had to change for you to stay small and survive?",
    ended: "You built something and sold it for what it was worth. What was it worth to the people who worked there?",
  },
  turns: [
    turn(2015, "A PRIVATE EQUITY FIRM IS ROLLING UP HVAC IN OKLAHOMA", ["Stay independent", 0.26], ["Take their 'growth partnership' money", 0.55]),
    turn(2016, "THE NEW PARTNERS WANT A SALES QUOTA FOR TECHS", ["Techs fix what's broken, nothing more", 0.3], ["Commission on every replacement sold", 0.7]),
    turn(2018, "THE HEALTH PLAN RENEWAL IS UP 31%", ["Absorb it, keep the family plan", 0.3], ["Switch everyone to a high-deductible plan", 0.76], "✂"),
    turn(2020, "THE PANDEMIC · A LOAN THAT BECOMES A GIFT", ["Spend it on payroll, like it says", 0.3], ["Payroll on paper; pay down the debt", 0.8]),
    turn(2021, "A NON-COMPETE FOR EVERY TECH", ["They can work wherever they want", 0.32], ["Two years, fifty miles — sign or go", 0.84], "✂"),
    turn(2022, "THE FIRM WANTS A 'MAINTENANCE MEMBERSHIP' PROGRAM", ["Keep it simple: fix-it pricing", 0.3], ["Auto-renew, hard to cancel", 0.88]),
    turn(2023, "THE FIRM OFFERS TO BUY YOU OUT AT 9× EARNINGS", ["Sell to your employees instead", 0.32], ["Take the check", 0.93]),
  ],
};

export const EXPERT: SeatConfig = {
  id: "expert",
  title: "The Expert Witness",
  role: "Consulting Economist",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#6FA8C9",
  litColor: WARM,
  scoreLabel: "MARKET POWER",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["what the data says", "what the client needs"],
  dialNote: "the firm keeps the experts who win",
  archetype: "the scholar whose model became the industry standard",
  boardLabel: "THE FIRM",
  firedTitle: "OFF THE CASE",
  firedBody:
    "You lost a case the firm needed. They brought in an economist from Chicago whose reports never lose. The mergers went through on schedule.",
  boardPressure: [
    "A partner mentioned that the client 'expected a cleaner report.'",
    "The firm is 'reviewing staffing' on the next engagement. Your name isn't on the list yet.",
  ],
  ranks: [
    { title: "Consultant", perk: "$650 an hour" },
    { title: "Senior Consultant", perk: "your own research team" },
    { title: "Affiliated Expert", perk: "your name on the letterhead" },
    { title: "Principal", perk: "clients ask for you by name" },
    { title: "Testifying Expert", perk: "your model is the industry standard" },
    { title: "Endowed Chair", perk: "named for a client's founder" },
  ],
  intro: [
    "You're Amara Okafor-Walker. Seventh semester on a one-semester contract. Then an email from an economic consulting firm: $650 an hour to write expert reports.",
    "The work is antitrust. When two companies merge, someone has to tell the court whether prices will go up. Your clients pay you to say no.",
    "The firm keeps you on as long as you keep winning. There's a dial between writing what the data says and writing what the client needs.",
    "The lights on the wall are the people who'll pay the prices. They'll never read your report. It will be cited for twenty years.",
  ],
  actLabel: "DECIDE",
  introCta: "Open the data room ›",
  resultCapture: "The merger cleared. Your report was cited in the ruling. Prices at the county's only hospital rose 22%.",
  resultProtect: "The report was honest. The client was not pleased. The firm noticed.",
  outLabel: "FALLOUT THIS CASE",
  closingQuestion: {
    fired: "Another expert wrote what the client needed. What would have had to change for honest analysis to be the kind that pays?",
    ended: "You finally got the job the credential promised. Whose prices paid for it?",
  },
  turns: [
    turn(2014, "A HOSPITAL MERGER · THE ONLY TWO IN THE COUNTY", ["Report what the model shows", 0.26], ["Define the market as the whole state", 0.55], "§"),
    turn(2015, "TWO AIRLINES · ONE HUB", ["Flag the fare increase", 0.3], ["'Efficiencies will be passed to consumers'", 0.68], "§"),
    turn(2017, "A SEED AND CHEMICAL MEGAMERGER", ["Testify to what the farmers told you", 0.3], ["Innovation requires scale", 0.76], "§"),
    turn(2018, "THE UNIVERSITY OFFERS TENURE TRACK · AT A THIRD THE PAY", ["Take the job, teach it straight", 0.32], ["Stay at the firm; keep a courtesy title for credibility", 0.8]),
    turn(2019, "NON-COMPETES FOR FAST-FOOD WORKERS", ["Write that they suppress wages", 0.3], ["Write that they protect training investment", 0.84], "§"),
    turn(2021, "A GROCERY CHAIN BUYS ITS RIVAL", ["Name the towns that lose their only store", 0.3], ["Divest twelve stores, call it remedied", 0.88], "§"),
    turn(2023, "PRICES ARE UP · CONGRESS WANTS AN EXPERT", ["Testify that concentration matters", 0.32], ["Testify that it's all supply chains", 0.93], "§"),
  ],
};

export const FARMER: SeatConfig = {
  id: "farmer",
  title: "The Farmer",
  role: "Fourth-Generation Farmer",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#B5A642",
  litColor: WARM,
  scoreLabel: "LAND CONTROLLED",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["farm like a neighbor", "farm like a fund"],
  dialNote: "get big or get out",
  archetype: "the family farm that became an operation",
  boardLabel: "THE BANK",
  firedTitle: "FORECLOSED",
  firedBody:
    "The bank didn't renew the operating loan. The land went at auction to the operation across the road — the one that already farms nine thousand acres. They tore out the windbreak your grandfather planted.",
  boardPressure: [
    "Your loan officer mentioned your 'growth trajectory' twice in one meeting.",
    "The bank wants a meeting before spring planting. They sent the paperwork ahead.",
  ],
  ranks: [
    { title: "Family Farm", perk: "a section and a note" },
    { title: "Growing Operation", perk: "a new combine" },
    { title: "Large Operation", perk: "3,000 acres, some rented" },
    { title: "Farm Bureau Board", perk: "a voice in St. Paul" },
    { title: "Mega-Farm", perk: "10,000 acres, GPS-steered" },
    { title: "Ag Investor", perk: "the land is a line in a portfolio" },
  ],
  intro: [
    "You're Dale Pedersen. Fourth generation on the same section outside Mankato. The note comes due in February, like it always does.",
    "The lights on the wall are the county: neighbors, the co-op, the Lutheran church, the school that has consolidated twice.",
    "The ag lender reads one number: whether you're growing. There's a dial between farming like a neighbor and farming like a fund.",
    "Every acre you add was someone else's. That's how farming has worked for fifty years. Nobody decided it.",
  ],
  actLabel: "DECIDE",
  introCta: "Head out to the field ›",
  resultCapture: "The operation grew. The school merged again. The church moved to every other Sunday.",
  resultProtect: "Your neighbors kept their ground another year. The bank flagged your numbers.",
  outLabel: "FALLOUT THIS SEASON",
  closingQuestion: {
    fired: "Someone bigger farmed it anyway. What would have had to change for a section to be enough?",
    ended: "You held the land. How many farms did it take to hold it?",
  },
  turns: [
    turn(1998, "HOG PRICES CRASH · THE NEIGHBOR'S FARM GOES TO AUCTION", ["Let the young couple outbid you", 0.26], ["Buy it on the courthouse steps", 0.55]),
    turn(2002, "THE INTEGRATOR OFFERS A CONTRACT · THEIR PIGS, YOUR BARN", ["Stay independent", 0.3], ["Sign, build the barn, take the debt", 0.68]),
    turn(2006, "ETHANOL · CORN GOES TO $4", ["Keep the rotation, keep the soil", 0.3], ["Corn on corn, tile every acre", 0.76], "⚙"),
    turn(2012, "A PENSION FUND WANTS FARMLAND IN BLUE EARTH COUNTY", ["Sell only to farmers", 0.32], ["Farm the fund's ground for cash rent", 0.8]),
    turn(2016, "THE CO-OP VOTES ON A MERGER", ["Vote to stay local", 0.3], ["Vote for the merger — it's more efficient", 0.84]),
    turn(2019, "THE TRADE WAR · A BAILOUT CHECK, SIZED BY ACRES", ["Push for a cap on the payments", 0.3], ["Take the biggest check in the township", 0.88]),
    turn(2023, "YOUR SON WANTS TO FARM · A FUND WANTS THE WHOLE SECTION", ["Sell to your son on a contract for deed", 0.32], ["Sell to the fund; they'll rent it back", 0.93]),
  ],
};

export const LANDLORD: SeatConfig = {
  id: "landlord",
  title: "The Landlord",
  role: "Landlord",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#C96F8F",
  litColor: WARM,
  scoreLabel: "RENT ROLL",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["rent a neighbor can pay", "rent the market will bear"],
  dialNote: "every landlord's rent is every other landlord's comp",
  archetype: "the renter who finally got in",
  boardLabel: "LENDER",
  firedTitle: "FORECLOSED",
  firedBody:
    "You fell behind on the note. The lender foreclosed and sold the building to an investment fund that owns eleven hundred units in the East Bay. The rents went up the first month.",
  boardPressure: [
    "The lender sent a letter about your debt-service coverage ratio.",
    "Your note is under review. The fund that owns the building next door sent a friendly offer.",
  ],
  ranks: [
    { title: "Landlord", perk: "one building, one note" },
    { title: "Small Landlord", perk: "a property manager on speed dial" },
    { title: "Investor", perk: "a second building in Fruitvale" },
    { title: "Portfolio", perk: "an LLC for each property" },
    { title: "Association Board", perk: "the council takes your calls" },
    { title: "The Market", perk: "they cite your rents as comps" },
  ],
  intro: [
    "You're Keisha Henderson. After six years of being three months from a down payment, your aunt passes and leaves you a share of her fourplex in West Oakland.",
    "Buying out your cousins means a mortgage bigger than your nursing salary. The only way to carry it is the rent.",
    "The lender watches one number: whether the building covers the note. There's a dial between rent a neighbor can pay and rent the market will bear.",
    "The lights on the wall are tenants — in your building and every building like it. The market price is what every landlord does. Including you.",
  ],
  actLabel: "DECIDE",
  introCta: "Take the keys ›",
  resultCapture: "The building cash-flows. Your old classmate from Castlemont moved to Stockton.",
  resultProtect: "Your tenants stayed. The lender's spreadsheet didn't like it.",
  outLabel: "FALLOUT THIS YEAR",
  closingQuestion: {
    fired: "A fund owns it now and does it anyway. What would have had to change for housing not to be the investment?",
    ended: "You finally got in. What did it cost the people who came after you?",
  },
  turns: [
    turn(2018, "YOU INHERIT A SHARE · YOUR COUSINS WANT OUT", ["Buy them out slowly, keep the rents", 0.26], ["Refinance to the max, raise rents to cover it", 0.55]),
    turn(2019, "A SOFTWARE COMPANY OFFERS 'PRICING OPTIMIZATION'", ["Set your own rents", 0.3], ["Let the algorithm set them", 0.72], "⚙"),
    turn(2020, "THE PANDEMIC · AN EVICTION MORATORIUM", ["Forgive the back rent", 0.3], ["Cash-for-keys the tenant who fell behind", 0.76], "✂"),
    turn(2021, "A SHORT-TERM RENTAL MAKES 3× AS MUCH", ["Keep it long-term", 0.3], ["Turn Unit B into a nightly rental", 0.8]),
    turn(2022, "THE CITY PROPOSES A FOURPLEX NEXT DOOR", ["Speak for it at the hearing", 0.32], ["Sign the neighbors' letter against it", 0.84], "✂"),
    turn(2023, "RENT CONTROL IS ON THE BALLOT", ["Vote for it, eat the cap", 0.3], ["Join the landlords' association campaign", 0.88], "⚡"),
    turn(2025, "AN INVESTMENT FUND OFFERS CASH FOR THE BUILDING", ["Sell to the tenants' land trust for less", 0.32], ["Take the fund's cash", 0.93]),
  ],
};

export const TRUSTEE: SeatConfig = {
  id: "trustee",
  title: "The Trustee",
  role: "Pension Board Trustee",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#8FA3B8",
  litColor: WARM,
  scoreLabel: "RETURNS",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["invest like a steward", "chase the return"],
  dialNote: "the promise needs 7% a year; bonds pay 3",
  archetype: "the teacher whose pension owns the buyout",
  boardLabel: "LEGISLATURE",
  firedTitle: "REPLACED",
  firedBody:
    "The legislature called the fund 'underperforming' and replaced the elected trustees with appointees from finance. They doubled the private equity allocation at their first meeting.",
  boardPressure: [
    "A legislator called the fund's returns 'a problem for taxpayers.'",
    "The governor's office floated 'professionalizing' the board. They meant you.",
  ],
  ranks: [
    { title: "Trustee", perk: "a seat and a binder" },
    { title: "Committee Chair", perk: "the consultants take you to dinner" },
    { title: "Vice-Chair", perk: "a conference in Scottsdale" },
    { title: "Board Chair", perk: "your name in the trade press" },
    { title: "National Council", perk: "other funds copy your allocation" },
    { title: "Industry Advisor", perk: "a paid seat at the buyout firm" },
  ],
  intro: [
    "You're Jim Peterson. Thirty-one years teaching eighth-grade civics. The retired teachers elected you to the state pension board.",
    "The fund has a hole in it. To keep the promise to people like you, it needs 7% a year. Bonds pay 3.",
    "The legislature watches one number: returns. There's a dial between investing like a steward and chasing the return.",
    "The lights on the wall are workers at companies the fund owns — through private equity, through deals you'll only ever see as a line in a quarterly report.",
  ],
  actLabel: "DECIDE",
  introCta: "Take your seat ›",
  resultCapture: "Returns beat the target. Somewhere in Ohio, a retailer closed 400 stores. The fund's share of the loss was a rounding error.",
  resultProtect: "The fund lagged its peers. The legislature noticed first.",
  outLabel: "FALLOUT THIS QUARTER",
  closingQuestion: {
    fired: "Appointees did it anyway. What would have had to change for your pension not to depend on someone else's layoff?",
    ended: "Your pension is safe. Whose paycheck is it made of?",
  },
  turns: [
    turn(2009, "THE FUND LOST A QUARTER OF ITS VALUE", ["Stay in index funds, ride it out", 0.26], ["Hire the consultants, go 'alternative'", 0.55]),
    turn(2011, "THE GOVERNOR WANTS TO CUT BENEFITS · YOU NEED RETURNS", ["Accept a smaller, honest target", 0.3], ["Commit $2 billion to private equity", 0.68]),
    turn(2014, "A BUYOUT FIRM TAKES A RETAILER PRIVATE · THE FUND IS IN", ["Ask about the jobs in the deal", 0.3], ["Don't ask. Returns are returns.", 0.76], "✂"),
    turn(2016, "THE BUYOUT FUND IS BUYING NURSING HOMES", ["Vote to exclude nursing homes", 0.32], ["It's the best-returning sector", 0.8]),
    turn(2019, "THE FEES ARE SECRET · THE FIRM WON'T DISCLOSE", ["Demand the fees in writing", 0.3], ["Sign the confidentiality agreement", 0.84]),
    turn(2020, "A MOBILE HOME PARK FUND · 14% RETURNS", ["Pass", 0.3], ["Allocate", 0.88]),
    turn(2023, "THE FUND IS FULLY FUNDED FOR THE FIRST TIME", ["Announce the tradeoffs publicly", 0.32], ["Double the private credit allocation", 0.93]),
  ],
};

export const COUNCIL: SeatConfig = {
  id: "council",
  title: "The Council Member",
  role: "Parish Council, District 5",
  mode: "extract",
  stat: "power",
  statScale: 0.9,
  sideStats: { fame: 0.018, money: 0.02 },
  scoreColor: "#D98A4D",
  litColor: WARM,
  scoreLabel: "INVESTMENT",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["the people by the fence", "the tax base"],
  dialNote: "the plants are the only employer that pays",
  archetype: "the council member who approved the corridor one vote at a time",
  actLabel: "VOTE",
  boardLabel: "COUNCIL",
  firedTitle: "VOTED OUT",
  firedBody:
    "The industry PAC funded your opponent in the next election. She won by two hundred votes and approved the complex at her first meeting.",
  boardPressure: [
    "The chemical association's lobbyist stopped returning your calls.",
    "A mailer went out in your district calling you 'anti-jobs.' Nobody will say who paid for it.",
  ],
  ranks: [
    { title: "Council Member", perk: "a seat and a nameplate" },
    { title: "Committee Chair", perk: "the plant managers know your name" },
    { title: "Council Chair", perk: "the ribbon cuttings" },
    { title: "Parish President", perk: "a parish that runs on plant money" },
    { title: "State Representative", perk: "a seat on the energy committee" },
    { title: "Industry Board", perk: "a paid seat at the chemical association" },
  ],
  intro: [
    "You're Denise Batiste. Your family has lived on the same road along the river since 1870. Now you represent it on the parish council.",
    "The plants came for the river and the cheap land. They brought the only jobs that pay, and air your mother's doctor asked her about.",
    "Every expansion needs a vote. The council counts on you to keep the investment coming. There's a dial between the people by the fence and the tax base.",
    "The lights on the wall are the parish. Some of them work at the plants. Most of them live downwind.",
  ],
  introCta: "Call the meeting to order ›",
  resultCapture: "The motion carried. The plant manager shook your hand at the ribbon cutting. Two more families on your road put their houses up for sale.",
  resultProtect: "You voted no. The motion carried anyway, 5–2, and the council remembered.",
  outLabel: "FALLOUT THIS SESSION",
  closingQuestion: {
    fired: "Someone else cast the vote. What would have had to change for the parish not to need the plants?",
    ended: "The parish got its investment. Who in the parish got to decide what it cost?",
  },
  turns: [
    turn(1998, "A PLASTICS PLANT WANTS TO BUILD · TEN YEARS TAX-FREE", ["Demand a health study first", 0.26], ["Approve it — the parish needs jobs", 0.55]),
    turn(2002, "THE STATE GRANTS THE EXEMPTION · THE SCHOOLS LOSE THE REVENUE", ["Fight for the school millage", 0.3], ["Don't cross the state board", 0.68]),
    turn(2006, "THE PLANT WANTS TO EXPAND ONTO AN OLD BURIAL GROUND", ["Protect the graves", 0.3], ["Rezone it industrial", 0.76]),
    turn(2010, "AN AIR MONITOR READS HIGH · THE PLANT SAYS IT'S MISCALIBRATED", ["Ask the state to investigate", 0.32], ["Accept the plant's own numbers", 0.8]),
    turn(2014, "A BUYOUT OFFER FOR THE HOMES NEAREST THE FENCE", ["Hold out for full relocation", 0.3], ["Take the offer as written", 0.84]),
    turn(2019, "A $9 BILLION COMPLEX · THE LARGEST IN PARISH HISTORY", ["Vote no", 0.3], ["Vote yes — the council is with you", 0.88]),
    turn(2021, "AFTER THE HURRICANE · WHO GETS POWER BACK FIRST", ["The homes first", 0.32], ["The plants first — they're the tax base", 0.93]),
  ],
};

export const PASTOR: SeatConfig = {
  id: "pastor",
  title: "The Pastor",
  role: "Senior Pastor",
  mode: "attn",
  stat: "fame",
  statScale: 0.05,
  sideStats: { money: 0.03 },
  scoreColor: "#C9A96F",
  litColor: EMBER,
  scoreLabel: "ATTENDANCE",
  litLabel: "still reads past the headline",
  lives: CIV_LIVES,
  dial: ["shepherd the flock", "grow the crowd"],
  dialNote: "a room with an enemy fills fastest",
  archetype: "the pastor whose pulpit became a platform",
  actLabel: "PREACH",
  boardLabel: "ELDERS",
  firedTitle: "REPLACED",
  firedBody:
    "The elders brought in a younger pastor from a Dallas megachurch who did everything you wouldn't. Attendance doubled. The hospital visits stopped.",
  boardPressure: [
    "The building fund came in short again. The elders want to talk about 'vision.'",
    "Two elders met without you. The chairman says they're 'praying about the church's direction.'",
  ],
  ranks: [
    { title: "Pastor", perk: "a pulpit and a strip-mall lease" },
    { title: "Senior Pastor", perk: "a sanctuary with your name on the plaque" },
    { title: "Multi-Site Pastor", perk: "your face on screens in three towns" },
    { title: "Conference Speaker", perk: "a book deal" },
    { title: "Network Regular", perk: "a weekly cable segment" },
    { title: "Movement Leader", perk: "candidates ask for your blessing" },
  ],
  intro: [
    "You're Wade Tillman. You planted Crossroads Church in a strip mall in 2004. It's four thousand people now, and you still make every hospital visit you can.",
    "When the plant closed and the paper folded, the church became the town square. It's where people find work, meals, and each other.",
    "It also carries a twelve-million-dollar note on the new sanctuary. The elders watch one number: attendance. There's a dial between shepherding the flock and growing the crowd.",
    "The lights on the wall are the town. They trust you more than anyone on television. That's the responsibility — and the leverage.",
  ],
  introCta: "Step up to the pulpit ›",
  resultCapture: "The room was packed. The clip went around town by Monday. The Bible study that used to argue about Romans now argues about the news.",
  resultProtect: "A quiet sermon, a smaller crowd. The offering came in light, and the elders noticed.",
  outLabel: "FALLOUT THIS SUNDAY",
  closingQuestion: {
    fired: "Someone else filled the room. What would have had to change for a full church not to need an enemy?",
    ended: "The pews are full. Is the town more of a community than when you started?",
  },
  turns: [
    turn(2008, "THE SANCTUARY IS FULL · THE ELDERS WANT A SECOND CAMPUS", ["Plant a sister church with its own pastor", 0.26], ["Livestream your sermon to a satellite campus", 0.55], "▶"),
    turn(2012, "THE CHURCH APP LAUNCHES · SERMON CLIPS SPREAD FAST", ["Keep the sermons for the room", 0.3], ["Cut the fiery clips for social media", 0.68], "▶"),
    turn(2016, "AN ELECTION YEAR · A CANDIDATE ASKS FOR THE PULPIT", ["Keep politics out of the pulpit", 0.3], ["Host the rally in the sanctuary", 0.76], "⚡"),
    turn(2018, "THE CHURCH FACEBOOK GROUP · RUMORS ABOUT THE NEW FAMILIES IN TOWN", ["Shut the rumor down from the pulpit", 0.32], ["Let it run — people are talking", 0.8], "⚡"),
    turn(2020, "THE PANDEMIC · THE STATE LIMITS GATHERINGS", ["Move online, protect the elderly", 0.3], ["Preach defiance, pack the room", 0.84], "⚡"),
    turn(2022, "A CABLE NETWORK WANTS YOU AS A REGULAR GUEST", ["Decline — the congregation is enough", 0.3], ["Go on air every week", 0.88], "▶"),
    turn(2024, "THE DENOMINATION SPLITS · MEMBERS PICK SIDES", ["Keep both sides at one table", 0.32], ["Name the enemy, keep the bigger half", 0.93], "⚡"),
  ],
};

export const UNION_LOCAL: SeatConfig = {
  id: "local",
  title: "The Local President",
  role: "President, Refinery Workers Local",
  mode: "extract",
  stat: "power",
  statScale: 0.9,
  sideStats: { fame: 0.018, money: 0.02 },
  scoreColor: "#D9544D",
  litColor: WARM,
  scoreLabel: "MEMBER SECURITY",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["everyone on the channel", "the members you have"],
  dialNote: "the members vote; the new hires and the neighbors don't",
  archetype: "the union man who protected his own",
  actLabel: "SIGN",
  boardLabel: "MEMBERSHIP",
  firedTitle: "VOTED OUT",
  firedBody:
    "The members voted you out for a challenger who promised no strikes. He signed the company's contract within a month, the one you wouldn't.",
  boardPressure: [
    "Guys are grumbling in the parking lot. They think you're going to get them locked out.",
    "A challenger is collecting signatures for a recall vote. He's telling people you care more about outsiders than members.",
  ],
  ranks: [
    { title: "Local President", perk: "a desk at the hall and a truck" },
    { title: "Chief Negotiator", perk: "the company knows your cell" },
    { title: "District Director", perk: "six locals on the channel" },
    { title: "International VP", perk: "a seat in Pittsburgh" },
    { title: "Labor Board", perk: "the governor's appointment" },
    { title: "Company Advisor", perk: "a consulting contract with the other side" },
  ],
  intro: [
    "You're Ray Villarreal. Twenty-six years as an operator at the refinery on the Houston Ship Channel. Your father worked the same unit. The members just elected you president of the local.",
    "You can see the flare from your kitchen in Pasadena. So can your neighbors, most of whom have never set foot in the plant.",
    "The members want one thing: their jobs and their pensions, safe. There's a dial between fighting for everyone on the channel and protecting the members you have.",
    "The lights on the wall are the east side of Houston: members, new hires, contractors, the families downwind. Only some of them get a vote at the hall.",
  ],
  introCta: "Open the union hall ›",
  resultCapture: "The members ratified it by a wide margin. Somebody's kid who starts next year will make seventy cents on your dollar.",
  resultProtect: "You held the line for people who can't vote for you. The members are asking whose side you're on.",
  outLabel: "FALLOUT THIS CONTRACT",
  closingQuestion: {
    fired: "Someone else signed the deal. What would have had to change for the members' security not to cost everyone else theirs?",
    ended: "Your members kept their pensions. Who paid for the ones they kept?",
  },
  turns: [
    turn(2001, "THE COMPANY WANTS A TWO-TIER CONTRACT · NEW HIRES AT 70%", ["Strike for one tier", 0.26], ["Take it — protect the members you have", 0.55], "✎"),
    turn(2005, "A REFINERY EXPLODES DOWN THE CHANNEL · FIFTEEN DEAD", ["Demand an independent safety audit", 0.3], ["Trade the safety demands for a raise", 0.68], "✎"),
    turn(2009, "TURNAROUND SEASON · NON-UNION CONTRACTORS AT HALF PAY", ["Grieve every contractor hire", 0.3], ["Let it slide — our guys get the overtime", 0.76]),
    turn(2012, "THE REFINERY WANTS A TAX ABATEMENT · THE SCHOOL DISTRICT PAYS", ["Tell the school board what it costs", 0.32], ["Pack the hearing in union shirts", 0.8], "⚡"),
    turn(2017, "THE HURRICANE · A TANK LEAKS INTO THE NEIGHBORHOOD", ["Go public about what spilled", 0.3], ["Keep quiet — the plant restarts sooner", 0.84], "✂"),
    turn(2021, "THE FREEZE · THE PLANT FLARES FOR A WEEK", ["Back the neighbors' lawsuit", 0.3], ["Sign the company's statement", 0.88], "✎"),
    turn(2024, "EARLY RETIREMENT · ONLY FOR TOP SENIORITY", ["Hold out for everyone", 0.32], ["Take the deal for the old guard", 0.93], "✎"),
  ],
};

export const MILL: SeatConfig = {
  id: "mill",
  title: "The Mill Owner",
  role: "CEO, Hardwick Mills",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#7FA35A",
  litColor: WARM,
  scoreLabel: "DIVIDEND",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["keep the town whole", "keep the family paid"],
  dialNote: "forty cousins own shares, and none of them live in Dalton",
  archetype: "the heir who kept the family paid",
  boardLabel: "THE FAMILY",
  firedTitle: "REPLACED",
  firedBody:
    "The family voted to bring in a turnaround CEO from Atlanta. He closed two mills and sold the brand, and the cousins got their dividend.",
  boardPressure: [
    "Your cousin in Charlotte called about 'the family's returns.' He's never been inside the mill.",
    "The family board is meeting without you in Atlanta. Your aunt said it was 'just a lunch.'",
  ],
  ranks: [
    { title: "President", perk: "your grandfather's office" },
    { title: "CEO", perk: "the mill's name on the high school stadium" },
    { title: "Chairman & CEO", perk: "the family defers to you" },
    { title: "Industry Chair", perk: "you speak for carpet in Washington" },
    { title: "Chamber President", perk: "the governor comes to your ribbon cuttings" },
    { title: "Hall of Fame", perk: "a portrait at the trade association" },
  ],
  intro: [
    "You're Tom Hardwick. Your grandfather started tufting bedspreads in a Dalton garage in 1948. Now Hardwick Mills runs three plants, and you're the third Hardwick to run it.",
    "Dalton makes most of the carpet in America. Half the town has worked a Hardwick line at some point. You know the shift leads by name.",
    "The family owns the company. The cousins watch one number: the dividend. There's a dial between keeping the town whole and keeping the family paid.",
    "The lights on the wall are Dalton: the line workers, the families who came from Mexico to run the machines, the people downstream who drink the river.",
  ],
  introCta: "Walk the mill floor ›",
  resultCapture: "The dividend went out on time. The family sent a nice card. A line in the old mill went quiet.",
  resultProtect: "The town noticed. So did the cousins: the dividend came in light.",
  outLabel: "FALLOUT THIS YEAR",
  closingQuestion: {
    fired: "An outsider made the cuts anyway. What would have had to change for the family to want a town more than a dividend?",
    ended: "Hardwick Mills survived. What did it leave in the river?",
  },
  turns: [
    turn(1994, "A NEW TRADE DEAL · A PLANT IN MEXICO COSTS HALF", ["Keep every line in Dalton", 0.26], ["Move the backing line south", 0.55], "✈"),
    turn(1999, "A STAIN-PROOF COATING · CUSTOMERS LOVE IT", ["Test what's in the wastewater first", 0.3], ["Ship it — the supplier says it's safe", 0.68], "⚗"),
    turn(2004, "THE LINES NEED WORKERS · A LABOR CONTRACTOR OFFERS CREWS", ["Hire direct, full wages", 0.3], ["Take the contractor's crews, no questions", 0.76]),
    turn(2009, "THE HOUSING CRASH · ORDERS DOWN 40%", ["Short weeks for everyone", 0.32], ["Close the oldest mill", 0.8], "✂"),
    turn(2013, "THE RIVER TESTS HIGH FOR 'FOREVER CHEMICALS'", ["Fund the cleanup", 0.3], ["Let the water utility handle it; lawyer up", 0.84], "⚗"),
    turn(2020, "THE PANDEMIC · THE MILL IS 'ESSENTIAL'", ["Pay people to stay home sick", 0.3], ["Keep the lines running, no sick pay", 0.88]),
    turn(2023, "A GLOBAL RIVAL OFFERS TO BUY · THE COUSINS WANT OUT", ["Buy the cousins out, stay in Dalton", 0.32], ["Sell and let them consolidate", 0.93]),
  ],
};
