import type { SeatConfig, SeatTurn } from "../types";
import { CIV_LIVES, ECON_LIVES } from "../constants";

const WARM = "#E8A24A";
const EMBER = "#F2C46D";

function turn(y: number, ch: string, protect: [string, number], capture: [string, number], glyph = "$"): SeatTurn {
  return {
    y,
    ch,
    o: [
      { id: "a", name: protect[0], glyph: "◍", type: "protect", pull: protect[1] },
      { id: "b", name: capture[0], glyph, type: "capture", pull: capture[1] },
    ],
  };
}

export const SUPERVISOR: SeatConfig = {
  id: "supervisor",
  title: "The Shift Supervisor",
  role: "Shift Supervisor",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#C9853F",
  litColor: WARM,
  scoreLabel: "UNITS PER HOUR",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["protect the crew", "hit the rate"],
  dialNote: "the rate only goes one direction",
  archetype: "the local man handed the quota",
  boardLabel: "DISTRICT",
  firedBody:
    "District brought in a supervisor from the Charleston site who hit the rate in a month. Your crew got the same quotas, from someone who didn't know their names.",
  boardPressure: [
    "District flagged your building's rate on the regional call.",
    "Your district manager is driving down Thursday. Nobody drives down on good news.",
  ],
  ranks: [
    { title: "Shift Supervisor", perk: "a radio and a clipboard" },
    { title: "Area Manager", perk: "salaried, no more overtime" },
    { title: "Operations Manager", perk: "a parking spot by the door" },
    { title: "Site Leader", perk: "stock grants" },
    { title: "Regional Director", perk: "three buildings, two states" },
    { title: "VP, Fulfillment", perk: "they fly you to headquarters" },
  ],
  intro: [
    "You're Roger Morrison. Four years after the mine closed, the distribution center on Route 52 is the best job in the county — and they've made you shift supervisor.",
    "The lights on the wall are the people on your shifts and the families behind them. Your neighbors. Your church. Men you worked underground with.",
    "District gives you one number: units per hour. There's a dial between protecting the crew and hitting the rate. District watches the rate.",
    "Nobody here will complain out loud. They need this job more than you do. That's what makes it work.",
  ],
  actLabel: "DECIDE",
  introCta: "Clock in ›",
  resultCapture: "The rate climbed. District sent a congratulations email. Two more guys didn't come back after break.",
  resultProtect: "The crew noticed. So did the dashboard. Your building was bottom of the region.",
  outLabel: "FALLOUT THIS SHIFT",
  closingQuestion: {
    fired: "They replaced you with someone who hit the rate. What would have had to change for the rate not to be the only number?",
    ended: "The rate went up every year. Is the county better off than when the mine closed?",
  },
  turns: [
    turn(2017, "THE CENTER OPENS · 400 JOBS FOR A COUNTY THAT LOST 3,000", ["Hire the older miners, train them right", 0.26], ["Hire through the temp agency — cheaper", 0.55]),
    turn(2018, "THE RATE GOES UP 8% · NOBODY ASKED THE FLOOR", ["Push back on district", 0.3], ["Post the leaderboard by the time clock", 0.68], "⚙"),
    turn(2019, "UNION CARDS IN THE BREAK ROOM", ["Stay out of it", 0.3], ["Forward the names to HR", 0.76], "✂"),
    turn(2020, "THE PANDEMIC SURGE · MANDATORY OVERTIME", ["Cap the hours, rotate the crews", 0.3], ["Sixty-hour weeks; hazard pay ends in June", 0.82]),
    turn(2021, "A BACK INJURY ON LINE 4", ["Report it as a workplace injury", 0.32], ["On-site clinic, keep it off the books", 0.86], "✂"),
    turn(2022, "THE ROBOTS ARRIVE · HALF THE PICKERS ARE 'REDEPLOYED'", ["Fight to retrain them", 0.3], ["Pick who goes, by rate", 0.9], "⚙"),
    turn(2024, "THE CENTER MIGHT CLOSE · THE COUNTY OFFERS A TAX BREAK TO STAY", ["Tell the county to let them go", 0.32], ["Testify for the tax break; the school levy gets cut", 0.92]),
  ],
};

export const FLEET: SeatConfig = {
  id: "fleet",
  title: "The Fleet Partner",
  role: "Fleet Partner",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#3FA7A0",
  litColor: WARM,
  scoreLabel: "FLEET REVENUE",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["fair terms", "squeeze the lease"],
  dialNote: "the app takes its cut first; you take yours second",
  archetype: "the driver who got out of the driver's seat",
  boardLabel: "PLATFORM",
  firedBody:
    "The platform reassigned your drivers to a fleet company out of Scottsdale with two hundred cars and no idea anyone's name. The terms got worse. The cars stayed on the road.",
  boardPressure: [
    "The platform moved you down a partner tier. Fewer rides are routed to your fleet.",
    "The app emailed: partners below target will be 'transitioned' at quarter end.",
  ],
  ranks: [
    { title: "Fleet Partner", perk: "two cars and a spreadsheet" },
    { title: "Top Partner", perk: "a badge on the app" },
    { title: "Fleet Owner", perk: "an LLC and an accountant" },
    { title: "Platinum Partner", perk: "the app returns your calls" },
    { title: "Regional Fleet", perk: "forty cars, three cities" },
    { title: "The Ad", perk: "they put you in the commercial about 'opportunity'" },
  ],
  intro: [
    "You're Maria Flores-Garcia. Four years of driving, a 4.97 rating, and the app just offered you a way out of the driver's seat: become a fleet partner.",
    "You lease cars to other drivers — people exactly like you were — and take a cut of every fare they drive.",
    "The platform ranks its partners. Fall behind and your drivers get reassigned to someone else. There's a dial between fair terms and squeezing the lease.",
    "The drivers on the wall are your cousins, friends from church, strangers from the Facebook group. They'll sign whatever you put in front of them. They need the car.",
  ],
  actLabel: "DECIDE",
  introCta: "Log in as a partner ›",
  resultCapture: "Revenue up. One of your drivers is sleeping in the car now — but he's driving.",
  resultProtect: "Your drivers were grateful. The platform dashboard was not.",
  outLabel: "FALLOUT THIS MONTH",
  closingQuestion: {
    fired: "Someone with more cars took your drivers. What would have had to change for the lease not to be the business?",
    ended: "You got out of the driver's seat. How many people did it take to hold it for you?",
  },
  turns: [
    turn(2019, "THE APP OFFERS FLEET PARTNER STATUS", ["Lease two cars at cost to your cousins", 0.26], ["Sign up ten drivers for the referral bonus", 0.55]),
    turn(2020, "THE PANDEMIC · RIDES DROP 70%", ["Pause the lease payments", 0.3], ["Payments due Friday, same as always", 0.7]),
    turn(2020, "A STATE BILL · DRIVERS ARE CONTRACTORS FOREVER", ["Tell your drivers what it takes from them", 0.3], ["Put the app's flyer in every car", 0.76], "⚡"),
    turn(2021, "GAS HITS FIVE DOLLARS", ["Eat the fuel surcharge", 0.3], ["Pass it all to the drivers", 0.8]),
    turn(2022, "A DRIVER IS DEACTIVATED · NO REASON GIVEN", ["Fight the app for her", 0.32], ["Give her car to the next name on the list", 0.84], "✂"),
    turn(2023, "THE LEASE TERMS ARE UP FOR RENEWAL", ["Write a path to ownership into the contract", 0.3], ["Add a mileage cap and a damage fee", 0.9]),
    turn(2024, "THE APP CUTS DRIVER PAY 15% · THE FLEET SHARE IS UNCHANGED", ["Stop recruiting until it's reversed", 0.32], ["Recruit harder — there's always someone newer", 0.93]),
  ],
};

export const ENGINEER: SeatConfig = {
  id: "engineer",
  title: "The Engineer",
  role: "Senior Engineer, Growth",
  mode: "attn",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#9B7FD9",
  litColor: EMBER,
  scoreLabel: "ENGAGEMENT",
  litLabel: "still reads past the headline",
  lives: CIV_LIVES,
  dial: ["ship it clean", "optimize for time spent"],
  dialNote: "the metric is minutes, not meaning",
  archetype: "the engineer who only ever shipped what the metric asked for",
  boardLabel: "REVIEW",
  firedTitle: "REORGED OUT",
  firedBody:
    "Your review said 'lacks impact.' They moved you off Growth and gave your roadmap to a new grad who shipped all of it in a quarter. The feed got stickier without you.",
  boardPressure: [
    "Your manager asked why your launch moved the metric less than forecast.",
    "Calibration is next week. Your manager says your 'impact narrative' needs work.",
  ],
  ranks: [
    { title: "Senior Engineer", perk: "RSUs, vesting quarterly" },
    { title: "Staff Engineer", perk: "your name on the launch memo" },
    { title: "Principal", perk: "a seat in the metrics review" },
    { title: "Director, Growth", perk: "your own org" },
    { title: "VP Engineering", perk: "the stock is your net worth now" },
    { title: "Keynote", perk: "you explain 'connection' on stage" },
  ],
  intro: [
    "You're David Nguyen. Senior engineer on the Growth team at a social platform with two billion users. The kids are asleep upstairs; the laptop is open.",
    "The lights on the wall are users — a small town's worth of them. The PTA chair, the retiree who reads every notice, the teenager up past midnight.",
    "Your review is graded on one number: engagement. There's a dial between shipping it clean and optimizing for time spent.",
    "Nothing you ship hurts anyone on the day it ships. The civic numbers show up next quarter — if anyone measures them.",
  ],
  actLabel: "DECIDE",
  introCta: "Open the laptop ›",
  resultCapture: "Time spent up 4%. The launch post got a thousand emoji reacts. Somewhere a town meeting had eleven people.",
  resultProtect: "Engineering-wise, beautiful. The metric was flat, and the review cycle noticed.",
  outLabel: "FALLOUT THIS CYCLE",
  closingQuestion: {
    fired: "The roadmap shipped without you. What would have had to change for time spent not to be the goal?",
    ended: "Every launch hit its number. What did the people on the wall stop doing with the hours you won?",
  },
  turns: [
    turn(2012, "MOBILE IS EVERYTHING · MAKE THE FEED STICKY", ["Chronological feed, a clear stopping point", 0.26], ["Infinite scroll", 0.55], "∞"),
    turn(2014, "NOTIFICATIONS DRIVE RETURN VISITS", ["Notify only on real messages", 0.3], ["Red badges for everything", 0.68], "●"),
    turn(2016, "OUTRAGE GETS 6× THE SHARES · THE DATA IS CLEAR", ["Downrank rage bait, eat the dip", 0.3], ["Rank by reactions — all of them", 0.8], "⚡"),
    turn(2018, "AN INTERNAL STUDY · TEENS FEEL WORSE AFTER USING IT", ["Take it to leadership, in writing", 0.32], ["Nobody asked you to read that deck", 0.84], "●"),
    turn(2020, "THE ELECTION INTEGRITY TEAM IS DISSOLVED", ["Volunteer to keep the guardrails running", 0.3], ["Join the new team — it's a promotion", 0.88], "⚡"),
    turn(2022, "SHORT VIDEO IS EATING OUR LUNCH", ["Keep friends and family at the center", 0.3], ["Autoplay strangers, forever", 0.9], "∞"),
    turn(2024, "AI CONTENT IS CHEAPER THAN PEOPLE", ["Label it, limit it", 0.32], ["Flood the feed — the metric can't tell", 0.93], "⚙"),
  ],
};

export const OWNER: SeatConfig = {
  id: "owner",
  title: "The Owner",
  role: "CEO, Kellerman Heating & Air",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#46B17F",
  litColor: WARM,
  scoreLabel: "MARGIN",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["run it for the people", "run it for the multiple"],
  dialNote: "the buyer pays for margin, not loyalty",
  archetype: "the founder who became a platform company",
  boardLabel: "LENDER",
  firedTitle: "BOUGHT OUT",
  firedBody:
    "The bank called the note. The firm bought the company out of the wreckage at half the multiple, put a new logo on your father's vans, and did everything you wouldn't — the same year.",
  boardPressure: [
    "Your banker asked to 'grab coffee.' It was not about coffee.",
    "The line of credit is under review. The firm's number is on your desk.",
  ],
  ranks: [
    { title: "Owner", perk: "four vans and a line of credit" },
    { title: "Founder-CEO", perk: "a logo someone else designed" },
    { title: "Platform CEO", perk: "three acquired shops" },
    { title: "Regional CEO", perk: "the roll-up's poster company" },
    { title: "Operating Partner", perk: "equity in the fund" },
    { title: "Exited", perk: "a lake house and a nondisclosure" },
  ],
  intro: [
    "You're Sandra Kellerman. Twenty years, seven employees, four vans with your father's name on the side. It's a real company now, and you're its CEO.",
    "The lights on the wall are your crew, your customers, and the families who've called you at 2am when the furnace quit.",
    "The bank that holds your line of credit watches one number: margin. There's a dial between running it for the people and running it for the multiple.",
    "A private equity firm has been buying up HVAC shops across Oklahoma. They've already called twice.",
  ],
  actLabel: "DECIDE",
  introCta: "Unlock the shop ›",
  resultCapture: "Margin up. The firm sent a bottle of scotch. Mrs. Alvarez paid $14,000 for a unit that needed a $300 part.",
  resultProtect: "The crew stayed loyal. The bank read the margin and frowned.",
  outLabel: "FALLOUT THIS QUARTER",
  closingQuestion: {
    fired: "Someone else bought the vans and did it anyway. What would have had to change for you to stay small and survive?",
    ended: "You built something and sold it for what it was worth. What was it worth to the people who worked there?",
  },
  turns: [
    turn(2015, "A PRIVATE EQUITY FIRM IS ROLLING UP HVAC IN OKLAHOMA", ["Stay independent", 0.26], ["Take their 'growth partnership' money", 0.55]),
    turn(2016, "THE NEW PARTNERS WANT A SALES QUOTA FOR TECHS", ["Techs fix what's broken, nothing more", 0.3], ["Commission on every replacement sold", 0.7]),
    turn(2018, "THE HEALTH PLAN RENEWAL IS UP 31%", ["Absorb it, keep the family plan", 0.3], ["Switch everyone to a high-deductible plan", 0.76], "✂"),
    turn(2020, "THE PANDEMIC · A LOAN THAT BECOMES A GIFT", ["Spend it on payroll, like it says", 0.3], ["Payroll on paper; pay down the debt", 0.8]),
    turn(2021, "A NON-COMPETE FOR EVERY TECH", ["They can work wherever they want", 0.32], ["Two years, fifty miles — sign or go", 0.84], "✂"),
    turn(2022, "THE FIRM WANTS A 'MAINTENANCE MEMBERSHIP' PROGRAM", ["Keep it simple: fix-it pricing", 0.3], ["Auto-renew, hard to cancel", 0.88]),
    turn(2023, "THE FIRM OFFERS TO BUY YOU OUT AT 9× EARNINGS", ["Sell to your employees instead", 0.32], ["Take the check", 0.93]),
  ],
};

export const EXPERT: SeatConfig = {
  id: "expert",
  title: "The Expert Witness",
  role: "Consulting Economist",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#6FA8C9",
  litColor: WARM,
  scoreLabel: "MARKET POWER",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["what the data says", "what the client needs"],
  dialNote: "the firm keeps the experts who win",
  archetype: "the scholar whose model became the industry standard",
  boardLabel: "THE FIRM",
  firedTitle: "OFF THE CASE",
  firedBody:
    "You lost a case the firm needed. They brought in an economist from Chicago whose reports never lose. The mergers went through on schedule.",
  boardPressure: [
    "A partner mentioned that the client 'expected a cleaner report.'",
    "The firm is 'reviewing staffing' on the next engagement. Your name isn't on the list yet.",
  ],
  ranks: [
    { title: "Consultant", perk: "$650 an hour" },
    { title: "Senior Consultant", perk: "your own research team" },
    { title: "Affiliated Expert", perk: "your name on the letterhead" },
    { title: "Principal", perk: "clients ask for you by name" },
    { title: "Testifying Expert", perk: "your model is the industry standard" },
    { title: "Endowed Chair", perk: "named for a client's founder" },
  ],
  intro: [
    "You're Amara Okafor-Walker. Seventh semester on a one-semester contract. Then an email from an economic consulting firm: $650 an hour to write expert reports.",
    "The work is antitrust. When two companies merge, someone has to tell the court whether prices will go up. Your clients pay you to say no.",
    "The firm keeps you on as long as you keep winning. There's a dial between writing what the data says and writing what the client needs.",
    "The lights on the wall are the people who'll pay the prices. They'll never read your report. It will be cited for twenty years.",
  ],
  actLabel: "DECIDE",
  introCta: "Open the data room ›",
  resultCapture: "The merger cleared. Your report was cited in the ruling. Prices at the county's only hospital rose 22%.",
  resultProtect: "The report was honest. The client was not pleased. The firm noticed.",
  outLabel: "FALLOUT THIS CASE",
  closingQuestion: {
    fired: "Another expert wrote what the client needed. What would have had to change for honest analysis to be the kind that pays?",
    ended: "You finally got the job the credential promised. Whose prices paid for it?",
  },
  turns: [
    turn(2014, "A HOSPITAL MERGER · THE ONLY TWO IN THE COUNTY", ["Report what the model shows", 0.26], ["Define the market as the whole state", 0.55], "§"),
    turn(2015, "TWO AIRLINES · ONE HUB", ["Flag the fare increase", 0.3], ["'Efficiencies will be passed to consumers'", 0.68], "§"),
    turn(2017, "A SEED AND CHEMICAL MEGAMERGER", ["Testify to what the farmers told you", 0.3], ["Innovation requires scale", 0.76], "§"),
    turn(2018, "THE UNIVERSITY OFFERS TENURE TRACK · AT A THIRD THE PAY", ["Take the job, teach it straight", 0.32], ["Stay at the firm; keep a courtesy title for credibility", 0.8]),
    turn(2019, "NON-COMPETES FOR FAST-FOOD WORKERS", ["Write that they suppress wages", 0.3], ["Write that they protect training investment", 0.84], "§"),
    turn(2021, "A GROCERY CHAIN BUYS ITS RIVAL", ["Name the towns that lose their only store", 0.3], ["Divest twelve stores, call it remedied", 0.88], "§"),
    turn(2023, "PRICES ARE UP · CONGRESS WANTS AN EXPERT", ["Testify that concentration matters", 0.32], ["Testify that it's all supply chains", 0.93], "§"),
  ],
};

export const FARMER: SeatConfig = {
  id: "farmer",
  title: "The Farmer",
  role: "Fourth-Generation Farmer",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#B5A642",
  litColor: WARM,
  scoreLabel: "LAND CONTROLLED",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["farm like a neighbor", "farm like a fund"],
  dialNote: "get big or get out",
  archetype: "the family farm that became an operation",
  boardLabel: "THE BANK",
  firedTitle: "FORECLOSED",
  firedBody:
    "The bank didn't renew the operating loan. The land went at auction to the operation across the road — the one that already farms nine thousand acres. They tore out the windbreak your grandfather planted.",
  boardPressure: [
    "Your loan officer mentioned your 'growth trajectory' twice in one meeting.",
    "The bank wants a meeting before spring planting. They sent the paperwork ahead.",
  ],
  ranks: [
    { title: "Family Farm", perk: "a section and a note" },
    { title: "Growing Operation", perk: "a new combine" },
    { title: "Large Operation", perk: "3,000 acres, some rented" },
    { title: "Farm Bureau Board", perk: "a voice in St. Paul" },
    { title: "Mega-Farm", perk: "10,000 acres, GPS-steered" },
    { title: "Ag Investor", perk: "the land is a line in a portfolio" },
  ],
  intro: [
    "You're Dale Pedersen. Fourth generation on the same section outside Mankato. The note comes due in February, like it always does.",
    "The lights on the wall are the county: neighbors, the co-op, the Lutheran church, the school that has consolidated twice.",
    "The ag lender reads one number: whether you're growing. There's a dial between farming like a neighbor and farming like a fund.",
    "Every acre you add was someone else's. That's how farming has worked for fifty years. Nobody decided it.",
  ],
  actLabel: "DECIDE",
  introCta: "Head out to the field ›",
  resultCapture: "The operation grew. The school merged again. The church moved to every other Sunday.",
  resultProtect: "Your neighbors kept their ground another year. The bank flagged your numbers.",
  outLabel: "FALLOUT THIS SEASON",
  closingQuestion: {
    fired: "Someone bigger farmed it anyway. What would have had to change for a section to be enough?",
    ended: "You held the land. How many farms did it take to hold it?",
  },
  turns: [
    turn(1998, "HOG PRICES CRASH · THE NEIGHBOR'S FARM GOES TO AUCTION", ["Let the young couple outbid you", 0.26], ["Buy it on the courthouse steps", 0.55]),
    turn(2002, "THE INTEGRATOR OFFERS A CONTRACT · THEIR PIGS, YOUR BARN", ["Stay independent", 0.3], ["Sign, build the barn, take the debt", 0.68]),
    turn(2006, "ETHANOL · CORN GOES TO $4", ["Keep the rotation, keep the soil", 0.3], ["Corn on corn, tile every acre", 0.76], "⚙"),
    turn(2012, "A PENSION FUND WANTS FARMLAND IN BLUE EARTH COUNTY", ["Sell only to farmers", 0.32], ["Farm the fund's ground for cash rent", 0.8]),
    turn(2016, "THE CO-OP VOTES ON A MERGER", ["Vote to stay local", 0.3], ["Vote for the merger — it's more efficient", 0.84]),
    turn(2019, "THE TRADE WAR · A BAILOUT CHECK, SIZED BY ACRES", ["Push for a cap on the payments", 0.3], ["Take the biggest check in the township", 0.88]),
    turn(2023, "YOUR SON WANTS TO FARM · A FUND WANTS THE WHOLE SECTION", ["Sell to your son on a contract for deed", 0.32], ["Sell to the fund; they'll rent it back", 0.93]),
  ],
};

export const LANDLORD: SeatConfig = {
  id: "landlord",
  title: "The Landlord",
  role: "Landlord",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#C96F8F",
  litColor: WARM,
  scoreLabel: "RENT ROLL",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["rent a neighbor can pay", "rent the market will bear"],
  dialNote: "every landlord's rent is every other landlord's comp",
  archetype: "the renter who finally got in",
  boardLabel: "LENDER",
  firedTitle: "FORECLOSED",
  firedBody:
    "You fell behind on the note. The lender foreclosed and sold the building to an investment fund that owns eleven hundred units in the East Bay. The rents went up the first month.",
  boardPressure: [
    "The lender sent a letter about your debt-service coverage ratio.",
    "Your note is under review. The fund that owns the building next door sent a friendly offer.",
  ],
  ranks: [
    { title: "Landlord", perk: "one building, one note" },
    { title: "Small Landlord", perk: "a property manager on speed dial" },
    { title: "Investor", perk: "a second building in Fruitvale" },
    { title: "Portfolio", perk: "an LLC for each property" },
    { title: "Association Board", perk: "the council takes your calls" },
    { title: "The Market", perk: "they cite your rents as comps" },
  ],
  intro: [
    "You're Keisha Henderson. After six years of being three months from a down payment, your aunt passes and leaves you a share of her fourplex in West Oakland.",
    "Buying out your cousins means a mortgage bigger than your nursing salary. The only way to carry it is the rent.",
    "The lender watches one number: whether the building covers the note. There's a dial between rent a neighbor can pay and rent the market will bear.",
    "The lights on the wall are tenants — in your building and every building like it. The market price is what every landlord does. Including you.",
  ],
  actLabel: "DECIDE",
  introCta: "Take the keys ›",
  resultCapture: "The building cash-flows. Your old classmate from Castlemont moved to Stockton.",
  resultProtect: "Your tenants stayed. The lender's spreadsheet didn't like it.",
  outLabel: "FALLOUT THIS YEAR",
  closingQuestion: {
    fired: "A fund owns it now and does it anyway. What would have had to change for housing not to be the investment?",
    ended: "You finally got in. What did it cost the people who came after you?",
  },
  turns: [
    turn(2018, "YOU INHERIT A SHARE · YOUR COUSINS WANT OUT", ["Buy them out slowly, keep the rents", 0.26], ["Refinance to the max, raise rents to cover it", 0.55]),
    turn(2019, "A SOFTWARE COMPANY OFFERS 'PRICING OPTIMIZATION'", ["Set your own rents", 0.3], ["Let the algorithm set them", 0.72], "⚙"),
    turn(2020, "THE PANDEMIC · AN EVICTION MORATORIUM", ["Forgive the back rent", 0.3], ["Cash-for-keys the tenant who fell behind", 0.76], "✂"),
    turn(2021, "A SHORT-TERM RENTAL MAKES 3× AS MUCH", ["Keep it long-term", 0.3], ["Turn Unit B into a nightly rental", 0.8]),
    turn(2022, "THE CITY PROPOSES A FOURPLEX NEXT DOOR", ["Speak for it at the hearing", 0.32], ["Sign the neighbors' letter against it", 0.84], "✂"),
    turn(2023, "RENT CONTROL IS ON THE BALLOT", ["Vote for it, eat the cap", 0.3], ["Join the landlords' association campaign", 0.88], "⚡"),
    turn(2025, "AN INVESTMENT FUND OFFERS CASH FOR THE BUILDING", ["Sell to the tenants' land trust for less", 0.32], ["Take the fund's cash", 0.93]),
  ],
};

export const TRUSTEE: SeatConfig = {
  id: "trustee",
  title: "The Trustee",
  role: "Pension Board Trustee",
  mode: "extract",
  stat: "money",
  statScale: 0.06,
  sideStats: { fame: 0.018 },
  scoreColor: "#8FA3B8",
  litColor: WARM,
  scoreLabel: "RETURNS",
  litLabel: "still a stable living",
  lives: ECON_LIVES,
  dial: ["invest like a steward", "chase the return"],
  dialNote: "the promise needs 7% a year; bonds pay 3",
  archetype: "the teacher whose pension owns the buyout",
  boardLabel: "LEGISLATURE",
  firedTitle: "REPLACED",
  firedBody:
    "The legislature called the fund 'underperforming' and replaced the elected trustees with appointees from finance. They doubled the private equity allocation at their first meeting.",
  boardPressure: [
    "A legislator called the fund's returns 'a problem for taxpayers.'",
    "The governor's office floated 'professionalizing' the board. They meant you.",
  ],
  ranks: [
    { title: "Trustee", perk: "a seat and a binder" },
    { title: "Committee Chair", perk: "the consultants take you to dinner" },
    { title: "Vice-Chair", perk: "a conference in Scottsdale" },
    { title: "Board Chair", perk: "your name in the trade press" },
    { title: "National Council", perk: "other funds copy your allocation" },
    { title: "Industry Advisor", perk: "a paid seat at the buyout firm" },
  ],
  intro: [
    "You're Jim Peterson. Thirty-one years teaching eighth-grade civics. The retired teachers elected you to the state pension board.",
    "The fund has a hole in it. To keep the promise to people like you, it needs 7% a year. Bonds pay 3.",
    "The legislature watches one number: returns. There's a dial between investing like a steward and chasing the return.",
    "The lights on the wall are workers at companies the fund owns — through private equity, through deals you'll only ever see as a line in a quarterly report.",
  ],
  actLabel: "DECIDE",
  introCta: "Take your seat ›",
  resultCapture: "Returns beat the target. Somewhere in Ohio, a retailer closed 400 stores. The fund's share of the loss was a rounding error.",
  resultProtect: "The fund lagged its peers. The legislature noticed first.",
  outLabel: "FALLOUT THIS QUARTER",
  closingQuestion: {
    fired: "Appointees did it anyway. What would have had to change for your pension not to depend on someone else's layoff?",
    ended: "Your pension is safe. Whose paycheck is it made of?",
  },
  turns: [
    turn(2009, "THE FUND LOST A QUARTER OF ITS VALUE", ["Stay in index funds, ride it out", 0.26], ["Hire the consultants, go 'alternative'", 0.55]),
    turn(2011, "THE GOVERNOR WANTS TO CUT BENEFITS · YOU NEED RETURNS", ["Accept a smaller, honest target", 0.3], ["Commit $2 billion to private equity", 0.68]),
    turn(2014, "A BUYOUT FIRM TAKES A RETAILER PRIVATE · THE FUND IS IN", ["Ask about the jobs in the deal", 0.3], ["Don't ask. Returns are returns.", 0.76], "✂"),
    turn(2016, "THE BUYOUT FUND IS BUYING NURSING HOMES", ["Vote to exclude nursing homes", 0.32], ["It's the best-returning sector", 0.8]),
    turn(2019, "THE FEES ARE SECRET · THE FIRM WON'T DISCLOSE", ["Demand the fees in writing", 0.3], ["Sign the confidentiality agreement", 0.84]),
    turn(2020, "A MOBILE HOME PARK FUND · 14% RETURNS", ["Pass", 0.3], ["Allocate", 0.88]),
    turn(2023, "THE FUND IS FULLY FUNDED FOR THE FIRST TIME", ["Announce the tradeoffs publicly", 0.32], ["Double the private credit allocation", 0.93]),
  ],
};
